// ccr-ui/frontend/src/components/common/EmptyState.vue
<template>
  <div
    class="glass-effect empty-state"
    role="status"
    aria-live="polite"
  >
    <div
      class="icon-wrapper"
      aria-hidden="true"
    >
      <component
        :is="icon"
        :size="48"
        :stroke-width="1.5"
      />
    </div>
    <h3 class="title">
      {{ title }}
    </h3>
    <p
      v-if="description"
      class="description"
    >
      {{ description }}
    </p>
    <button
      v-if="actionText && onAction"
      class="action-btn min-h-[44px]"
      @click="onAction"
    >
      <component
        :is="actionIcon"
        v-if="actionIcon"
        class="action-icon"
        aria-hidden="true"
      />
      {{ actionText }}
    </button>
  </div>
</template>

<script setup lang="ts">
import type { Component } from 'vue'
import { FileX } from 'lucide-vue-next'

interface Props {
  icon?: Component
  title: string
  description?: string
  actionText?: string
  actionIcon?: Component
  onAction?: () => void
}

withDefaults(defineProps<Props>(), {
  icon: () => FileX,
})
</script>

<style scoped>
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: var(--space-12);
  text-align: center;
  min-height: 300px;
}

.icon-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 80px;
  height: 80px;
  margin-bottom: var(--space-4);
  border-radius: var(--radius-full);
  background: var(--color-bg-surface);
  color: var(--color-text-muted);
}

.title {
  font-size: var(--text-xl);
  font-weight: var(--font-semibold);
  color: var(--color-text-primary);
  margin-bottom: var(--space-2);
}

.description {
  font-size: var(--text-base);
  color: var(--color-text-secondary);
  max-width: 480px;
  margin-bottom: var(--space-4);
}

.action-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-2);
  padding: var(--space-2) var(--space-4);
  font-size: var(--text-base);
  font-weight: var(--font-medium);
  color: white;
  background: var(--color-accent-primary);
  border: none;
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: all var(--duration-normal) var(--ease-out);
}

.action-icon {
  width: 18px;
  height: 18px;
}

.action-btn:hover {
  background: var(--color-accent-primary-hover);
  transform: translateY(-1px);
  box-shadow: var(--glow-primary);
}

.action-btn:active {
  transform: translateY(0);
}
</style>

// ccr-ui/src/ui/empty-state.tsx
import type { ReactNode } from 'react'
import { cn } from './cn'
import { SIcon } from './s-icon'

interface EmptyStateProps {
  icon?: string
  title: string
  description?: string
  actionText?: string
  actionIcon?: string
  onAction?: () => void
  children?: ReactNode
  className?: string
}

export function EmptyState({
  icon = 'FileX',
  title,
  description,
  actionText,
  actionIcon,
  onAction,
  children,
  className,
}: EmptyStateProps) {
  return (
    <div
      className={cn(
        'empty-state flex min-h-[300px] flex-col items-center justify-center p-12 text-center',
        className,
      )}
      role="status"
      aria-live="polite"
    >
      <div
        className="empty-state__icon mb-4 flex h-20 w-20 items-center justify-center rounded-full text-text-muted"
        aria-hidden="true"
      >
        <SIcon name={icon} />
      </div>
      <h3 className="mb-2 text-xl font-semibold text-text-primary">{title}</h3>
      {description ? (
        <p className="mb-4 max-w-[480px] text-base text-text-secondary">{description}</p>
      ) : null}
      {actionText && onAction ? (
        <button
          type="button"
          className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-accent-primary/15 bg-accent-primary px-5 py-2.5 text-base font-medium text-text-inverted transition-[background-color,transform] duration-200 ease-out hover:-translate-y-px hover:bg-accent-primary-hover active:translate-y-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-primary/30"
          onClick={onAction}
        >
          {actionIcon ? <SIcon name={actionIcon} size="w-[18px] h-[18px]" /> : null}
          {actionText}
        </button>
      ) : null}
      {children}
    </div>
  )
}
