// ccr-ui/frontend/src/components/ui/EmptyState.vue
<template>
  <div
    class="flex flex-col items-center justify-center p-12 text-center min-h-[300px] glass-effect"
    role="status"
    aria-live="polite"
  >
    <div
      class="flex items-center justify-center w-20 h-20 mb-4 rounded-full bg-bg-surface text-text-muted"
      aria-hidden="true"
    >
      <component
        :is="icon"
        :size="48"
        :stroke-width="1.5"
      />
    </div>
    <h3 class="text-xl font-semibold text-text-primary mb-2">
      {{ title }}
    </h3>
    <p
      v-if="description"
      class="text-base text-text-secondary max-w-[480px] mb-4"
    >
      {{ description }}
    </p>
    <button
      v-if="actionText && onAction"
      class="inline-flex items-center justify-center gap-2 px-4 py-2 text-base font-medium text-white bg-accent-primary border-none rounded-md cursor-pointer transition-[background-color,transform,box-shadow] duration-200 ease-out hover:bg-accent-primary-hover hover:-translate-y-px hover:shadow-glow-primary active:translate-y-0 min-h-[44px]"
      @click="onAction"
    >
      <component
        :is="actionIcon"
        v-if="actionIcon"
        class="w-[18px] h-[18px]"
        aria-hidden="true"
      />
      {{ actionText }}
    </button>
  </div>
</template>

<script setup lang="ts">
import type { Component } from 'vue'
import { FileX } from 'lucide-vue-next'

interface Props {
  icon?: Component
  title: string
  description?: string
  actionText?: string
  actionIcon?: Component
  onAction?: () => void
}

withDefaults(defineProps<Props>(), {
  icon: () => FileX,
})
</script>

// ccr-ui/src/ui/empty-state.tsx
import type { ReactNode } from 'react'
import { cn } from './cn'
import { SIcon } from './s-icon'

interface EmptyStateProps {
  icon?: string
  title: string
  description?: string
  actionText?: string
  actionIcon?: string
  onAction?: () => void
  children?: ReactNode
  className?: string
}

export function EmptyState({
  icon = 'FileX',
  title,
  description,
  actionText,
  actionIcon,
  onAction,
  children,
  className,
}: EmptyStateProps) {
  return (
    <div
      className={cn(
        'empty-state flex min-h-[300px] flex-col items-center justify-center p-12 text-center',
        className,
      )}
      role="status"
      aria-live="polite"
    >
      <div
        className="empty-state__icon mb-4 flex h-20 w-20 items-center justify-center rounded-full text-text-muted"
        aria-hidden="true"
      >
        <SIcon name={icon} />
      </div>
      <h3 className="mb-2 text-xl font-semibold text-text-primary">{title}</h3>
      {description ? (
        <p className="mb-4 max-w-[480px] text-base text-text-secondary">{description}</p>
      ) : null}
      {actionText && onAction ? (
        <button
          type="button"
          className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-accent-primary/15 bg-accent-primary px-5 py-2.5 text-base font-medium text-text-inverted transition-[background-color,transform] duration-200 ease-out hover:-translate-y-px hover:bg-accent-primary-hover active:translate-y-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-primary/30"
          onClick={onAction}
        >
          {actionIcon ? <SIcon name={actionIcon} size="w-[18px] h-[18px]" /> : null}
          {actionText}
        </button>
      ) : null}
      {children}
    </div>
  )
}
