// ccr-ui/src/features/checkin/tabs/CheckinRecordsTab.tsx
import { memo, useCallback, useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { listCheckinRecords, exportCheckinRecords } from '@/api'
import { getErrorMessage } from '@/types/api'
import type {
  AccountInfo,
  CheckinProvider,
  CheckinRecordInfo,
  CheckinRecordsQuery,
  CheckinRecordsResponse,
  TodayCheckinStats,
} from '@/types/checkin'
import { logger } from '@/utils/logger'
import { SIcon } from '@/ui'
import { getSkipReasonText, getStatusText } from '../lib/checkinFormat'
import { checkinNotify } from '../lib/checkinNotify'
import { useCheckinLocale, useCheckinT } from '../hooks/useCheckinT'
import '../styles/records.css'

interface CheckinRecordsTabProps {
  records: CheckinRecordInfo[]
  recordsLoadError: string | null
  providers: CheckinProvider[]
  accounts: AccountInfo[]
  todayStats: TodayCheckinStats | null
  onUpdateCookie?: (accountId: string) => void
}

interface HistoryFilters {
  provider: string
  keyword: string
}

const FailedHistoryItem = memo(function FailedHistoryItem({
  accountName,
  accountId,
  showFix,
  fixLabel,
  onFix,
}: {
  accountName: string
  accountId: string
  showFix: boolean
  fixLabel: string
  onFix: (accountId: string) => void
}) {
  const handleFix = useCallback(() => onFix(accountId), [accountId, onFix])
  return (
    <div className="checkin-records__history-item">
      <div>{accountName}</div>
      {showFix ? (
        <button type="button" className="checkin-records__history-button checkin-records__fix-button" onClick={handleFix}>
          {fixLabel}
        </button>
      ) : null}
    </div>
  )
})

const statusClass = (status: string) => {
  if (status === 'success') return 'checkin-records__status-badge--success'
  if (status === 'already_checked_in') return 'checkin-records__status-badge--warning'
  if (status === 'failed') return 'checkin-records__status-badge--danger'
  return 'checkin-records__status-badge--neutral'
}

const RecordRow = memo(function RecordRow({
  record,
  accountName,
  reason,
  statusLabel,
  formattedDate,
  detailsLabel,
  expanded,
  showFix,
  fixLabel,
  onToggle,
  onFix,
}: {
  record: CheckinRecordInfo
  accountName: string
  reason: string
  statusLabel: string
  formattedDate: string
  detailsLabel: string
  expanded: boolean
  showFix: boolean
  fixLabel: string
  onToggle: (id: string) => void
  onFix: (accountId: string) => void
}) {
  const handleToggle = useCallback(() => onToggle(record.id), [onToggle, record.id])
  const handleFix = useCallback(() => onFix(record.account_id), [onFix, record.account_id])
  return (
    <>
      <tr className="checkin-records__table-row">
        <td className="checkin-records__table-cell checkin-records__table-cell--muted">{formattedDate}</td>
        <td className="checkin-records__table-cell checkin-records__table-cell--primary">{accountName}</td>
        <td className="checkin-records__table-cell">
          <span className={`checkin-records__status-badge checkin-badge-pill ${statusClass(record.status)}`}>
            {statusLabel}
          </span>
        </td>
        <td className="checkin-records__table-cell checkin-records__table-cell--success">
          {record.reward || '-'}
        </td>
        <td className="checkin-records__table-cell checkin-records__table-cell--muted">
          {record.balance_after !== undefined && record.balance_after !== null
            ? `$${record.balance_after.toFixed(2)}`
            : '-'}
        </td>
        <td className="checkin-records__table-cell checkin-records__table-cell--muted">{reason}</td>
        <td className="checkin-records__table-cell checkin-records__table-cell--right">
          <div className="checkin-records__row-actions">
            {showFix ? (
              <button type="button" className="checkin-records__detail-toggle checkin-records__fix-button" onClick={handleFix}>
                {fixLabel}
              </button>
            ) : null}
            <button type="button" className="checkin-records__detail-toggle" onClick={handleToggle}>
              {detailsLabel}
            </button>
          </div>
        </td>
      </tr>
      {expanded ? (
        <tr>
          <td colSpan={7} className="checkin-records__table-cell">
            {record.message || '-'}
          </td>
        </tr>
      ) : null}
    </>
  )
})

export function CheckinRecordsTab({
  records,
  recordsLoadError,
  providers,
  accounts,
  onUpdateCookie,
}: CheckinRecordsTabProps) {
  const t = useCheckinT()
  const locale = useCheckinLocale()
  const [expandedIds, setExpandedIds] = useState<string[]>([])
  const [failedRecords, setFailedRecords] = useState<CheckinRecordInfo[]>([])
  const [failedTotal, setFailedTotal] = useState(0)
  const [failedLoading, setFailedLoading] = useState(false)
  const [failedPage, setFailedPage] = useState(1)
  const filters = useForm<HistoryFilters>({ defaultValues: { provider: 'all', keyword: '' } })
  const getFilters = filters.getValues

  const getAccountName = useCallback(
    (accountId: string) => accounts.find((account) => account.id === accountId)?.name || accountId,
    [accounts],
  )

  const getRecordReason = useCallback(
    (record: CheckinRecordInfo) => {
      if (record.message) return record.message
      if (record.status === 'skipped') {
        return getSkipReasonText(record.error_code, t) || t('checkin.detail.skipped')
      }
      if (record.status === 'success') return t('checkin.detail.checkinSuccess')
      if (record.status === 'already_checked_in') return t('checkin.detail.todayAlreadyCheckedIn')
      if (record.status === 'failed') return t('checkin.errors.unknownReason')
      return '-'
    },
    [t],
  )

  const loadFailedHistory = useCallback(async (page: number) => {
    setFailedLoading(true)
    try {
      const { provider, keyword } = getFilters()
      const params: CheckinRecordsQuery = { status: 'failed', page, page_size: 5 }
      if (provider !== 'all') params.provider_id = provider
      if (keyword.trim()) params.keyword = keyword.trim()
      const response = await listCheckinRecords<CheckinRecordsResponse>(params)
      setFailedRecords(response.records)
      setFailedTotal(response.total)
    } catch (error: unknown) {
      logger.error('Failed to load failed history:', error)
    } finally {
      setFailedLoading(false)
    }
  }, [getFilters])

  useEffect(() => {
    void loadFailedHistory(1)
  }, [loadFailedHistory])

  const applyFilters = useCallback(() => {
    setFailedPage(1)
    void loadFailedHistory(1)
  }, [loadFailedHistory])

  const resetFilters = useCallback(() => {
    filters.reset({ provider: 'all', keyword: '' })
    setFailedPage(1)
    void loadFailedHistory(1)
  }, [filters, loadFailedHistory])

  const toggleExpanded = useCallback((id: string) => {
    setExpandedIds((current) => (current.includes(id) ? current.filter((item) => item !== id) : [...current, id]))
  }, [])

  const handleFix = useCallback(
    (accountId: string) => {
      onUpdateCookie?.(accountId)
    },
    [onUpdateCookie],
  )

  const exportFailed = useCallback(async () => {
    try {
      const { provider, keyword } = getFilters()
      const params: CheckinRecordsQuery = { status: 'failed' }
      if (provider !== 'all') params.provider_id = provider
      if (keyword.trim()) params.keyword = keyword.trim()
      const { blob, filename } = await exportCheckinRecords<{ blob: Blob; filename: string }>(params)
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = filename
      document.body.appendChild(link)
      link.click()
      link.remove()
      URL.revokeObjectURL(url)
    } catch (error: unknown) {
      checkinNotify.error(
        t('checkin.records.exportFailed', { error: getErrorMessage(error, t('checkin.errors.unknown')) }),
      )
    }
  }, [getFilters, t])

  const failedHistoryTotalPages = useMemo(() => Math.max(1, Math.ceil(failedTotal / 5)), [failedTotal])

  if (recordsLoadError) {
    return (
      <div className="checkin-records">
        <h2 className="checkin-records__title">{t('checkin.records.title')}</h2>
        <div className="checkin-records__error">
          <SIcon name="AlertCircle" size="w-4 h-4" />
          <span>{recordsLoadError}</span>
        </div>
      </div>
    )
  }

  if (records.length === 0) {
    return (
      <div className="checkin-records">
        <h2 className="checkin-records__title">{t('checkin.records.title')}</h2>
        <div className="checkin-records__empty">{t('checkin.records.empty')}</div>
      </div>
    )
  }

  return (
    <div className="checkin-records">
      <h2 className="checkin-records__title">{t('checkin.records.title')}</h2>
      <details className="checkin-records__history">
        <summary className="checkin-records__history-summary">
          {t('checkin.records.failedHistoryTitle', { count: failedTotal })}
        </summary>
        <div className="checkin-records__history-body">
          <div className="checkin-records__history-filters">
            <select className="checkin-records__history-input" {...filters.register('provider')}>
              <option value="all">{t('checkin.records.allProviders')}</option>
              {providers.map((provider) => (
                <option key={provider.id} value={provider.id}>
                  {provider.name}
                </option>
              ))}
            </select>
            <input
              className="checkin-records__history-input"
              placeholder={t('checkin.records.keywordPlaceholder')}
              {...filters.register('keyword')}
            />
            <button type="button" className="checkin-records__history-button" disabled={failedLoading} onClick={applyFilters}>
              {t('checkin.records.filter')}
            </button>
            <button type="button" className="checkin-records__history-button" disabled={failedLoading} onClick={resetFilters}>
              {t('checkin.records.reset')}
            </button>
            <button type="button" className="checkin-records__history-button" disabled={failedLoading} onClick={exportFailed}>
              {t('checkin.records.export')}
            </button>
          </div>
          {failedRecords.map((record) => (
            <FailedHistoryItem
              key={record.id}
              accountName={getAccountName(record.account_id)}
              accountId={record.account_id}
              showFix={record.error_code === 'cookie_expired'}
              fixLabel={t('checkin.records.cookieExpiredFix')}
              onFix={handleFix}
            />
          ))}
        </div>
      </details>
      <div className="checkin-records__table-shell">
        <table className="checkin-records__table">
          <thead>
            <tr>
              <th className="checkin-records__table-heading">{t('checkin.records.time')}</th>
              <th className="checkin-records__table-heading">{t('checkin.records.account')}</th>
              <th className="checkin-records__table-heading">{t('checkin.records.status')}</th>
              <th className="checkin-records__table-heading">{t('checkin.records.reward')}</th>
              <th className="checkin-records__table-heading">{t('checkin.records.balance')}</th>
              <th className="checkin-records__table-heading">{t('checkin.records.reason')}</th>
              <th className="checkin-records__table-heading checkin-records__table-heading--right">
                {t('checkin.records.details')}
              </th>
            </tr>
          </thead>
          <tbody>
            {records.map((record) => (
              <RecordRow
                key={record.id}
                record={record}
                accountName={getAccountName(record.account_id)}
                reason={getRecordReason(record)}
                statusLabel={getStatusText(record.status, t)}
                formattedDate={new Date(record.checked_in_at).toLocaleString(locale)}
                detailsLabel={t('checkin.records.details')}
                expanded={expandedIds.includes(record.id)}
                showFix={record.error_code === 'cookie_expired'}
                fixLabel={t('checkin.records.cookieExpiredFix')}
                onToggle={toggleExpanded}
                onFix={handleFix}
              />
            ))}
          </tbody>
        </table>
      </div>
      <span>{t('checkin.records.pageLabel', { page: failedPage, total: failedHistoryTotalPages })}</span>
    </div>
  )
}

// ccr-ui/src/views/checkin/tabs/CheckinRecordsTab.vue
<template>
  <div class="checkin-records">
    <h2 class="checkin-records__title">
      {{ t('checkin.records.title') }}
    </h2>
    <div
      v-if="recordsLoadError"
      class="checkin-records__error"
    >
      <SIcon
        name="AlertCircle"
        size="w-4 h-4"
      />
      <span>{{ recordsLoadError }}</span>
    </div>
    <div
      v-else-if="records.length === 0"
      class="checkin-records__empty"
    >
      {{ t('checkin.records.empty') }}
    </div>
    <div
      v-else
      class="checkin-records__content"
    >
      <details class="checkin-records__history">
        <summary class="checkin-records__history-summary">
          <div class="checkin-records__history-summary-label">
            <SIcon
              name="XCircle"
              size="w-4 h-4"
            />
            {{ t('checkin.records.failedHistoryTitle', { count: failedHistoryTotal }) }}
          </div>
          <span class="checkin-records__history-summary-hint">
            {{ t('checkin.records.failedHistoryHint') }}
          </span>
        </summary>
        <div class="checkin-records__history-body">
          <div class="checkin-records__history-filters">
            <select
              v-model="failedHistoryProviderFilter"
              class="checkin-records__history-input"
            >
              <option value="all">
                {{ t('checkin.records.allProviders') }}
              </option>
              <option
                v-for="provider in providers"
                :key="provider.id"
                :value="provider.id"
              >
                {{ provider.name }}
              </option>
            </select>
            <input
              v-model="failedHistoryKeyword"
              type="text"
              :placeholder="t('checkin.records.keywordPlaceholder')"
              class="checkin-records__history-input"
            >
            <button
              class="checkin-records__history-button"
              :disabled="failedHistoryLoading"
              @click="applyFailedHistoryFilters"
            >
              {{ t('checkin.records.filter') }}
            </button>
            <button
              class="checkin-records__history-button"
              :disabled="failedHistoryLoading"
              @click="resetFailedHistoryFilters"
            >
              {{ t('checkin.records.reset') }}
            </button>
            <button
              class="checkin-records__history-button"
              :disabled="failedHistoryLoading"
              @click="exportFailedHistory"
            >
              {{ t('checkin.records.export') }}
            </button>
          </div>
          <div
            v-if="failedHistoryLoading"
            class="checkin-records__history-state"
          >
            {{ t('checkin.records.loading') }}
          </div>
          <div
            v-else-if="failedHistoryTotal === 0"
            class="checkin-records__history-state"
          >
            {{ t('checkin.records.emptyFailed') }}
          </div>
          <div
            v-else
            class="checkin-records__history-list"
          >
            <div
              v-for="record in failedHistoryRecords"
              :key="record.id"
              class="checkin-records__history-item"
            >
              <div class="checkin-records__history-item-head">
                <div class="checkin-records__history-item-name">
                  {{ getAccountName(record.account_id) }}
                </div>
                <div class="checkin-records__history-item-time">
                  {{ formatDate(record.checked_in_at) }}
                </div>
              </div>
              <div class="checkin-records__history-item-meta">
                {{ t('checkin.records.providerLabel', { name: getRecordProviderName(record) }) }}
                {{ t('checkin.records.accountIdLabel', { id: record.account_id }) }}
              </div>
              <div class="checkin-records__history-item-reason">
                {{ t('checkin.records.reasonLabel', { reason: getRecordReason(record) }) }}
              </div>
              <button
                v-if="record.error_code === 'cookie_expired'"
                type="button"
                class="checkin-records__history-button checkin-records__fix-button"
                @click="emit('update-cookie', record.account_id)"
              >
                {{ t('checkin.records.cookieExpiredFix') }}
              </button>
            </div>
            <div class="checkin-records__history-pagination">
              <span>
                {{ t('checkin.records.pageLabel', { page: failedHistoryPage, total: failedHistoryTotalPages }) }}
              </span>
              <div class="checkin-records__history-pagination-actions">
                <button
                  class="checkin-records__history-button"
                  :disabled="failedHistoryPage === 1"
                  @click="goToFailedHistoryPage(failedHistoryPage - 1)"
                >
                  {{ t('checkin.records.previousPage') }}
                </button>
                <button
                  class="checkin-records__history-button"
                  :disabled="failedHistoryPage === failedHistoryTotalPages"
                  @click="goToFailedHistoryPage(failedHistoryPage + 1)"
                >
                  {{ t('checkin.records.nextPage') }}
                </button>
              </div>
            </div>
          </div>
        </div>
      </details>

      <div class="checkin-records__table-shell">
        <table class="checkin-records__table">
          <thead class="checkin-records__table-head">
            <tr>
              <th class="checkin-records__table-heading">
                {{ t('checkin.records.time') }}
              </th>
              <th class="checkin-records__table-heading">
                {{ t('checkin.records.account') }}
              </th>
              <th class="checkin-records__table-heading">
                {{ t('checkin.records.status') }}
              </th>
              <th class="checkin-records__table-heading">
                {{ t('checkin.records.reward') }}
              </th>
              <th class="checkin-records__table-heading">
                {{ t('checkin.records.balance') }}
              </th>
              <th class="checkin-records__table-heading">
                {{ t('checkin.records.reason') }}
              </th>
              <th class="checkin-records__table-heading checkin-records__table-heading--right">
                {{ t('checkin.records.details') }}
              </th>
            </tr>
          </thead>
          <tbody class="checkin-records__table-body">
            <template
              v-for="record in records"
              :key="record.id"
            >
              <tr class="checkin-records__table-row">
                <td class="checkin-records__table-cell checkin-records__table-cell--muted checkin-records__table-cell--nowrap">
                  {{ formatDate(record.checked_in_at) }}
                </td>
                <td class="checkin-records__table-cell checkin-records__table-cell--primary checkin-records__table-cell--nowrap">
                  {{ getAccountName(record.account_id) }}
                </td>
                <td class="checkin-records__table-cell checkin-records__table-cell--nowrap">
                  <span
                    class="checkin-records__status-badge checkin-badge-pill"
                    :class="getStatusClass(record.status)"
                  >
                    {{ getStatusText(record.status) }}
                  </span>
                </td>
                <td class="checkin-records__table-cell checkin-records__table-cell--success checkin-records__table-cell--nowrap">
                  {{ record.reward || '-' }}
                </td>
                <td class="checkin-records__table-cell checkin-records__table-cell--muted checkin-records__table-cell--nowrap">
                  {{ record.balance_after !== undefined && record.balance_after !== null ? `$${record.balance_after.toFixed(2)}` : '-' }}
                </td>
                <td class="checkin-records__table-cell checkin-records__table-cell--muted checkin-records__table-cell--truncate">
                  {{ getRecordReason(record) }}
                </td>
                <td class="checkin-records__table-cell checkin-records__table-cell--right">
                  <div class="checkin-records__row-actions">
                    <button
                      v-if="record.error_code === 'cookie_expired'"
                      type="button"
                      class="checkin-records__detail-toggle checkin-records__fix-button"
                      @click="emit('update-cookie', record.account_id)"
                    >
                      {{ t('checkin.records.cookieExpiredFix') }}
                    </button>
                    <button
                      class="checkin-records__detail-toggle"
                      :aria-expanded="isRecordExpanded(record.id)"
                      @click="toggleRecordExpanded(record.id)"
                    >
                      <SIcon
                        v-if="isRecordExpanded(record.id)"
                        name="ChevronUp"
                        size="w-4 h-4"
                      />
                      <SIcon
                        v-else
                        name="ChevronDown"
                        size="w-4 h-4"
                      />
                      {{ t('checkin.records.details') }}
                    </button>
                  </div>
                </td>
              </tr>
              <tr
                v-if="isRecordExpanded(record.id)"
                class="checkin-records__detail-row"
              >
                <td
                  colspan="7"
                  class="checkin-records__detail-cell"
                >
                  <div class="checkin-records__detail-grid">
                    <div class="checkin-records__detail-item">
                      <div class="checkin-records__detail-label">
                        {{ t('checkin.records.provider') }}
                      </div>
                      <div class="checkin-records__detail-value">
                        {{ getRecordProviderName(record) }}
                      </div>
                    </div>
                    <div class="checkin-records__detail-item">
                      <div class="checkin-records__detail-label">
                        {{ t('checkin.records.accountId') }}
                      </div>
                      <div class="checkin-records__detail-value checkin-records__detail-value--break">
                        {{ record.account_id }}
                      </div>
                    </div>
                    <div class="checkin-records__detail-item">
                      <div class="checkin-records__detail-label">
                        {{ t('checkin.records.reason') }}
                      </div>
                      <div class="checkin-records__detail-value checkin-records__detail-value--break">
                        {{ getRecordReason(record) }}
                      </div>
                    </div>
                    <div class="checkin-records__detail-item">
                      <div class="checkin-records__detail-label">
                        {{ t('checkin.records.rawMessage') }}
                      </div>
                      <div class="checkin-records__detail-value checkin-records__detail-value--break">
                        {{ getRecordRawMessage(record) }}
                      </div>
                    </div>
                    <div class="checkin-records__detail-item">
                      <div class="checkin-records__detail-label">
                        {{ t('checkin.records.rewardAndBalance') }}
                      </div>
                      <div class="checkin-records__detail-value">
                        {{ record.reward || '-' }} ·
                        {{ record.balance_change !== undefined && record.balance_change !== null ? `$${record.balance_change.toFixed(2)}` : '-' }}
                      </div>
                    </div>
                    <div class="checkin-records__detail-item">
                      <div class="checkin-records__detail-label">
                        {{ t('checkin.records.balanceBeforeAfter') }}
                      </div>
                      <div class="checkin-records__detail-value">
                        {{ record.balance_before !== undefined && record.balance_before !== null ? `$${record.balance_before.toFixed(2)}` : '-' }}
                        {{ t('checkin.records.balanceSeparator') }}
                        {{ record.balance_after !== undefined && record.balance_after !== null ? `$${record.balance_after.toFixed(2)}` : '-' }}
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            </template>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { ref, computed, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useUIStore } from '@/stores/ui'
import {
  listCheckinRecords,
  exportCheckinRecords,
} from '@/api'
import type {
  CheckinRecordInfo,
  CheckinProvider,
  AccountInfo,
  TodayCheckinStats,
  CheckinRecordsQuery,
  CheckinRecordsResponse,
} from '@/types/checkin'
import { logger } from '@/utils/logger'
import { getErrorMessage } from '@/types/api'

interface CheckinRecordsExportResponse {
  blob: Blob
  filename: string
}

const props = defineProps<{
  records: CheckinRecordInfo[]
  recordsLoadError: string | null
  providers: CheckinProvider[]
  accounts: AccountInfo[]
  todayStats: TodayCheckinStats | null
}>()

const emit = defineEmits<{
  /** cookie_expired 快捷修复：请求打开对应账号的编辑弹窗 */
  (e: 'update-cookie', accountId: string): void
}>()

const { t, locale } = useI18n()
const uiStore = useUIStore()

// 记录展开状态
const expandedRecordIds = ref<string[]>([])

// 失败历史记录相关
const failedHistoryRecords = ref<CheckinRecordInfo[]>([])
const failedHistoryTotal = ref(0)
const failedHistoryLoading = ref(false)
const failedHistoryPage = ref(1)
const failedHistoryPageSize = ref(5)
const failedHistoryProviderFilter = ref<string>('all')
const failedHistoryKeyword = ref('')

const failedHistoryTotalPages = computed(() => {
  const total = Math.ceil(failedHistoryTotal.value / failedHistoryPageSize.value)
  return total > 0 ? total : 1
})

// 辅助函数
const getProviderName = (providerId: string) => {
  return props.providers.find(p => p.id === providerId)?.name || providerId
}

const getAccountName = (accountId: string) => {
  return props.accounts.find(a => a.id === accountId)?.name || accountId
}

const formatDate = (dateStr: string) => {
  return new Date(dateStr).toLocaleString(locale.value)
}

const getStatusClass = (status: string) => {
  switch (status) {
    case 'success':
      return 'checkin-records__status-badge--success'
    case 'already_checked_in':
      return 'checkin-records__status-badge--warning'
    case 'failed':
      return 'checkin-records__status-badge--danger'
    case 'skipped':
      return 'checkin-records__status-badge--neutral'
    default:
      return 'checkin-records__status-badge--neutral'
  }
}

const getStatusText = (status: string) => {
  switch (status) {
    case 'success':
      return t('checkin.status.success')
    case 'already_checked_in':
      return t('checkin.status.already_checked_in')
    case 'failed':
      return t('checkin.status.failed')
    case 'skipped':
      return t('checkin.status.skipped')
    default:
      return status
  }
}

const getRecordProviderName = (record: CheckinRecordInfo) => {
  if (record.provider_name) return record.provider_name
  const account = props.accounts.find(a => a.id === record.account_id)
  return account?.provider_id ? getProviderName(account.provider_id) : '-'
}

// skipped 记录的 skip_reason 经由 error_code 列持久化（4 态契约）
const skipReasonText: Record<string, string> = {
  account_disabled: t('checkin.skipReasons.account_disabled'),
  provider_disabled: t('checkin.skipReasons.provider_disabled'),
  provider_unsupported: t('checkin.skipReasons.provider_unsupported'),
}

const getRecordReason = (record: CheckinRecordInfo) => {
  if (record.message) return record.message
  switch (record.status) {
    case 'success':
      return record.reward
        ? `${t('checkin.detail.checkinSuccess')} · ${t('checkin.detail.reward', { reward: record.reward })}`
        : t('checkin.detail.checkinSuccess')
    case 'already_checked_in':
      return t('checkin.detail.todayAlreadyCheckedIn')
    case 'failed':
      return t('checkin.errors.unknownReason')
    case 'skipped':
      return (record.error_code && skipReasonText[record.error_code]) || t('checkin.detail.skipped')
    default:
      return '-'
  }
}

const getRecordRawMessage = (record: CheckinRecordInfo) => record.message || '-'

const isRecordExpanded = (recordId: string) => {
  return expandedRecordIds.value.includes(recordId)
}

const toggleRecordExpanded = (recordId: string) => {
  expandedRecordIds.value = expandedRecordIds.value.includes(recordId)
    ? expandedRecordIds.value.filter(id => id !== recordId)
    : [...expandedRecordIds.value, recordId]
}

// 失败历史记录加载
const loadFailedHistory = async () => {
  failedHistoryLoading.value = true
  try {
    const params: CheckinRecordsQuery = {
      status: 'failed',
      page: failedHistoryPage.value,
      page_size: failedHistoryPageSize.value,
    }
    if (failedHistoryProviderFilter.value !== 'all') {
      params.provider_id = failedHistoryProviderFilter.value
    }
    if (failedHistoryKeyword.value.trim()) {
      params.keyword = failedHistoryKeyword.value.trim()
    }
    const response = await listCheckinRecords<CheckinRecordsResponse>(params)
    failedHistoryRecords.value = response.records
    failedHistoryTotal.value = response.total
  } catch (e: unknown) {
    logger.error('Failed to load failed history:', e)
  } finally {
    failedHistoryLoading.value = false
  }
}

const applyFailedHistoryFilters = async () => {
  failedHistoryPage.value = 1
  await loadFailedHistory()
}

const resetFailedHistoryFilters = async () => {
  failedHistoryProviderFilter.value = 'all'
  failedHistoryKeyword.value = ''
  failedHistoryPage.value = 1
  await loadFailedHistory()
}

const goToFailedHistoryPage = async (page: number) => {
  const nextPage = Math.min(Math.max(page, 1), failedHistoryTotalPages.value)
  if (nextPage === failedHistoryPage.value) return
  failedHistoryPage.value = nextPage
  await loadFailedHistory()
}

const exportFailedHistory = async () => {
  try {
    const params: CheckinRecordsQuery = { status: 'failed' }
    if (failedHistoryProviderFilter.value !== 'all') {
      params.provider_id = failedHistoryProviderFilter.value
    }
    if (failedHistoryKeyword.value.trim()) {
      params.keyword = failedHistoryKeyword.value.trim()
    }
    const { blob, filename } = await exportCheckinRecords<CheckinRecordsExportResponse>(params)
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    link.remove()
    URL.revokeObjectURL(url)
  } catch (e: unknown) {
    uiStore.showError(t('checkin.records.exportFailed', {
      error: getErrorMessage(e, t('checkin.errors.unknown')),
    }))
  }
}

// 监听失败历史总数，修正页码
watch(
  () => failedHistoryTotal.value,
  () => {
    if (failedHistoryPage.value > failedHistoryTotalPages.value) {
      failedHistoryPage.value = failedHistoryTotalPages.value
    }
  }
)

onMounted(() => {
  loadFailedHistory()
})
</script>

<style scoped>
.checkin-records,
.checkin-records__content,
.checkin-records__history-list {
  display: flex;
  flex-direction: column;
}

.checkin-records {
  gap: 1rem;
}

.checkin-records__title {
  font-size: 1.25rem;
  line-height: 1.75rem;
  font-weight: 600;
  color: var(--text-primary);
}

.checkin-records__empty {
  padding: 3rem 0;
  text-align: center;
  color: var(--text-muted);
}

.checkin-records__error {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.875rem 1rem;
  border: 1px solid rgb(var(--color-warning-rgb) / 30%);
  border-radius: 0.5rem;
  background: rgb(var(--color-warning-rgb) / 10%);
  color: var(--color-warning);
}

.checkin-records__content {
  gap: 1rem;
}

.checkin-records__history {
  overflow: hidden;
  border: 1px solid rgb(var(--color-danger-rgb) / 30%);
  border-radius: 0.5rem;
  background: rgb(var(--color-danger-rgb) / 8%);
}

.checkin-records__history-summary,
.checkin-records__history-summary-label,
.checkin-records__history-filters,
.checkin-records__history-item-head,
.checkin-records__history-pagination,
.checkin-records__history-pagination-actions,
.checkin-records__detail-toggle {
  display: flex;
  align-items: center;
}

.checkin-records__history-summary {
  justify-content: space-between;
  cursor: pointer;
  user-select: none;
  padding: 0.75rem 1rem;
  font-size: 0.875rem;
  line-height: 1.25rem;
  font-weight: 500;
  color: var(--color-danger);
}

.checkin-records__history-summary-label {
  gap: 0.5rem;
}

.checkin-records__history-summary-hint,
.checkin-records__history-item-time,
.checkin-records__history-item-meta,
.checkin-records__history-item-reason,
.checkin-records__history-pagination,
.checkin-records__history-state,
.checkin-records__history-input,
.checkin-records__history-button {
  font-size: 0.75rem;
  line-height: 1rem;
  color: rgb(var(--color-danger-rgb) / 82%);
}

.checkin-records__history-body {
  padding: 0.5rem 1rem 1rem;
}

.checkin-records__history-filters {
  flex-wrap: wrap;
  gap: 0.5rem;
  padding-bottom: 0.75rem;
}

.checkin-records__history-input,
.checkin-records__history-button {
  border: 1px solid rgb(var(--color-danger-rgb) / 30%);
  border-radius: 0.375rem;
  background: rgb(var(--color-bg-surface-rgb) / 80%);
  padding: 0.25rem 0.5rem;
}

.checkin-records__history-button {
  transition: background-color 0.2s ease, opacity 0.2s ease;
}

.checkin-records__history-button:hover:not(:disabled) {
  background: rgb(var(--color-danger-rgb) / 14%);
}

.checkin-records__history-button:disabled {
  opacity: 0.5;
}

.checkin-records__history-list {
  gap: 0.5rem;
}

.checkin-records__history-item {
  border: 1px solid rgb(var(--color-danger-rgb) / 30%);
  border-radius: 0.375rem;
  background: rgb(var(--color-bg-surface-rgb) / 70%);
  padding: 0.75rem;
}

.checkin-records__history-item-head,
.checkin-records__history-pagination {
  justify-content: space-between;
  gap: 1rem;
}

.checkin-records__history-item-head {
  flex-wrap: wrap;
}

.checkin-records__history-item-name {
  font-size: 0.875rem;
  line-height: 1.25rem;
  font-weight: 500;
  color: var(--color-danger);
}

.checkin-records__history-item-meta {
  margin-top: 0.25rem;
}

.checkin-records__history-item-reason {
  margin-top: 0.5rem;
  word-break: break-all;
}

.checkin-records__history-pagination {
  padding-top: 0.5rem;
}

.checkin-records__history-pagination-actions {
  gap: 0.5rem;
}

.checkin-records__table-shell {
  overflow: hidden;
  border-radius: 0.5rem;
  background: var(--color-bg-surface);
  box-shadow: var(--shadow-xs);
}

.checkin-records__table {
  min-width: 100%;
  border-collapse: separate;
  border-spacing: 0;
}

.checkin-records__table-head {
  background: var(--color-bg-elevated);
}

.checkin-records__table-heading,
.checkin-records__table-cell {
  padding: 0.75rem 1.5rem;
}

.checkin-records__table-heading {
  text-align: left;
  font-size: 0.75rem;
  line-height: 1rem;
  font-weight: 500;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: var(--text-muted);
}

.checkin-records__table-heading--right,
.checkin-records__table-cell--right {
  text-align: right;
}

.checkin-records__table-body > tr + tr > td {
  border-top: 1px solid var(--color-border-subtle);
}

.checkin-records__table-row {
  transition: background-color 0.2s ease;
}

.checkin-records__table-row:hover {
  background: rgb(var(--color-accent-primary-rgb) / 6%);
}

.checkin-records__table-cell {
  font-size: 0.875rem;
  line-height: 1.25rem;
}

.checkin-records__table-cell--muted {
  color: var(--text-muted);
}

.checkin-records__table-cell--primary {
  color: var(--text-primary);
}

.checkin-records__table-cell--success {
  color: var(--color-success);
}

.checkin-records__table-cell--nowrap {
  white-space: nowrap;
}

.checkin-records__table-cell--truncate {
  max-width: 20rem;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* 形状配方由全局 .checkin-badge-pill 提供，这里保留尺寸差异 */
.checkin-records__status-badge {
  padding: 0.25rem 0.5rem;
  line-height: 1rem;
  font-weight: 500;
}

.checkin-records__status-badge--success {
  background: rgb(var(--color-success-rgb) / 15%);
  color: var(--color-success);
}

.checkin-records__status-badge--warning {
  background: rgb(var(--color-warning-rgb) / 15%);
  color: var(--color-warning);
}

.checkin-records__status-badge--danger {
  background: rgb(var(--color-danger-rgb) / 15%);
  color: var(--color-danger);
}

.checkin-records__status-badge--neutral {
  background: var(--color-bg-overlay);
  color: var(--text-secondary);
}

.checkin-records__detail-toggle {
  gap: 0.25rem;
  font-size: 0.75rem;
  line-height: 1rem;
  color: var(--color-info);
  transition: color 0.2s ease;
}

.checkin-records__detail-toggle:hover {
  color: var(--color-info-hover);
}

.checkin-records__row-actions {
  display: inline-flex;
  align-items: center;
  gap: 0.75rem;
}

/* cookie_expired 快捷修复入口（直达账号编辑弹窗） */
.checkin-records__fix-button {
  color: var(--color-danger);
}

.checkin-records__fix-button:hover {
  color: var(--color-danger-hover);
}

.checkin-records__history-item .checkin-records__fix-button {
  margin-top: 0.5rem;
}

.checkin-records__detail-row {
  background: rgb(var(--color-bg-elevated-rgb) / 70%);
}

.checkin-records__detail-cell {
  padding: 1rem 1.5rem;
  font-size: 0.875rem;
  line-height: 1.25rem;
  color: var(--text-secondary);
}

.checkin-records__detail-grid {
  display: grid;
  gap: 0.75rem;
}

.checkin-records__detail-item {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.checkin-records__detail-label {
  font-size: 0.75rem;
  line-height: 1rem;
  color: var(--text-muted);
}

.checkin-records__detail-value {
  font-size: 0.875rem;
  line-height: 1.25rem;
}

.checkin-records__detail-value--break {
  word-break: break-all;
}

@media (width >= 768px) {
  .checkin-records__detail-grid {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
}

@media (width <= 767px) {
  .checkin-records__table-shell {
    overflow-x: auto;
  }

  .checkin-records__history-summary,
  .checkin-records__history-pagination {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
