// ccr-ui/src/components/codex/profiles/Sparkline.vue
<!-- 极简 SVG Sparkline：只服务统计条视觉点缀，不承担真实图表能力 -->
<template>
  <svg
    :width="width"
    :height="height"
    :viewBox="`0 0 ${width} ${height}`"
    aria-hidden="true"
    role="presentation"
  >
    <polyline
      :points="points"
      fill="none"
      :stroke="color"
      stroke-width="1.4"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
  </svg>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  values: number[]
  color?: string
  width?: number
  height?: number
}

const props = withDefaults(defineProps<Props>(), {
  color: 'currentColor',
  width: 60,
  height: 18,
})

const points = computed(() => {
  const vs = props.values
  if (!vs.length) return ''
  const max = Math.max(...vs, 1)
  const min = Math.min(...vs, 0)
  const range = max - min || 1
  const w = props.width
  const h = props.height
  const denom = vs.length === 1 ? 1 : vs.length - 1
  return vs
    .map((v, i) => {
      const x = (i / denom) * w
      const y = h - ((v - min) / range) * h
      return `${x.toFixed(1)},${y.toFixed(1)}`
    })
    .join(' ')
})
</script>

// ccr-ui/src/features/usage/Sparkline.tsx
import { useMemo } from 'react'

interface SparklineProps {
  values: number[]
  width?: number
  height?: number
  strokeWidth?: number
  fill?: string
  label?: string
  className?: string
}

/** SVG sparkline；配色走 currentColor / chart-colors token。 */
export function Sparkline({
  values,
  width = 120,
  height = 38,
  strokeWidth = 2.4,
  fill = 'currentColor',
  label,
  className,
}: SparklineProps) {
  const path = useMemo(() => {
    if (values.length === 0) return ''
    const max = Math.max(...values, 0)
    const min = Math.min(...values, 0)
    const span = Math.max(max - min, 1)
    const step = values.length > 1 ? width / (values.length - 1) : width

    return values
      .map((value, index) => {
        const x = index * step
        const y = height - ((value - min) / span) * height
        return `${index === 0 ? 'M' : 'L'}${x.toFixed(2)} ${y.toFixed(2)}`
      })
      .join(' ')
  }, [height, values, width])

  return (
    <svg
      className={className}
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      height="100%"
      role="img"
      aria-label={label}
      preserveAspectRatio="none"
    >
      <path
        d={path}
        fill="none"
        stroke={fill}
        strokeWidth={strokeWidth}
        strokeLinejoin="round"
        strokeLinecap="round"
      />
    </svg>
  )
}
