// ccr-ui/src/features/claude/observer/ChartPreparingState.tsx
import { t } from '@/features/claude/locale'

const BAR_HEIGHTS = [34, 58, 46, 76, 52, 68, 40, 60]

interface ChartPreparingStateProps {
  label?: string
}

/** 图表准备态：条形占位，不用 px / rgba 字面量。 */
export function ChartPreparingState({ label }: ChartPreparingStateProps) {
  const displayLabel = label ?? t('claudeCode.observer.chart.preparing')
  return (
    <div
      className="grid min-h-full w-full place-items-center gap-3 rounded-2xl border border-dashed border-border-default/25 bg-bg-surface text-sm text-text-muted"
      role="status"
    >
      <div className="flex h-13 items-end gap-1" aria-hidden="true">
        {BAR_HEIGHTS.map((height) => (
          <span
            key={height}
            className="min-h-3 w-1.5 rounded-full bg-accent-primary/30 motion-safe:animate-pulse"
            style={{ height: `${height}%` }}
          />
        ))}
      </div>
      <span className="font-semibold text-text-muted">{displayLabel}</span>
    </div>
  )
}

// ccr-ui/src/components/claude-observer/ChartPreparingState.vue
<template>
  <div class="chart-preparing-state">
    <div
      class="chart-preparing-state__bars"
      aria-hidden="true"
    >
      <span
        v-for="height in barHeights"
        :key="height"
        :style="{ height: `${height}%` }"
      />
    </div>
    <span class="chart-preparing-state__label">
      {{ displayLabel }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const props = withDefaults(defineProps<{
  label?: string
}>(), {
  label: undefined,
})

const { t } = useI18n()
const barHeights = [34, 58, 46, 76, 52, 68, 40, 60]
const displayLabel = computed(() => props.label ?? t('claudeCode.observer.chart.preparing'))
</script>

<style scoped>
.chart-preparing-state {
  display: grid;
  width: 100%;
  min-height: 100%;
  place-items: center;
  gap: 0.75rem;
  border-radius: 1rem;
  border: 1px dashed rgb(var(--color-border-default-rgb) / 24%);
  background: var(--color-bg-surface);
  color: var(--color-text-muted);
  font-size: 0.85rem;
}

.chart-preparing-state__bars {
  display: flex;
  align-items: end;
  gap: 0.28rem;
  height: 3.25rem;
}

.chart-preparing-state__bars span {
  width: 0.42rem;
  min-height: 0.7rem;
  border-radius: 9999px;
  background: rgb(var(--color-accent-primary-rgb) / 28%);
  animation: chart-preparing-pulse 1.1s ease-in-out infinite;
}

.chart-preparing-state__bars span:nth-child(2n) {
  background: rgb(var(--color-accent-secondary-rgb) / 28%);
  animation-delay: 90ms;
}

.chart-preparing-state__bars span:nth-child(3n) {
  background: rgb(var(--color-info-rgb) / 24%);
  animation-delay: 160ms;
}

.chart-preparing-state__label {
  color: var(--color-text-muted);
  font-weight: 600;
}

@keyframes chart-preparing-pulse {
  0%,
  100% {
    opacity: 0.45;
    transform: scaleY(0.72);
  }

  50% {
    opacity: 1;
    transform: scaleY(1);
  }
}

@media (prefers-reduced-motion: reduce) {
  .chart-preparing-state__bars span {
    animation: none;
  }
}
</style>
