// ccr-ui/src/components/opencode/OpenCodePageShell.vue
<template>
  <PageShell>
    <template #header>
      <div
        class="opencode-page-shell__header"
        :data-tone="tone"
      >
        <RouterLink
          :to="backTo"
          class="opencode-page-shell__back"
        >
          <Button
            variant="ghost"
            surface="status"
            density="compact"
            motion="subtle"
          >
            <template #leading>
              <SIcon
                name="ChevronLeft"
                size="w-4 h-4"
              />
            </template>
            {{ backLabel }}
          </Button>
        </RouterLink>

        <PageHeader
          :title="title"
          :description="description"
          eyebrow="OpenCode operator surface"
          eyebrow-lang="en"
        >
          <template #leading>
            <div class="opencode-page-shell__icon">
              <SIcon
                :name="icon"
                size="w-5 h-5"
              />
            </div>
          </template>

          <template
            v-if="$slots.actions"
            #actions
          >
            <slot name="actions" />
          </template>

          <template
            v-if="badge || $slots.meta"
            #status
          >
            <Badge
              v-if="badge"
              size="sm"
              shape="square"
            >
              {{ badge }}
            </Badge>
            <slot name="meta" />
          </template>
        </PageHeader>
      </div>
    </template>

    <slot />
  </PageShell>
</template>

<script setup lang="ts">
import { RouterLink } from 'vue-router'
import Badge from '@/components/ui/Badge.vue'
import Button from '@/components/ui/Button.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import PageShell from '@/components/ui/PageShell.vue'
import SIcon from '@/components/ui/SIcon.vue'

withDefaults(defineProps<{
  title: string
  description: string
  icon?: string
  /** 保留调用方 tone 契约；不再用字面色粉刷图标。 */
  tone?: 'lime' | 'violet' | 'cyan' | 'amber' | 'emerald'
  backTo?: string
  backLabel?: string
  badge?: string
}>(), {
  icon: 'TerminalSquare',
  tone: 'lime',
  backTo: '/opencode',
  backLabel: 'OpenCode',
  badge: '',
})
</script>

<style scoped>
.opencode-page-shell__header {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.opencode-page-shell__back {
  display: inline-flex;
  width: fit-content;
}

.opencode-page-shell__icon {
  display: flex;
  width: 2.75rem;
  height: 2.75rem;
  flex-shrink: 0;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-2xl);
  background: var(--color-bg-surface);
  color: var(--color-text-secondary);
}
</style>

// ccr-ui/src/features/opencode/OpenCodePageShell.tsx
import type { ReactNode } from 'react'
import { Link } from 'react-router'
import { PageHeader, PageShell, SIcon, buttonClass } from '@/ui'

interface OpenCodePageShellProps {
  title: string
  description: string
  icon?: string
  tone?: 'lime' | 'violet' | 'cyan' | 'amber' | 'emerald'
  backTo?: string
  backLabel?: string
  badge?: string
  actions?: ReactNode
  meta?: ReactNode
  children?: ReactNode
}

/** OpenCode 子页壳。tone 仅保留调用方契约，不写字面色。 */
export function OpenCodePageShell({
  title,
  description,
  icon = 'TerminalSquare',
  tone = 'lime',
  backTo = '/opencode',
  backLabel = 'OpenCode',
  badge = '',
  actions,
  meta,
  children,
}: OpenCodePageShellProps) {
  return (
    <PageShell
      header={
        <div className="flex flex-col gap-4" data-tone={tone}>
          <Link to={backTo} className="inline-flex w-fit">
            <span className={buttonClass({ variant: 'ghost' })}>
              <SIcon name="ChevronLeft" size="w-4 h-4" />
              {backLabel}
            </span>
          </Link>
          <PageHeader
            title={title}
            description={description}
            eyebrow="OpenCode operator surface"
            eyebrowLang="en"
            leading={
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-border-subtle bg-bg-surface text-text-secondary">
                <SIcon name={icon} size="w-5 h-5" />
              </div>
            }
            status={
              badge || meta ? (
                <div className="flex items-center gap-2">
                  {badge ? (
                    <span className="rounded-md border border-border-default px-2 py-0.5 text-xs">{badge}</span>
                  ) : null}
                  {meta}
                </div>
              ) : undefined
            }
            actions={actions}
          />
        </div>
      }
    >
      {children}
    </PageShell>
  )
}
