// ccr-ui/src/features/configs/components/ConfigList.tsx
import { memo } from 'react'
import type { ConfigItem } from '@/types'
import { SIcon, Spinner } from '@/ui'
import { t } from '../locale'
import { ConfigCard } from './ConfigCard'

interface ConfigListProps {
  configs: ConfigItem[]
  loading: boolean
  error: string | null
  highlightedName: string | null
  onSwitch: (name: string) => void
  onEdit: (name: string) => void
}

export const ConfigList = memo(function ConfigList({
  configs,
  loading,
  error,
  highlightedName,
  onSwitch,
  onEdit,
}: ConfigListProps) {
  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-text-muted">
        <Spinner size="xl" className="mb-4 text-accent-primary" />
        <span className="animate-pulse font-mono text-sm">{t('common.loading')}</span>
      </div>
    )
  }
  if (error) {
    return (
      <div className="flex items-center gap-3 rounded-xl border border-accent-danger/20 bg-accent-danger/10 p-4 text-accent-danger">
        <SIcon name="AlertCircle" size="w-5 h-5" className="shrink-0" />
        <span>
          {t('configs.operationFailed')}: {error}
        </span>
      </div>
    )
  }
  if (configs.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-text-muted">
        <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl glass-surface">
          <SIcon name="Settings" size="w-8 h-8" className="opacity-20" />
        </div>
        <p>{t('configs.noConfigsInCategory')}</p>
      </div>
    )
  }
  return (
    <div className="flex flex-col gap-2">
      {configs.map((config) => (
        <ConfigCard
          key={config.name}
          config={config}
          highlighted={highlightedName === config.name}
          onSwitch={onSwitch}
          onEdit={onEdit}
        />
      ))}
    </div>
  )
})

// ccr-ui/src/components/configs/ConfigList.vue
<template>
  <div class="space-y-2">
    <!-- Loading State -->
    <div
      v-if="loading"
      class="flex flex-col items-center justify-center py-20 text-text-muted"
    >
      <Spinner
        size="xl"
        class="text-accent-primary mb-4"
      />
      <span class="text-sm font-mono animate-pulse">{{ $t('common.loading') }}</span>
    </div>

    <!-- Error State -->
    <div
      v-else-if="error"
      class="p-4 rounded-xl bg-accent-danger/10 border border-accent-danger/20 flex items-center gap-3 text-accent-danger"
    >
      <SIcon
        name="AlertCircle"
        size="w-5 h-5"
        class="shrink-0"
      />
      <span>{{ $t('configs.operationFailed') }}: {{ error }}</span>
    </div>

    <!-- Empty State -->
    <div
      v-else-if="configs.length === 0"
      class="py-20 flex flex-col items-center justify-center text-text-muted"
    >
      <div class="w-16 h-16 rounded-2xl glass-surface flex items-center justify-center mb-4">
        <SIcon
          name="Settings"
          size="w-8 h-8"
          class="opacity-20"
        />
      </div>
      <p>{{ $t('configs.noConfigsInCategory') }}</p>
    </div>

    <!-- Config List (Single Column) -->
    <div
      v-else
      class="flex flex-col gap-2"
    >
      <ConfigCard
        v-for="config in configs"
        :key="config.name"
        :config="config"
        @switch="$emit('switch', $event)"
        @edit="$emit('edit', $event)"
        @delete="$emit('delete', $event)"
        @enable="$emit('enable', $event)"
        @disable="$emit('disable', $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import type { ConfigItem } from '@/types'
import ConfigCard from '@/components/ConfigCard.vue'
import Spinner from '@/components/ui/Spinner.vue'

defineProps<{
  configs: ConfigItem[]
  loading: boolean
  error: string | null
}>()

defineEmits<{
  switch: [name: string]
  edit: [name: string]
  delete: [name: string]
  enable: [name: string]
  disable: [name: string]
}>()
</script>
