// ccr-ui/src/features/codex/CodexSessionsView.tsx
import { useCallback, useMemo, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useVirtualizer } from '@tanstack/react-virtual'
import { useForm } from 'react-hook-form'
import { Link } from 'react-router'
import {
  cloneCodexSession,
  deleteCodexSession,
  exportCodexSession,
  getCodexSessionDetail,
  listCodexSessions,
} from '@/api'
import { surfaceNotify } from '@/configs/surfaceNotify'
import { copyText } from '@/utils/clipboard'
import { getErrorMessage } from '@/utils/errorHandler'
import { PageHeader, PageShell, PillToggleGroup, SIcon, buttonClass } from '@/ui'
import { CodexSubnav } from './CodexSubnav'
import { SessionDetailPanel } from './sessions/SessionDetailPanel'
import { SessionListPanel } from './sessions/SessionListPanel'
import { DETAIL_LIMIT, EXPORT_LIMIT, SESSION_LIMIT, formatTokenCount } from './sessions/session-format'
import { panelCardClass } from './ui-classes'
import { codexKeys } from './queries'
import { useCodexLocale } from './useCodexLocale'
import type { CodexSessionSummary } from '@/types'

type SessionSort = 'recent' | 'tokens'

export function CodexSessionsView() {
  const { tt } = useCodexLocale()
  const queryClient = useQueryClient()
  const searchForm = useForm({ defaultValues: { q: '' } })
  const searchQuery = searchForm.watch('q')
  const [sessionSort, setSessionSort] = useState<SessionSort>('recent')
  const [selectedFilePath, setSelectedFilePath] = useState('')
  const listRef = useRef<HTMLDivElement>(null)
  const unknownTime = tt('未知时间', 'Unknown time')

  const listQuery = useQuery({
    queryKey: codexKeys.sessions.list(SESSION_LIMIT),
    queryFn: () => listCodexSessions({ limit: SESSION_LIMIT }),
  })
  const sessions = useMemo(() => listQuery.data?.sessions ?? [], [listQuery.data])
  const filteredSessions = useMemo(() => {
    const query = searchQuery.trim().toLowerCase()
    const matched = query
      ? sessions.filter((session) =>
          [session.session_id, session.cwd ?? '', session.model ?? '', session.preview ?? '', session.relative_path]
            .some((value) => value.toLowerCase().includes(query)),
        )
      : [...sessions]
    if (sessionSort !== 'tokens') return matched
    return matched.sort((left, right) => {
      const rightTokens = right.total_input_tokens + right.total_output_tokens
      const leftTokens = left.total_input_tokens + left.total_output_tokens
      return rightTokens - leftTokens
    })
  }, [searchQuery, sessionSort, sessions])

  const selectedPath = selectedFilePath || filteredSessions[0]?.file_path || ''
  const detailQuery = useQuery({
    queryKey: codexKeys.sessions.detail(selectedPath),
    queryFn: () => getCodexSessionDetail(selectedPath, DETAIL_LIMIT),
    enabled: Boolean(selectedPath),
  })
  const selectedSession = detailQuery.data?.session ?? null
  const totalTokens = sessions.reduce(
    (total, session) => total + session.total_input_tokens + session.total_output_tokens,
    0,
  )

  const virtualizer = useVirtualizer({
    count: filteredSessions.length,
    getScrollElement: () => listRef.current,
    estimateSize: () => 132,
    overscan: 8,
  })

  const handleOpen = useCallback((filePath: string) => {
    setSelectedFilePath(filePath)
  }, [])
  const handleRefresh = useCallback(() => {
    void listQuery.refetch()
    void detailQuery.refetch()
  }, [detailQuery, listQuery])
  const handleClearSearch = useCallback(() => {
    searchForm.reset({ q: '' })
  }, [searchForm])

  const exportMutation = useMutation({
    mutationFn: async (session: CodexSessionSummary) => exportCodexSession(session.file_path, EXPORT_LIMIT),
    onSuccess: (payload) => {
      const blob = new Blob([payload.content], { type: 'text/markdown;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = payload.file_name
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
      surfaceNotify.success(tt('Session Markdown 已导出', 'Session Markdown exported'))
    },
    onError: (error) => surfaceNotify.error(getErrorMessage(error)),
  })
  const cloneMutation = useMutation({
    mutationFn: async (session: CodexSessionSummary) => cloneCodexSession(session.file_path),
    onSuccess: async (payload) => {
      await queryClient.invalidateQueries({ queryKey: codexKeys.sessions.all })
      setSelectedFilePath(payload.session.file_path)
      surfaceNotify.success(tt('Session 已克隆到本地会话目录', 'Session cloned to the local session directory'))
    },
    onError: (error) => surfaceNotify.error(getErrorMessage(error)),
  })
  const deleteMutation = useMutation({
    mutationFn: async (session: CodexSessionSummary) => deleteCodexSession(session.file_path),
    onSuccess: async () => {
      const fallback = sessions.find((session) => session.file_path !== selectedPath)?.file_path ?? ''
      await queryClient.invalidateQueries({ queryKey: codexKeys.sessions.all })
      setSelectedFilePath(fallback)
      surfaceNotify.success(tt('Session 已删除', 'Session deleted'))
    },
    onError: (error) => surfaceNotify.error(getErrorMessage(error)),
  })

  const actionLoading = exportMutation.isPending || cloneMutation.isPending || deleteMutation.isPending
  const handleExport = useCallback(() => {
    if (selectedSession) void exportMutation.mutateAsync(selectedSession)
  }, [exportMutation, selectedSession])
  const handleClone = useCallback(() => {
    if (selectedSession) void cloneMutation.mutateAsync(selectedSession)
  }, [cloneMutation, selectedSession])
  const handleDelete = useCallback(async () => {
    if (!selectedSession) return
    const ok = await surfaceNotify.confirm({
      title: tt('删除 Session', 'Delete session'),
      message: tt(
        `确认删除 ${selectedSession.session_id} 吗？这个操作会直接删除本地 JSONL 文件。`,
        `Delete ${selectedSession.session_id}? This will delete the local JSONL file.`,
      ),
      confirmText: tt('删除', 'Delete'),
      cancelText: tt('取消', 'Cancel'),
      type: 'danger',
    })
    if (ok) void deleteMutation.mutateAsync(selectedSession)
  }, [deleteMutation, selectedSession, tt])
  const handleCopyPath = useCallback(async () => {
    if (!selectedSession) return
    const ok = await copyText(selectedSession.file_path)
    surfaceNotify[ok ? 'success' : 'error'](ok ? tt('已复制 session 文件路径', 'Session file path copied') : tt('复制失败', 'Copy failed'))
  }, [selectedSession, tt])
  const handleCopyCwd = useCallback(async () => {
    if (!selectedSession?.cwd) return
    const ok = await copyText(selectedSession.cwd)
    surfaceNotify[ok ? 'success' : 'error'](ok ? tt('已复制工作目录', 'Working directory copied') : tt('复制失败', 'Copy failed'))
  }, [selectedSession, tt])

  const sortOptions = useMemo(
    () => [
      { value: 'recent' as const, label: tt('最近', 'Recent') },
      { value: 'tokens' as const, label: 'Tokens' },
    ],
    [tt],
  )

  return (
    <PageShell
      header={
        <PageHeader
          title={tt('Codex 会话', 'Codex Sessions')}
          description={tt(
            '直接读取本地 `~/.codex/sessions`，集中查看会话上下文、导出记录和复制工作流样本。',
            'Read local `~/.codex/sessions` directly to inspect session context, export records, and copy workflow samples.',
          )}
          leading={
            <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-platform-codex/20 bg-platform-codex/10">
              <SIcon name="MessagesSquare" size="w-6 h-6" className="text-platform-codex" />
            </div>
          }
          actions={
            <div className="flex flex-wrap gap-2">
              <Link to="/codex" className={buttonClass({ variant: 'secondary' })}>
                <SIcon name="ArrowLeft" size="w-4 h-4" />
                <span>{tt('返回 Codex', 'Back to Codex')}</span>
              </Link>
              <button type="button" className={buttonClass({ variant: 'primary' })} disabled={listQuery.isFetching} onClick={handleRefresh}>
                <SIcon name="RefreshCw" size="w-4 h-4" className={listQuery.isFetching ? 'animate-spin' : undefined} />
                {tt('刷新列表', 'Refresh list')}
              </button>
            </div>
          }
        />
      }
      subnav={<CodexSubnav />}
    >
      <div className="mb-4 grid gap-4 md:grid-cols-3">
        <div className={panelCardClass}>
          <p className="text-xs font-medium text-text-ghost">{tt('已加载会话', 'Loaded sessions')}</p>
          <p className="mt-2 text-2xl font-semibold tabular-nums text-text-primary">{sessions.length}</p>
          <p className="mt-2 text-sm text-text-muted">
            {tt(`当前窗口最多展示 ${SESSION_LIMIT} 条最近记录`, `This window shows up to ${SESSION_LIMIT} recent records`)}
          </p>
        </div>
        <div className={panelCardClass}>
          <p className="text-xs font-medium text-text-ghost">{tt('列表 Tokens', 'List tokens')}</p>
          <p className="mt-2 text-2xl font-semibold tabular-nums text-text-primary">{formatTokenCount(totalTokens)}</p>
          <p className="mt-2 text-sm text-text-muted">{tt('来自当前已加载的会话摘要', 'From the currently loaded session summaries')}</p>
        </div>
        <div className={panelCardClass}>
          <p className="text-xs font-medium text-text-ghost">{tt('当前会话消息', 'Current session messages')}</p>
          <p className="mt-2 text-2xl font-semibold tabular-nums text-text-primary">{selectedSession?.message_count ?? 0}</p>
          <p className="mt-2 text-sm text-text-muted">{tt('仅统计用户与助手消息', 'Only user and assistant messages are counted')}</p>
        </div>
      </div>

      {listQuery.error ? (
        <div className="mb-4 flex items-center gap-2 rounded-xl border border-accent-danger/20 bg-accent-danger/10 px-4 py-3 text-sm text-accent-danger">
          <SIcon name="AlertTriangle" size="w-4 h-4" />
          <span>{getErrorMessage(listQuery.error)}</span>
        </div>
      ) : null}

      <div className="grid gap-4 xl:grid-cols-[minmax(22.5rem,26.25rem)_minmax(0,1fr)]">
        <section className={`${panelCardClass} min-h-[45rem]`}>
          <div className="mb-4 flex flex-col gap-4">
            <div>
              <h2 className="text-base font-semibold text-text-primary">{tt('最近会话', 'Recent sessions')}</h2>
              <p className="text-sm text-text-muted">
                {tt('左侧列表用于快速切换，右侧查看详情和导出', 'Use the left list for quick switching and the right panel for details and export')}
              </p>
              <PillToggleGroup className="mt-3" options={sortOptions} value={sessionSort} onValueChange={setSessionSort} />
            </div>
            <label className="relative block">
              <SIcon name="Search" size="w-4 h-4" className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" />
              <input
                type="text"
                className="w-full rounded-xl border border-border-default bg-bg-elevated py-2 pr-3 pl-9 text-sm"
                placeholder={tt('搜索 session id / cwd / model', 'Search session id / cwd / model')}
                {...searchForm.register('q')}
              />
            </label>
          </div>
          <SessionListPanel
            tt={tt}
            unknownTime={unknownTime}
            listRef={listRef}
            virtualizer={virtualizer}
            filteredSessions={filteredSessions}
            selectedPath={selectedPath}
            pending={listQuery.isPending}
            onOpen={handleOpen}
            onClearSearch={handleClearSearch}
          />
        </section>

        <SessionDetailPanel
          tt={tt}
          unknownTime={unknownTime}
          selectedPath={selectedPath}
          selectedSession={selectedSession}
          detail={detailQuery.data ?? null}
          detailPending={detailQuery.isPending}
          actionLoading={actionLoading}
          onCopyPath={handleCopyPath}
          onExport={handleExport}
          onClone={handleClone}
          onDelete={handleDelete}
          onCopyCwd={handleCopyCwd}
        />
      </div>
    </PageShell>
  )
}

// ccr-ui/src/views/CodexSessionsView.vue
<template>
  <PageShell class="codex-sessions-view">
    <template #header>
      <PageHeader
        :title="tt('Codex 会话', 'Codex Sessions')"
        :description="tt('直接读取本地 `~/.codex/sessions`，集中查看会话上下文、导出记录和复制工作流样本。', 'Read local `~/.codex/sessions` directly to inspect session context, export records, and copy workflow samples.')"
      >
        <template #leading>
          <div class="codex-sessions-header__icon">
            <SIcon
              name="MessagesSquare"
              size="w-6 h-6"
              class="text-platform-codex"
            />
          </div>
        </template>
        <template #actions>
          <RouterLink
            to="/codex"
            class="btn btn-secondary"
          >
            <SIcon
              name="ArrowLeft"
              size="w-4 h-4"
            />
            <span>{{ tt('返回 Codex', 'Back to Codex') }}</span>
          </RouterLink>
          <button
            class="hidden"
            :disabled="loading"
            @click="refreshSessions()"
          />
          <Button
            variant="primary"
            surface="card"
            density="compact"
            motion="standard"
            :disabled="loading"
            @click="refreshSessions()"
          >
            <template #leading>
              <SIcon
                name="RefreshCw"
                size="w-4 h-4"
                :class="{ 'animate-spin': loading }"
              />
            </template>
            {{ tt('刷新列表', 'Refresh list') }}
          </Button>
        </template>
      </PageHeader>
    </template>

    <template #subnav>
      <ModuleSubnav module="codex" />
    </template>

    <div class="codex-sessions-stats">
      <Card
        surface="status"
        :elevation="2"
        motion="subtle"
        class="codex-sessions-stat"
      >
        <p class="codex-sessions-stat__label">
          {{ tt('已加载会话', 'Loaded sessions') }}
        </p>
        <p class="codex-sessions-stat__value">
          {{ sessions.length }}
        </p>
        <p class="codex-sessions-stat__hint">
          {{ tt(`当前窗口最多展示 ${SESSION_LIMIT} 条最近记录`, `This window shows up to ${SESSION_LIMIT} recent records`) }}
        </p>
      </Card>
      <Card
        surface="status"
        :elevation="2"
        motion="subtle"
        class="codex-sessions-stat"
      >
        <p class="codex-sessions-stat__label">
          {{ tt('列表 Tokens', 'List tokens') }}
        </p>
        <p class="codex-sessions-stat__value">
          {{ formatTokenCount(totalTokens) }}
        </p>
        <p class="codex-sessions-stat__hint">
          {{ tt('来自当前已加载的会话摘要', 'From the currently loaded session summaries') }}
        </p>
      </Card>
      <Card
        surface="status"
        :elevation="2"
        motion="subtle"
        class="codex-sessions-stat"
      >
        <p class="codex-sessions-stat__label">
          {{ tt('当前会话消息', 'Current session messages') }}
        </p>
        <p class="codex-sessions-stat__value">
          {{ selectedSession?.message_count ?? 0 }}
        </p>
        <p class="codex-sessions-stat__hint">
          {{ tt('仅统计用户与助手消息', 'Only user and assistant messages are counted') }}
        </p>
      </Card>
    </div>

    <div
      v-if="loadError"
      class="codex-sessions-error"
    >
      <SIcon
        name="AlertTriangle"
        size="w-4 h-4"
      />
      <span>{{ loadError }}</span>
    </div>

    <div class="codex-sessions-workspace">
      <Card
        surface="workspace"
        :elevation="2"
        motion="subtle"
        class="codex-sessions-panel codex-sessions-panel--list"
      >
        <div class="codex-sessions-panel__header">
          <div>
            <h2 class="codex-sessions-panel__title">
              {{ tt('最近会话', 'Recent sessions') }}
            </h2>
            <p class="codex-sessions-panel__subtitle">
              {{ tt('左侧列表用于快速切换，右侧查看详情和导出', 'Use the left list for quick switching and the right panel for details and export') }}
            </p>
            <PillToggleGroup
              class="mt-3"
              :options="sessionSortOptions"
              :model-value="sessionSort"
              @update:model-value="sessionSort = $event"
            />
          </div>

          <div class="codex-sessions-search">
            <Input
              v-model="searchQuery"
              type="text"
              surface="status"
              :elevation="1"
              motion="subtle"
              density="compact"
              :full-width="true"
              :placeholder="tt('搜索 session id / cwd / model', 'Search session id / cwd / model')"
            >
              <template #leading>
                <SIcon
                  name="Search"
                  size="w-4 h-4"
                />
              </template>
            </Input>
          </div>
        </div>

        <div
          v-if="loading"
          class="codex-sessions-loading"
        >
          <div class="codex-sessions-loading__spinner" />
          <span>{{ tt('正在读取本地会话记录…', 'Loading local session records...') }}</span>
        </div>

        <EmptyState
          v-else-if="filteredSessions.length === 0"
          icon="Inbox"
          :title="tt('没有匹配的会话', 'No matching sessions')"
          :description="tt('当前过滤条件下没有找到会话，试试清空搜索或刷新列表。', 'No sessions match the current filters. Try clearing the search or refreshing the list.')"
          :action-text="tt('清空搜索', 'Clear search')"
          action-icon="RotateCcw"
          :on-action="clearSearch"
        />

        <div
          v-else
          class="codex-sessions-list"
        >
          <button
            v-for="session in filteredSessions"
            :key="session.file_path"
            type="button"
            class="codex-session-row"
            :class="{
              'codex-session-row--active': session.file_path === selectedFilePath,
            }"
            @click="openSession(session.file_path)"
          >
            <div class="codex-session-row__top">
              <div class="min-w-0">
                <p class="codex-session-row__id">
                  {{ session.session_id }}
                </p>
                <p class="codex-session-row__meta">
                  {{ session.model || tt('未知模型', 'Unknown model') }} ·
                  {{ formatRelative(session.updated_at) }}
                </p>
              </div>

              <span class="codex-session-row__badge"> {{ tt(`${session.message_count} 条消息`, `${session.message_count} msg`) }} </span>
            </div>

            <p
              v-if="session.preview"
              class="codex-session-row__preview"
            >
              {{ session.preview }}
            </p>

            <div class="codex-session-row__footer">
              <span class="truncate">{{ session.cwd || session.relative_path }}</span>
              <span>{{
                formatTokenCount(session.total_input_tokens + session.total_output_tokens)
              }}</span>
            </div>
          </button>
        </div>
      </Card>

      <Card
        surface="workspace"
        :elevation="2"
        motion="subtle"
        class="codex-sessions-panel codex-sessions-panel--detail"
      >
        <div class="codex-sessions-panel__header">
          <div>
            <h2 class="codex-sessions-panel__title">
              {{ tt('会话详情', 'Session details') }}
            </h2>
            <p class="codex-sessions-panel__subtitle">
              {{ tt('当前默认只展示用户与助手消息，避免把系统提示词刷满工作台', 'By default, only user and assistant messages are shown so system prompts do not flood the workspace') }}
            </p>
          </div>

          <div class="codex-detail-actions">
            <Button
              variant="glass"
              surface="status"
              density="compact"
              motion="subtle"
              :disabled="!selectedSession || actionLoading"
              @click="copyFilePath"
            >
              <template #leading>
                <SIcon
                  name="Copy"
                  size="w-4 h-4"
                />
              </template>
              {{ tt('复制路径', 'Copy path') }}
            </Button>
            <Button
              variant="glass"
              surface="status"
              density="compact"
              motion="subtle"
              :disabled="!selectedSession || actionLoading"
              @click="handleExport"
            >
              <template #leading>
                <SIcon
                  name="Download"
                  size="w-4 h-4"
                />
              </template>
              {{ tt('导出', 'Export') }}
            </Button>
            <Button
              variant="glass"
              surface="status"
              density="compact"
              motion="subtle"
              :disabled="!selectedSession || actionLoading"
              @click="handleClone"
            >
              <template #leading>
                <SIcon
                  name="CopyPlus"
                  size="w-4 h-4"
                />
              </template>
              {{ tt('克隆', 'Clone') }}
            </Button>
            <Button
              variant="danger"
              surface="status"
              density="compact"
              motion="subtle"
              :disabled="!selectedSession || actionLoading"
              @click="handleDelete"
            >
              <template #leading>
                <SIcon
                  name="Trash2"
                  size="w-4 h-4"
                />
              </template>
              {{ tt('删除', 'Delete') }}
            </Button>
          </div>
        </div>

        <div
          v-if="detailLoading"
          class="codex-sessions-loading"
        >
          <div class="codex-sessions-loading__spinner" />
          <span>{{ tt('正在读取会话详情…', 'Loading session details...') }}</span>
        </div>

        <EmptyState
          v-else-if="!detail"
          icon="MessagesSquare"
          :title="tt('还没有选中会话', 'No session selected yet')"
          :description="tt('从左侧选择一个最近会话，就可以在这里查看详细上下文。', 'Select a recent session on the left to inspect its full context here.')"
        />

        <div
          v-else
          class="codex-detail"
        >
          <div class="codex-detail-summary">
            <div class="codex-detail-summary__title-row">
              <div>
                <h3 class="codex-detail-summary__title">
                  {{ selectedSession?.session_id }}
                </h3>
                <p class="codex-detail-summary__meta">
                  {{ selectedSession?.model || tt('未知模型', 'Unknown model') }} ·
                  {{ formatAbsolute(selectedSession?.updated_at) }}
                </p>
              </div>
              <span class="codex-detail-summary__pill">
                {{ tt(`${selectedSession?.total_requests ?? 0} 次请求`, `${selectedSession?.total_requests ?? 0} req`) }}
              </span>
            </div>

            <div class="codex-detail-grid">
              <div class="codex-detail-field">
                <span class="codex-detail-field__label">{{ tt('工作目录', 'Working directory') }}</span>
                <button
                  type="button"
                  class="codex-detail-field__value codex-detail-field__value--button"
                  @click="copyCwd"
                >
                  {{ selectedSession?.cwd || tt('N/A', 'N/A') }}
                </button>
              </div>
              <div class="codex-detail-field">
                <span class="codex-detail-field__label">{{ tt('相对路径', 'Relative path') }}</span>
                <span class="codex-detail-field__value">
                  {{ selectedSession?.relative_path }}
                </span>
              </div>
              <div class="codex-detail-field">
                <span class="codex-detail-field__label">{{ tt('输入 / 输出', 'Input / output') }}</span>
                <span class="codex-detail-field__value">
                  {{ formatTokenCount(selectedSession?.total_input_tokens ?? 0) }}
                  /
                  {{ formatTokenCount(selectedSession?.total_output_tokens ?? 0) }}
                </span>
              </div>
              <div class="codex-detail-field">
                <span class="codex-detail-field__label">{{ tt('CLI 版本', 'CLI version') }}</span>
                <span class="codex-detail-field__value">
                  {{ selectedSession?.cli_version || tt('N/A', 'N/A') }}
                </span>
              </div>
            </div>

            <div
              v-if="detail.clipped"
              class="codex-detail-tip"
            >
              {{ tt(`详情面板只展示最近 ${detail.message_limit} 条消息，导出会沿用同样的窗口上限。`, `The detail panel only shows the most recent ${detail.message_limit} messages, and export uses the same window limit.`) }}
            </div>
          </div>

          <div class="codex-detail-messages">
            <article
              v-for="(message, index) in detail.messages"
              :key="`${message.timestamp || 'none'}-${index}`"
              class="codex-message"
              :class="
                message.role === 'assistant'
                  ? 'codex-message--assistant'
                  : 'codex-message--user'
              "
            >
              <div class="codex-message__meta">
                <span class="codex-message__role">
                  {{ message.role === 'assistant' ? tt('助手', 'Assistant') : tt('用户', 'User') }}
                </span>
                <span class="codex-message__time">
                  {{ formatAbsolute(message.timestamp) }}
                </span>
              </div>
              <pre class="codex-message__body"><code>{{ message.text }}</code></pre>
            </article>
          </div>
        </div>
      </Card>
    </div>
  </PageShell>
</template>

<script setup lang="ts">
import { computed, onActivated, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { getErrorMessage } from '@/utils/errorHandler'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import EmptyState from '@/components/ui/EmptyState.vue'
import Input from '@/components/ui/Input.vue'
import ModuleSubnav from '@/components/ModuleSubnav.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import PageShell from '@/components/ui/PageShell.vue'
import PillToggleGroup from '@/components/ui/PillToggleGroup.vue'
import SIcon from '@/components/ui/SIcon.vue'
import {
  cloneCodexSession,
  deleteCodexSession,
  exportCodexSession,
  getCodexSessionDetail,
  listCodexSessions,
} from '@/api'
import { useUIStore } from '@/stores/ui'
import { formatRelativeTime, formatTimestamp } from '@/utils/codexHelpers'
import { copyText } from '@/utils/clipboard'
import { logger } from '@/utils/logger'
import type {
  CodexSessionDetailResponse,
  CodexSessionSummary,
} from '@/types'

defineOptions({ name: 'CodexSessionsView' })

const SESSION_LIMIT = 160
const DETAIL_LIMIT = 120
const EXPORT_LIMIT = 200

const { locale } = useI18n()
const isZh = computed(() => locale.value.startsWith('zh'))
const tt = (zh: string, en: string) => (isZh.value ? zh : en)
const uiStore = useUIStore()

const loading = ref(true)
const detailLoading = ref(false)
const actionLoading = ref(false)
const loadError = ref<string | null>(null)
const sessions = ref<CodexSessionSummary[]>([])
const detail = ref<CodexSessionDetailResponse | null>(null)
const selectedFilePath = ref('')
const searchQuery = ref('')
const sessionSort = ref<'recent' | 'tokens'>('recent')

const selectedSession = computed(() => detail.value?.session ?? null)

const sessionSortOptions = computed(() => [
  { value: 'recent' as const, label: tt('最近', 'Recent') },
  { value: 'tokens' as const, label: 'Tokens' },
])

const filteredSessions = computed(() => {
  const query = searchQuery.value.trim().toLowerCase()
  const matched = query
    ? sessions.value.filter((session) => {
        return [
          session.session_id,
          session.cwd ?? '',
          session.model ?? '',
          session.preview ?? '',
          session.relative_path,
        ].some((value) => value.toLowerCase().includes(query))
      })
    : [...sessions.value]

  if (sessionSort.value === 'tokens') {
    return matched.sort((left, right) => {
      const rightTokens = right.total_input_tokens + right.total_output_tokens
      const leftTokens = left.total_input_tokens + left.total_output_tokens
      return rightTokens - leftTokens
    })
  }

  return matched
})

const totalTokens = computed(() => {
  return sessions.value.reduce((total, session) => {
    return total + session.total_input_tokens + session.total_output_tokens
  }, 0)
})

function formatTokenCount(value: number): string {
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}K`
  return String(value)
}

function formatRelative(value?: string | null): string {
  if (!value) return tt('未知时间', 'Unknown time')
  return formatRelativeTime(value)
}

function formatAbsolute(value?: string | null): string {
  if (!value) return tt('未知时间', 'Unknown time')
  return formatTimestamp(value)
}

function extractErrorMessage(error: unknown): string {
  return getErrorMessage(error)
}

async function loadSessionDetail(filePath: string) {
  detailLoading.value = true
  try {
    selectedFilePath.value = filePath
    detail.value = await getCodexSessionDetail(filePath, DETAIL_LIMIT)
  } catch (error) {
    const message = extractErrorMessage(error)
    logger.error('Failed to load codex session detail:', error)
    uiStore.showError(message)
  } finally {
    detailLoading.value = false
  }
}

async function loadSessions(preferredFilePath?: string) {
  loading.value = true
  loadError.value = null

  try {
    const response = await listCodexSessions({ limit: SESSION_LIMIT })
    sessions.value = response.sessions ?? []

    const nextFilePath = preferredFilePath ?? selectedFilePath.value ?? sessions.value[0]?.file_path

    if (nextFilePath && sessions.value.some((session) => session.file_path === nextFilePath)) {
      await loadSessionDetail(nextFilePath)
    } else if (sessions.value[0]?.file_path) {
      await loadSessionDetail(sessions.value[0].file_path)
    } else {
      selectedFilePath.value = ''
      detail.value = null
    }
  } catch (error) {
    loadError.value = extractErrorMessage(error)
    logger.error('Failed to load codex sessions:', error)
  } finally {
    loading.value = false
  }
}

function refreshSessions() {
  void loadSessions(selectedFilePath.value || undefined)
}

function clearSearch() {
  searchQuery.value = ''
}

function openSession(filePath: string) {
  if (filePath === selectedFilePath.value && detail.value) {
    return
  }
  void loadSessionDetail(filePath)
}

async function handleExport() {
  if (!selectedSession.value) {
    return
  }

  actionLoading.value = true
  try {
    const payload = await exportCodexSession(
      selectedSession.value.file_path,
      EXPORT_LIMIT
    )
    const blob = new Blob([payload.content], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = payload.file_name
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    uiStore.showSuccess(tt('Session Markdown 已导出', 'Session Markdown exported'))
  } catch (error) {
    const message = extractErrorMessage(error)
    logger.error('Failed to export codex session:', error)
    uiStore.showError(message)
  } finally {
    actionLoading.value = false
  }
}

async function handleClone() {
  if (!selectedSession.value) {
    return
  }

  actionLoading.value = true
  try {
    const payload = await cloneCodexSession(
      selectedSession.value.file_path
    )
    await loadSessions(payload.session.file_path)
    uiStore.showSuccess(tt('Session 已克隆到本地会话目录', 'Session cloned to the local session directory'))
  } catch (error) {
    const message = extractErrorMessage(error)
    logger.error('Failed to clone codex session:', error)
    uiStore.showError(message)
  } finally {
    actionLoading.value = false
  }
}

async function handleDelete() {
  if (!selectedSession.value) {
    return
  }

  const confirmed = await uiStore.requestConfirm({
    title: tt('删除 Session', 'Delete session'),
    message: tt(`确认删除 ${selectedSession.value.session_id} 吗？这个操作会直接删除本地 JSONL 文件。`, `Delete ${selectedSession.value.session_id}? This will delete the local JSONL file.`),
    confirmText: tt('删除', 'Delete'),
    cancelText: tt('取消', 'Cancel'),
    type: 'danger',
  })

  if (!confirmed) {
    return
  }

  const deletingPath = selectedSession.value.file_path
  const fallbackFilePath = sessions.value.find(
    (session) => session.file_path !== deletingPath
  )?.file_path

  actionLoading.value = true
  try {
    await deleteCodexSession(deletingPath)
    await loadSessions(fallbackFilePath)
    uiStore.showSuccess(tt('Session 已删除', 'Session deleted'))
  } catch (error) {
    const message = extractErrorMessage(error)
    logger.error('Failed to delete codex session:', error)
    uiStore.showError(message)
  } finally {
    actionLoading.value = false
  }
}

async function copyFilePath() {
  if (!selectedSession.value) return
  const success = await copyText(selectedSession.value.file_path)
  if (success) {
    uiStore.showSuccess(tt('已复制 session 文件路径', 'Session file path copied'))
  } else {
    uiStore.showError(tt('复制失败', 'Copy failed'))
  }
}

async function copyCwd() {
  if (!selectedSession.value?.cwd) return
  const success = await copyText(selectedSession.value.cwd)
  if (success) {
    uiStore.showSuccess(tt('已复制工作目录', 'Working directory copied'))
  } else {
    uiStore.showError(tt('复制失败', 'Copy failed'))
  }
}

onMounted(() => {
  void loadSessions()
})

onActivated(() => {
  if (!sessions.value.length) {
    void loadSessions()
  }
})
</script>

<style scoped>
.codex-sessions-header__icon {
  @apply flex h-10 w-10 items-center justify-center rounded-xl border border-platform-codex/20 bg-platform-codex/10;
}

.codex-sessions-stats {
  @apply grid gap-4 md:grid-cols-3;
}

.codex-sessions-stat {
  @apply p-5;
}

.codex-sessions-stat__label {
  @apply text-xs font-medium text-text-ghost;
}

.codex-sessions-stat__value {
  @apply mt-2 text-2xl font-semibold tabular-nums text-text-primary;
}

.codex-sessions-stat__hint {
  @apply mt-2 text-sm text-text-muted;
}

.codex-sessions-error {
  @apply flex items-center gap-2 rounded-xl border border-accent-danger/20 bg-accent-danger/10 px-4 py-3 text-sm text-accent-danger;
}

.codex-sessions-workspace {
  @apply grid gap-4 xl:grid-cols-[minmax(360px,420px)_minmax(0,1fr)];
}

.codex-sessions-panel {
  @apply p-5;
}

.codex-sessions-panel--list,
.codex-sessions-panel--detail {
  min-height: 720px;
}

.codex-sessions-panel__header {
  @apply mb-4 flex flex-col gap-4;
}

.codex-sessions-panel__title {
  @apply text-base font-semibold text-text-primary;
}

.codex-sessions-panel__subtitle {
  @apply text-sm text-text-muted;
}

.codex-sessions-loading {
  @apply flex h-full min-h-[320px] flex-col items-center justify-center gap-3 text-sm text-text-muted;
}

.codex-sessions-loading__spinner {
  @apply h-9 w-9 animate-spin rounded-full border-4 border-transparent border-r-platform-codex border-t-platform-codex;
}

.codex-sessions-list {
  @apply space-y-3 overflow-y-auto pr-1;

  max-height: 620px;
}

.codex-session-row {
  @apply w-full rounded-2xl border border-border-default/15 bg-bg-elevated p-4 text-left transition-all duration-200 hover:border-platform-codex/25 hover:bg-bg-elevated/80;
}

.codex-session-row--active {
  @apply border-platform-codex/35 bg-platform-codex/10;
}

.codex-session-row__top {
  @apply flex items-start justify-between gap-3;
}

.codex-session-row__id {
  @apply truncate font-mono text-sm font-semibold text-text-primary;
}

.codex-session-row__meta {
  @apply mt-1 text-xs text-text-ghost;
}

.codex-session-row__badge {
  @apply shrink-0 rounded-full border border-border-default/15 bg-bg-elevated px-2.5 py-1 text-[11px] text-text-secondary;
}

.codex-session-row__preview {
  @apply mt-3 line-clamp-3 text-sm leading-6 text-text-secondary;
}

.codex-session-row__footer {
  @apply mt-3 flex items-center justify-between gap-3 text-xs text-text-ghost;
}

.codex-detail-actions {
  @apply flex flex-wrap gap-2;
}

.codex-detail {
  @apply flex h-full flex-col gap-4;
}

.codex-detail-summary {
  @apply rounded-2xl border border-border-default/15 bg-bg-elevated p-4;
}

.codex-detail-summary__title-row {
  @apply flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between;
}

.codex-detail-summary__title {
  @apply font-mono text-lg font-semibold text-text-primary;
}

.codex-detail-summary__meta {
  @apply mt-1 text-sm text-text-muted;
}

.codex-detail-summary__pill {
  @apply inline-flex items-center rounded-md border border-platform-codex/20 bg-platform-codex/10 px-3 py-1 text-xs font-medium text-platform-codex;
}

.codex-detail-grid {
  @apply mt-4 grid gap-3 md:grid-cols-2;
}

.codex-detail-field {
  @apply rounded-2xl border border-border-default/15 bg-bg-base px-3 py-3;
}

.codex-detail-field__label {
  @apply text-xs font-medium text-text-ghost;
}

.codex-detail-field__value {
  @apply mt-1 block break-all text-sm text-text-primary;
}

.codex-detail-field__value--button {
  @apply text-left transition-colors hover:text-platform-codex;
}

.codex-detail-tip {
  @apply mt-4 rounded-xl border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-sm text-amber-200;
}

.codex-detail-messages {
  @apply flex-1 space-y-3 overflow-y-auto pr-1;

  max-height: 520px;
}

.codex-message {
  @apply rounded-2xl border p-4;
}

.codex-message--assistant {
  @apply border-indigo-500/20 bg-indigo-500/10;
}

.codex-message--user {
  @apply border-border-default/15 bg-bg-elevated;
}

.codex-message__meta {
  @apply flex items-center justify-between gap-3 text-xs;
}

.codex-message__role {
  @apply font-semibold uppercase tracking-[0.18em] text-text-muted;
}

.codex-message__time {
  @apply text-text-ghost;
}

.codex-message__body {
  @apply mt-3 overflow-x-auto whitespace-pre-wrap break-words text-sm leading-7 text-text-primary;

  font-family: var(--font-mono);
}
</style>
