// ccr-ui/src/features/usage/dashboard/DashboardView.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { getCliVersions, getSystemInfo } from '@/api'
import { getErrorMessage } from '@/utils/errorHandler'
import { logger } from '@/utils/logger'
import { perfMark, shouldLogPerfTelemetry } from '@/utils/perfTelemetry'
import { readPrefersReducedMotion } from '@/utils/reducedMotion'
import { scheduleWhenIdle } from '@/utils/scheduling'
import { isTauriRuntime } from '@/utils/tauriRuntime'
import { PageHeader } from '@/ui'
import type { CliVersionEntry, CliVersionsResponse, SystemInfo } from '@/types'
import {
  buildDashboardPresentation,
  type DashboardBackendStatus,
  type DashboardPlatformSource,
} from '@/views/dashboard/dashboardPresentation'
import { useHomeUsageOverview } from '../queries'
import { hydrateUsageLocale, useUsageT } from '../translate'
import { DashboardNextActions } from './DashboardNextActions'
import { DashboardPlatformMatrix } from './DashboardPlatformMatrix'
import { DashboardReadinessLedger } from './DashboardReadinessLedger'
import { DashboardSignalStream } from './DashboardSignalStream'
import { DashboardUsageMovement } from './DashboardUsageMovement'
import { useDashboardSignals } from './useDashboardSignals'
import '../styles/dashboard-view.css'

const CLI_PLATFORM_ALIASES: Record<string, string> = {
  claude: 'claude-code',
  'claude-code': 'claude-code',
  codex: 'codex',
  gemini: 'antigravity',
  agy: 'antigravity',
  antigravity: 'antigravity',
  'antigravity-cli': 'antigravity',
  'gemini-cli': 'antigravity',
  opencode: 'opencode',
  'open-code': 'opencode',
}

const normalizeDashboardCliPlatform = (platform: string) =>
  CLI_PLATFORM_ALIASES[platform.trim().toLowerCase()] ?? null

export function DashboardView() {
  const t = useUsageT()
  const [activeDays, setActiveDays] = useState(7)
  const overviewQuery = useHomeUsageOverview(activeDays)
  const { logs, pause, resume } = useDashboardSignals(24)
  const [systemInfo, setSystemInfo] = useState<SystemInfo | null>(null)
  const [systemInfoError, setSystemInfoError] = useState<string | null>(null)
  const [cliVersions, setCliVersions] = useState<Map<string, CliVersionEntry>>(new Map())
  const [cliVersionsLoaded, setCliVersionsLoaded] = useState(false)
  const isNativeRuntime = isTauriRuntime()

  const applyCliVersions = useCallback((entries: CliVersionEntry[]) => {
    const normalized = new Map<string, CliVersionEntry>()
    entries.forEach((entry) => {
      const platformKey = normalizeDashboardCliPlatform(entry.platform)
      if (!platformKey) return
      normalized.set(platformKey, { ...entry, platform: platformKey })
    })
    setCliVersions(normalized)
    setCliVersionsLoaded(true)
    perfMark('dashboard:cli-badges-updated')
  }, [])

  useEffect(() => {
    void hydrateUsageLocale()
    const cancel = scheduleWhenIdle(() => {
      if (!isNativeRuntime) {
        perfMark('dashboard:web-preview-ready')
        setCliVersionsLoaded(true)
        return
      }
      void getSystemInfo()
        .then((info) => {
          setSystemInfo(info)
          setSystemInfoError(null)
          perfMark('dashboard:system-ready')
        })
        .catch((caught: unknown) => {
          setSystemInfoError(getErrorMessage(caught))
          logger.error('[DashboardView] failed to load system info', caught)
        })
      void getCliVersions({ mode: 'fast', timeoutMs: 3500, parallelism: 4 })
        .then((versions: CliVersionsResponse) => applyCliVersions(versions.entries))
        .catch((caught: unknown) => {
          setCliVersionsLoaded(true)
          logger.error('[DashboardView] failed to load CLI versions', caught)
        })
    }, { timeout: 1400, fallbackDelay: 280 })

    return () => {
      cancel()
      pause()
    }
  }, [applyCliVersions, isNativeRuntime, pause])

  useEffect(() => {
    resume()
  }, [resume])

  const loadUsageOverview = useCallback((days: number) => {
    setActiveDays(days)
  }, [])

  const backendStatus: DashboardBackendStatus = !isNativeRuntime
    ? 'unsupported'
    : systemInfoError
      ? 'error'
      : systemInfo
        ? 'ok'
        : 'checking'

  const platforms = useMemo<DashboardPlatformSource[]>(() => [
    {
      title: t('dashboard.platforms.claudeTitle'),
      desc: t('dashboard.platforms.claudeDesc'),
      path: '/claude-code',
      icon: 'Code2',
      iconClass: 'text-platform-claude',
      platformKey: 'claude-code',
      usageKey: 'claude',
      role: t('dashboard.platforms.roleCoreCli'),
      mode: 'cli',
      isRuntimeCli: true,
    },
    {
      title: t('dashboard.platforms.codexTitle'),
      desc: t('dashboard.platforms.codexDesc'),
      path: '/codex',
      icon: 'Settings',
      iconClass: 'text-platform-codex',
      platformKey: 'codex',
      usageKey: 'codex',
      role: t('dashboard.platforms.roleCoreCli'),
      mode: 'cli',
      isRuntimeCli: true,
    },
    {
      title: t('dashboard.platforms.antigravityTitle'),
      desc: t('dashboard.platforms.antigravityDesc'),
      path: '/antigravity',
      icon: 'Sparkles',
      iconClass: 'text-platform-gemini',
      platformKey: 'antigravity',
      usageKey: 'gemini',
      role: t('dashboard.platforms.roleCoreCli'),
      mode: 'cli',
      isRuntimeCli: true,
    },
    {
      title: t('dashboard.platforms.opencodeTitle'),
      desc: t('dashboard.platforms.opencodeDesc'),
      path: '/opencode',
      icon: 'TerminalSquare',
      iconClass: 'text-accent-info',
      platformKey: 'opencode',
      usageKey: 'opencode',
      role: t('dashboard.platforms.roleManaged'),
      mode: 'managed',
      isRuntimeCli: false,
    },
  ], [t])

  const dashboardPresentation = useMemo(() => buildDashboardPresentation({
    backendStatus,
    isNativeRuntime,
    systemInfo,
    cliVersions,
    cliVersionsLoaded,
    platforms,
    overview: overviewQuery.data ?? null,
    usageLoading: overviewQuery.isLoading,
    usageError: overviewQuery.error ? getErrorMessage(overviewQuery.error) : null,
    logs,
  }), [
    backendStatus,
    cliVersions,
    cliVersionsLoaded,
    isNativeRuntime,
    logs,
    overviewQuery.data,
    overviewQuery.error,
    overviewQuery.isLoading,
    platforms,
    systemInfo,
  ])

  const scrollToReadiness = useCallback(() => {
    const target = document.querySelector('[data-dashboard-readiness]')
    const reduceMotion = readPrefersReducedMotion()
    target?.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' })
  }, [])

  useEffect(() => {
    if (!shouldLogPerfTelemetry() || typeof performance === 'undefined') return undefined
    const timer = window.setTimeout(() => {
      logger.info('[Perf]', { scope: 'dashboard' })
    }, 4500)
    return () => window.clearTimeout(timer)
  }, [])

  return (
    <main className="dashboard-view">
      <div className="dashboard-workbench">
        <section className="dashboard-header" data-dashboard-hero>
          <PageHeader
            title={t('dashboard.title')}
            eyebrow={t('dashboard.eyebrow')}
            description={t('dashboard.description')}
            status={(
              <button
                type="button"
                className="dashboard-header__badge"
                data-status={dashboardPresentation.readiness.status}
                aria-label={t('dashboard.readiness.label')}
                onClick={scrollToReadiness}
              >
                <span className="dashboard-header__badge-dot" aria-hidden="true" />
                {t(dashboardPresentation.readiness.labelKey)}
              </button>
            )}
          />
        </section>
        <section className="dashboard-grid dashboard-grid--status">
          <DashboardReadinessLedger
            className="dashboard-grid__readiness"
            readiness={dashboardPresentation.readiness}
            statusMetrics={dashboardPresentation.statusMetrics}
          />
        </section>
        <section className="dashboard-grid dashboard-grid--actions">
          <DashboardNextActions
            className="dashboard-grid__actions"
            actions={dashboardPresentation.actions}
            showOnboarding={dashboardPresentation.isFirstRun}
          />
        </section>
        <section className="dashboard-grid dashboard-grid--insight">
          <DashboardUsageMovement
            className="dashboard-grid__usage"
            overview={overviewQuery.data ?? null}
            loading={overviewQuery.isLoading}
            error={overviewQuery.error ? getErrorMessage(overviewQuery.error) : null}
            activeDays={activeDays}
            onChangeDays={loadUsageOverview}
          />
          <DashboardSignalStream
            className="dashboard-grid__signals"
            entries={logs}
            limit={6}
          />
        </section>
        <DashboardPlatformMatrix
          className="dashboard-grid__entries"
          rows={dashboardPresentation.platformRows}
          installedCliCount={dashboardPresentation.installedCliCount}
          runtimeCliCount={dashboardPresentation.runtimeCliCount}
        />
      </div>
    </main>
  )
}

// ccr-ui/src/views/DashboardView.vue
<template>
  <main class="dashboard-view">
    <div class="dashboard-workbench">
      <section
        class="dashboard-header"
        data-dashboard-hero
      >
        <PageHeader
          :title="t('dashboard.title')"
          :eyebrow="t('dashboard.eyebrow')"
          :description="t('dashboard.description')"
        >
          <template #status>
            <button
              type="button"
              class="dashboard-header__badge"
              :data-status="dashboardPresentation.readiness.status"
              :aria-label="t('dashboard.readiness.label')"
              @click="scrollToReadiness"
            >
              <span
                class="dashboard-header__badge-dot"
                aria-hidden="true"
              />
              {{ t(dashboardPresentation.readiness.labelKey) }}
            </button>
          </template>
        </PageHeader>
      </section>

      <section class="dashboard-grid dashboard-grid--status">
        <DashboardReadinessLedger
          class="dashboard-grid__readiness"
          :readiness="dashboardPresentation.readiness"
          :status-metrics="dashboardPresentation.statusMetrics"
        />
      </section>

      <section class="dashboard-grid dashboard-grid--actions">
        <DashboardNextActions
          class="dashboard-grid__actions"
          :actions="dashboardPresentation.actions"
          :show-onboarding="dashboardPresentation.isFirstRun"
        />
      </section>

      <section class="dashboard-grid dashboard-grid--insight">
        <DashboardUsageMovement
          class="dashboard-grid__usage"
          :overview="overview"
          :loading="usageLoading"
          :error="usageError"
          :active-days="activeDays"
          @change-days="loadUsageOverview"
        />
        <DashboardSignalStream
          class="dashboard-grid__signals"
          :entries="logs"
          :limit="6"
        />
      </section>

      <DashboardPlatformMatrix
        class="dashboard-grid__entries"
        :rows="dashboardPresentation.platformRows"
        :installed-cli-count="dashboardPresentation.installedCliCount"
        :runtime-cli-count="dashboardPresentation.runtimeCliCount"
      />
    </div>
  </main>
</template>

<script setup lang="ts">
import { computed, onActivated, onBeforeUnmount, onDeactivated, onMounted, ref } from 'vue'
import { getErrorMessage } from '@/utils/errorHandler'
import { useI18n } from 'vue-i18n'
import { storeToRefs } from 'pinia'
import DashboardNextActions from '@/components/dashboard/DashboardNextActions.vue'
import DashboardPlatformMatrix from '@/components/dashboard/DashboardPlatformMatrix.vue'
import DashboardReadinessLedger from '@/components/dashboard/DashboardReadinessLedger.vue'
import DashboardSignalStream from '@/components/dashboard/DashboardSignalStream.vue'
import DashboardUsageMovement from '@/components/dashboard/DashboardUsageMovement.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import { getCliVersions, getSystemInfo } from '@/api/runtime/system'
import { useMonitoringFeed } from '@/composables/useMonitoringFeed'
import { useHomeUsageOverviewStore } from '@/stores/homeUsageOverview'
import { logger } from '@/utils/logger'
import { perfMark, shouldLogPerfTelemetry } from '@/utils/perfTelemetry'
import { scheduleWhenIdle } from '@/utils/scheduling'
import { isTauriRuntime } from '@/utils/tauriRuntime'
import {
  buildDashboardPresentation,
  type DashboardBackendStatus,
  type DashboardPlatformSource,
} from '@/views/dashboard/dashboardPresentation'
import type { CliVersionEntry, CliVersionsResponse, SystemInfo } from '@/types'

const { t } = useI18n()
const usageOverviewStore = useHomeUsageOverviewStore()
const { overview, loading: usageLoading, error: usageError, activeDays } = storeToRefs(usageOverviewStore)
const { logs, pause: pauseFeed, resume: resumeFeed } = useMonitoringFeed({
  initialCount: 6,
  maxEntries: 24,
})

const systemInfo = ref<SystemInfo | null>(null)
const systemInfoError = ref<string | null>(null)
const cliVersions = ref<Map<string, CliVersionEntry>>(new Map())
const cliVersionsLoaded = ref(false)
const isNativeRuntime = isTauriRuntime()

const CLI_PLATFORM_ALIASES: Record<string, string> = {
  claude: 'claude-code',
  'claude-code': 'claude-code',
  codex: 'codex',
  gemini: 'antigravity',
  agy: 'antigravity',
  antigravity: 'antigravity',
  'antigravity-cli': 'antigravity',
  'gemini-cli': 'antigravity',
  opencode: 'opencode',
  'open-code': 'opencode',
}

const normalizeDashboardCliPlatform = (platform: string) => {
  return CLI_PLATFORM_ALIASES[platform.trim().toLowerCase()] ?? null
}

const applyCliVersions = (entries: CliVersionEntry[]) => {
  const normalizedEntries = new Map<string, CliVersionEntry>()

  for (const entry of entries) {
    const platformKey = normalizeDashboardCliPlatform(entry.platform)
    if (!platformKey) continue

    normalizedEntries.set(platformKey, {
      ...entry,
      platform: platformKey,
    })
  }

  cliVersions.value = normalizedEntries
  cliVersionsLoaded.value = true
  perfMark('dashboard:cli-badges-updated')
}

const loadSystemInfo = async () => {
  try {
    systemInfo.value = await getSystemInfo()
    systemInfoError.value = null
    perfMark('dashboard:system-ready')
  } catch (error) {
    systemInfoError.value = getErrorMessage(error)
    logger.error('[DashboardView] failed to load system info', error)
  }
}

const loadCliVersions = async () => {
  try {
    cliVersionsLoaded.value = false
    const versions: CliVersionsResponse = await getCliVersions({
      mode: 'fast',
      timeoutMs: 3500,
      parallelism: 4,
    })
    applyCliVersions(versions.entries)
  } catch (error) {
    cliVersionsLoaded.value = true
    logger.error('[DashboardView] failed to load CLI versions', error)
  }
}

const loadUsageOverview = async (days: number) => {
  try {
    await usageOverviewStore.loadOverview(days)
    perfMark('dashboard:usage-overview-ready')
  } catch (error) {
    logger.error('[DashboardView] failed to load usage overview', error)
  }
}

let cancelDashboardDeferredTasks: (() => void) | null = null

const logDashboardPerfSnapshot = () => {
  if (!shouldLogPerfTelemetry() || typeof performance === 'undefined') return

  window.setTimeout(() => {
    const resources = performance.getEntriesByType('resource') as PerformanceResourceTiming[]
    const relevant = resources
      .filter((entry) =>
        entry.name.includes('get_system_info')
        || entry.name.includes('get_cli_versions')
        || entry.name.includes('get_home_usage_overview_v2'),
      )
      .map((entry) => ({
        name: entry.name,
        responseEnd: Math.round(entry.responseEnd),
        duration: Math.round(entry.duration),
      }))

    const badgeMarks = performance.getEntriesByName('dashboard:cli-badges-updated')
    const usageMarks = performance.getEntriesByName('dashboard:usage-overview-ready')

    logger.info('[Perf]', {
      scope: 'dashboard',
      apiResponses: relevant,
      cliBadgeUpdatedAt: badgeMarks.length > 0 ? Math.round(badgeMarks[badgeMarks.length - 1].startTime) : null,
      usageOverviewReadyAt: usageMarks.length > 0 ? Math.round(usageMarks[usageMarks.length - 1].startTime) : null,
    })
  }, 4500)
}

onMounted(() => {
  cancelDashboardDeferredTasks = scheduleWhenIdle(() => {
    if (!isNativeRuntime) {
      perfMark('dashboard:web-preview-ready')
      cliVersionsLoaded.value = true
      return
    }

    void loadSystemInfo()
    void loadCliVersions()
    void loadUsageOverview(activeDays.value)
  }, { timeout: 1400, fallbackDelay: 280 })
  logDashboardPerfSnapshot()
})

onBeforeUnmount(() => {
  cancelDashboardDeferredTasks?.()
  cancelDashboardDeferredTasks = null
  void usageOverviewStore.teardown()
})

// 本视图被 keep-alive 缓存：onBeforeUnmount 在导航离开时不触发，改由 deactivated 暂停
// 监控事件源、activated 恢复，避免切走后仍在后台持续合并事件。
onDeactivated(() => {
  pauseFeed()
})

onActivated(() => {
  resumeFeed()
})

const backendStatus = computed<DashboardBackendStatus>(() => {
  if (!isNativeRuntime) return 'unsupported'
  if (systemInfoError.value) return 'error'
  if (systemInfo.value) return 'ok'
  return 'checking'
})

const scrollToReadiness = () => {
  const target = document.querySelector('[data-dashboard-readiness]')
  const reduceMotion = typeof window.matchMedia === 'function'
    && window.matchMedia('(prefers-reduced-motion: reduce)').matches

  target?.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' })
}

const platforms = computed<DashboardPlatformSource[]>(() => [
  {
    title: t('dashboard.platforms.claudeTitle'),
    desc: t('dashboard.platforms.claudeDesc'),
    path: '/claude-code',
    icon: 'Code2',
    iconClass: 'text-platform-claude',
    platformKey: 'claude-code',
    usageKey: 'claude',
    role: t('dashboard.platforms.roleCoreCli'),
    mode: 'cli',
    isRuntimeCli: true,
  },
  {
    title: t('dashboard.platforms.codexTitle'),
    desc: t('dashboard.platforms.codexDesc'),
    path: '/codex',
    icon: 'Settings',
    iconClass: 'text-platform-codex',
    platformKey: 'codex',
    usageKey: 'codex',
    role: t('dashboard.platforms.roleCoreCli'),
    mode: 'cli',
    isRuntimeCli: true,
  },
  {
    title: t('dashboard.platforms.antigravityTitle'),
    desc: t('dashboard.platforms.antigravityDesc'),
    path: '/antigravity',
    icon: 'Sparkles',
    iconClass: 'text-platform-gemini',
    platformKey: 'antigravity',
    usageKey: 'gemini',
    role: t('dashboard.platforms.roleCoreCli'),
    mode: 'cli',
    isRuntimeCli: true,
  },
  {
    title: t('dashboard.platforms.opencodeTitle'),
    desc: t('dashboard.platforms.opencodeDesc'),
    path: '/opencode',
    icon: 'TerminalSquare',
    iconClass: 'text-accent-info',
    platformKey: 'opencode',
    usageKey: 'opencode',
    role: t('dashboard.platforms.roleManaged'),
    mode: 'managed',
    isRuntimeCli: false,
  },
])

const dashboardPresentation = computed(() => buildDashboardPresentation({
  backendStatus: backendStatus.value,
  isNativeRuntime,
  systemInfo: systemInfo.value,
  cliVersions: cliVersions.value,
  cliVersionsLoaded: cliVersionsLoaded.value,
  platforms: platforms.value,
  overview: overview.value,
  usageLoading: usageLoading.value,
  usageError: usageError.value,
  logs: logs.value,
}))
</script>

<style scoped>
.dashboard-view {
  min-height: 100%;
  color: var(--color-text-primary);
}

.dashboard-workbench {
  display: grid;
  gap: var(--home-section-gap);
  width: 100%;
  min-width: 0;
}

.dashboard-header {
  min-width: 0;
  padding-top: 0.25rem;
}

.dashboard-header__badge {
  display: inline-flex;
  flex-shrink: 0;
  align-items: center;
  gap: 0.45rem;
  padding: 0.35rem 0.75rem;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-full);
  background: var(--color-bg-elevated);
  color: var(--color-text-secondary);
  font-size: 0.8125rem;
  font-weight: 500;
  line-height: 1.24;
  letter-spacing: 0;
  cursor: pointer;
  transition:
    border-color var(--home-motion-duration) var(--home-motion-ease),
    background-color var(--home-motion-duration) var(--home-motion-ease),
    color var(--home-motion-duration) var(--home-motion-ease);
}

.dashboard-header__badge:hover {
  border-color: var(--color-border-strong);
  color: var(--color-text-primary);
}

.dashboard-header__badge:focus-visible {
  outline: 2px solid var(--color-accent-primary);
  outline-offset: 2px;
}

.dashboard-header__badge-dot {
  width: 0.45rem;
  height: 0.45rem;
  border-radius: 999px;
  background: var(--color-text-muted);
}

.dashboard-header__badge[data-status='ready'] {
  color: var(--color-success);
  background: rgb(var(--color-success-rgb) / 10%);
  border-color: rgb(var(--color-success-rgb) / 18%);
}

.dashboard-header__badge[data-status='ready'] .dashboard-header__badge-dot {
  background: var(--color-success);
}

.dashboard-header__badge[data-status='attention'] {
  color: var(--color-warning);
  background: rgb(var(--color-warning-rgb) / 10%);
  border-color: rgb(var(--color-warning-rgb) / 18%);
}

.dashboard-header__badge[data-status='attention'] .dashboard-header__badge-dot {
  background: var(--color-warning);
}

.dashboard-header__badge[data-status='warming'] .dashboard-header__badge-dot {
  background: var(--color-info);
}

.dashboard-header__badge[data-status='web-preview'] {
  color: var(--color-info);
  background: rgb(var(--color-info-rgb) / 10%);
  border-color: rgb(var(--color-info-rgb) / 18%);
}

.dashboard-header__badge[data-status='web-preview'] .dashboard-header__badge-dot {
  background: var(--color-info);
}

.dashboard-grid {
  display: grid;
  grid-template-columns: repeat(12, minmax(0, 1fr));
  gap: var(--home-section-gap-tight);
  align-items: stretch;
}

.dashboard-grid > * {
  min-width: 0;
}

.dashboard-grid__readiness,
.dashboard-grid__actions,
.dashboard-grid__entries {
  grid-column: 1 / -1;
}

.dashboard-grid__usage {
  grid-column: span 7;
}

.dashboard-grid__signals {
  grid-column: span 5;
}

@media (width <= 1180px) {
  .dashboard-grid__usage,
  .dashboard-grid__signals {
    grid-column: 1 / -1;
  }
}

@media (width <= 960px) {
  .dashboard-workbench {
    gap: var(--home-section-gap-tight);
  }
}
</style>
