// ccr-ui/src/components/mcp/McpDetailPanel.vue
<template>
  <div class="mcp-detail-panel">
    <div
      v-if="!group"
      class="mcp-detail-panel__empty"
    >
      <SIcon
        name="Server"
        size="w-8 h-8"
      />
      <p>{{ t('mcp.manager.detail.emptyTitle') }}</p>
      <span>{{ t('mcp.manager.detail.emptySubtitle') }}</span>
    </div>

    <template v-else-if="primaryServer">
      <div class="detail-header">
        <div class="detail-header__info">
          <div class="detail-header__icon">
            <SIcon
              :name="group.transportType === 'stdio' ? 'Terminal' : 'Globe'"
              size="w-5 h-5"
            />
          </div>
          <div>
            <p class="detail-header__eyebrow">
              {{ scopeLabel(primaryServer.scope ?? 'global') }} {{ t('mcp.manager.detail.scopeSuffix') }} · {{ stateLabel(primaryServer) }}
            </p>
            <h2 class="detail-header__title">
              {{ group.name }}
            </h2>
            <p class="detail-header__sub">
              {{ group.transportType.toUpperCase() }} · {{ t('mcp.manager.detail.instanceCount', { count: group.items.length }) }}
            </p>
          </div>
        </div>
        <div class="detail-header__actions">
          <button
            type="button"
            class="detail-btn"
            @click="$emit('edit', group.name)"
          >
            <SIcon
              name="Pencil"
              size="w-4 h-4"
            />
            <span>{{ t('common.edit') }}</span>
          </button>
          <button
            type="button"
            class="detail-btn detail-btn--danger"
            @click="$emit('delete', group)"
          >
            <SIcon
              name="Trash2"
              size="w-4 h-4"
            />
            <span>{{ t('common.delete') }}</span>
          </button>
        </div>
      </div>

      <section class="detail-section detail-section--effective">
        <div class="detail-section__heading">
          <h3 class="detail-section__title">
            {{ t('mcp.manager.detail.effectiveTitle') }}
          </h3>
          <span
            class="state-pill"
            :class="statePillClass(primaryServer)"
          >
            {{ stateLabel(primaryServer) }}
          </span>
        </div>
        <div class="detail-grid">
          <div class="detail-field">
            <span class="detail-field__label">{{ t('mcp.manager.detail.typeLabel') }}</span>
            <span class="detail-field__value">{{ group.transportType }}</span>
          </div>
          <div class="detail-field detail-field--wide">
            <span class="detail-field__label">
              {{ group.transportType === 'stdio' ? t('mcp.manager.detail.commandLabel') : t('mcp.manager.detail.urlLabel') }}
            </span>
            <span class="detail-field__value detail-field__value--mono">{{ group.transportLabel || '—' }}</span>
          </div>
          <div
            v-if="primaryServer.args?.length"
            class="detail-field detail-field--wide"
          >
            <span class="detail-field__label">{{ t('mcp.manager.detail.argsLabel') }}</span>
            <span class="detail-field__value detail-field__value--mono">{{ primaryServer.args.join(' ') }}</span>
          </div>
          <div
            v-if="primaryServer.timeout"
            class="detail-field"
          >
            <span class="detail-field__label">{{ t('mcp.manager.detail.timeoutLabel') }}</span>
            <span class="detail-field__value">{{ primaryServer.timeout }}ms</span>
          </div>
          <div
            v-if="primaryServer.cwd"
            class="detail-field detail-field--wide"
          >
            <span class="detail-field__label">{{ t('mcp.manager.detail.cwdLabel') }}</span>
            <span class="detail-field__value detail-field__value--mono">{{ primaryServer.cwd }}</span>
          </div>
        </div>
      </section>

      <section class="detail-section">
        <h3 class="detail-section__title">
          {{ t('mcp.manager.detail.precedenceTitle') }}
        </h3>
        <div class="precedence-stack">
          <div
            v-for="item in precedenceItems"
            :key="`${item.platform}-${item.scope ?? 'global'}-${item.name}`"
            class="precedence-row"
            :class="{ 'precedence-row--active': item.effective !== false && !item.hidden_by }"
          >
            <span class="precedence-row__dot" />
            <div class="precedence-row__body">
              <strong>{{ scopeLabel(item.scope ?? item.platform) }}</strong>
              <span>{{ item.source_path ?? t('mcp.manager.detail.sourceUnavailable') }}</span>
              <em v-if="item.hidden_by">{{ t('mcp.manager.detail.hiddenBy', { hiddenBy: item.hidden_by }) }}</em>
              <em v-else-if="item.approval_state">{{ t('mcp.manager.detail.approvalState', { state: approvalLabel(item.approval_state) }) }}</em>
            </div>
            <span
              class="state-pill"
              :class="statePillClass(item)"
            >
              {{ stateLabel(item) }}
            </span>
          </div>
        </div>
      </section>

      <section
        v-if="hasEnvVars || hasHeaders"
        class="detail-section"
      >
        <h3 class="detail-section__title">
          {{ t('mcp.manager.detail.envHeadersTitle') }}
        </h3>
        <div
          v-if="hasEnvVars"
          class="detail-kv-list"
        >
          <div
            v-for="(value, key) in primaryServer.env"
            :key="key"
            class="detail-kv"
          >
            <span class="detail-kv__key">{{ key }}</span>
            <span class="detail-kv__value">{{ maskValue(String(value)) }}</span>
          </div>
        </div>
        <div
          v-if="hasHeaders"
          class="detail-kv-list"
        >
          <div
            v-for="(value, key) in primaryServer.headers"
            :key="key"
            class="detail-kv"
          >
            <span class="detail-kv__key">{{ key }}</span>
            <span class="detail-kv__value">{{ maskValue(String(value)) }}</span>
          </div>
        </div>
      </section>

      <section class="detail-section">
        <h3 class="detail-section__title">
          {{ t('mcp.manager.detail.rawConfigTitle') }}
        </h3>
        <pre class="raw-config-preview">{{ rawConfigPreview }}</pre>
      </section>

      <section class="detail-section">
        <h3 class="detail-section__title">
          {{ t('mcp.manager.detail.instancesTitle') }}
        </h3>
        <div class="detail-agent-list">
          <div
            v-for="item in group.items"
            :key="`${item.platform}-${item.scope ?? 'global'}-${item.name}-instance`"
            class="detail-agent-row"
          >
            <AgentIcons
              :agents="[item.platform]"
              :compact="false"
            />
            <span class="detail-agent-scope">{{ scopeLabel(item.scope ?? 'global') }}</span>
            <span
              class="detail-agent-status"
              :class="item.disabled ? 'detail-agent-status--disabled' : 'detail-agent-status--active'"
            >
              {{ item.disabled ? t('mcp.manager.state.disabled') : t('mcp.manager.state.enabled') }}
            </span>
            <button
              type="button"
              class="detail-btn detail-btn--sm"
              @click="$emit('toggle', item)"
            >
              <SIcon
                :name="item.disabled ? 'ToggleLeft' : 'ToggleRight'"
                size="w-4 h-4"
              />
            </button>
          </div>
        </div>
      </section>

      <section
        v-if="diagnostics.length"
        class="detail-section detail-section--diagnostics"
      >
        <h3 class="detail-section__title">
          {{ t('mcp.manager.detail.diagnosticsTitle') }}
        </h3>
        <div class="diagnostic-list">
          <div
            v-for="(diagnostic, index) in diagnostics"
            :key="`${diagnostic.source_path ?? 'diagnostic'}-${index}`"
            class="diagnostic-row"
          >
            <span class="diagnostic-row__level">{{ diagnostic.level }}</span>
            <span>{{ diagnostic.message }}</span>
          </div>
        </div>
      </section>
    </template>

    <div
      v-else
      class="mcp-detail-panel__empty"
    >
      <SIcon
        name="AlertCircle"
        size="w-8 h-8"
      />
      <p>{{ t('mcp.manager.detail.noReadableInstance') }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import AgentIcons from '@/components/common/AgentIcons.vue'
import SIcon from '@/components/ui/SIcon.vue'
import type { McpGroup } from '@/types/mcpManager'
import type { UnifiedMcpDiagnostic, UnifiedMcpServer } from '@/types/unifiedMcp'

const props = defineProps<{
  group: McpGroup | null
  diagnostics?: UnifiedMcpDiagnostic[]
}>()

const { t } = useI18n({ useScope: 'global' })

defineEmits<{
  edit: [groupName: string]
  delete: [group: McpGroup]
  toggle: [server: UnifiedMcpServer]
}>()

const primaryServer = computed(() =>
  props.group?.items.find(item => item.effective !== false && !item.hidden_by)
  ?? props.group?.items[0]
  ?? null,
)

const diagnostics = computed(() => props.diagnostics ?? [])

const precedenceItems = computed(() => {
  const items = props.group?.items ?? []
  const order = { local: 0, project: 1, user: 2 } as Record<string, number>
  return [...items].sort((a, b) => {
    const aOrder = order[String(a.scope)] ?? 9
    const bOrder = order[String(b.scope)] ?? 9
    if (aOrder !== bOrder) return aOrder - bOrder
    return String(a.platform).localeCompare(String(b.platform))
  })
})

const rawConfigPreview = computed(() => {
  const raw = primaryServer.value?.raw_config
  if (raw && typeof raw === 'object') {
    return JSON.stringify(raw, null, 2)
  }

  return JSON.stringify(
    {
      command: primaryServer.value?.command ?? undefined,
      url: primaryServer.value?.url ?? undefined,
      args: primaryServer.value?.args,
      env: primaryServer.value?.env,
      headers: primaryServer.value?.headers,
      disabled: primaryServer.value?.disabled,
    },
    null,
    2,
  )
})

const hasEnvVars = computed(() => {
  const env = primaryServer.value?.env
  return env && Object.keys(env).length > 0
})

const hasHeaders = computed(() => {
  const headers = primaryServer.value?.headers
  return headers && Object.keys(headers).length > 0
})

function stateLabel(server: UnifiedMcpServer): string {
  if (server.hidden_by) return t('mcp.manager.state.overridden')
  if (server.disabled) return t('mcp.manager.state.disabled')
  if (server.approval_state === 'pending') return t('mcp.manager.state.pending')
  if (server.approval_state === 'disabled') return t('mcp.manager.state.notApproved')
  if (server.effective === false) return t('mcp.manager.state.hidden')
  return t('mcp.manager.state.effective')
}

function statePillClass(server: UnifiedMcpServer): string {
  if (server.hidden_by || server.effective === false) return 'state-pill--muted'
  if (server.disabled || server.approval_state === 'disabled') return 'state-pill--danger'
  if (server.approval_state === 'pending') return 'state-pill--warning'
  return 'state-pill--ok'
}

function scopeLabel(scope: string): string {
  const key = `mcp.manager.scopes.${scope}`
  const label = t(key)
  return label === key ? scope : label
}

function approvalLabel(state: string): string {
  const key = `mcp.manager.approvals.${state}`
  const label = t(key)
  return label === key ? state : label
}

function maskValue(value: string): string {
  if (!value) return ''
  if (value.includes('•')) return value
  if (value.length <= 8) return '••••••'
  return `${value.slice(0, 4)}••••${value.slice(-2)}`
}
</script>

<style scoped>
.mcp-detail-panel {
  height: 100%;
  overflow-y: auto;
  padding: 1.6rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.mcp-detail-panel__empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.6rem;
  height: 100%;
  color: var(--color-text-muted);
  text-align: center;
}

.mcp-detail-panel__empty p {
  color: var(--color-text-primary);
  font-weight: 700;
}

.mcp-detail-panel__empty span {
  font-size: 0.8rem;
}

.detail-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 1rem;
  padding-bottom: 0.45rem;
}

.detail-header__info {
  display: flex;
  align-items: center;
  gap: 0.9rem;
}

.detail-header__icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2.8rem;
  height: 2.8rem;
  border: 1px solid rgb(var(--color-accent-primary-rgb) / 22%);
  border-radius: 0.9rem;
  background: rgb(var(--color-accent-primary-rgb) / 9%);
  color: rgb(var(--color-accent-primary-rgb));
  flex-shrink: 0;
}

.detail-header__eyebrow {
  color: rgb(var(--color-accent-primary-rgb) / 88%);
  font-size: 0.64rem;
  font-weight: 750;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

.detail-header__title {
  margin-top: 0.1rem;
  color: var(--color-text-primary);
  font-family: Georgia, 'Times New Roman', var(--font-sans);
  font-size: 1.55rem;
  line-height: 1.1;
  letter-spacing: -0.035em;
}

.detail-header__sub {
  color: var(--color-text-muted);
  font-size: 0.76rem;
  margin-top: 0.25rem;
}

.detail-header__actions {
  display: flex;
  gap: 0.5rem;
  flex-shrink: 0;
}

.detail-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.42rem 0.78rem;
  border-radius: 999px;
  font-size: 0.78rem;
  font-weight: 650;
  border: 1px solid var(--surface-status-border, rgb(var(--color-border-default-rgb) / 55%));
  background: var(--surface-status-bg);
  color: var(--color-text-secondary);
  cursor: pointer;
  transition:
    color var(--motion-subtle-duration) var(--motion-subtle-ease),
    background-color var(--motion-subtle-duration) var(--motion-subtle-ease),
    border-color var(--motion-subtle-duration) var(--motion-subtle-ease);
}

.detail-btn:hover {
  color: var(--color-text-primary);
  background: var(--surface-card-bg);
}

.detail-btn--danger {
  color: rgb(var(--color-danger-rgb) / 85%);
}

.detail-btn--danger:hover {
  border-color: rgb(var(--color-danger-rgb) / 22%);
  background: rgb(var(--color-danger-rgb) / 8%);
  color: rgb(var(--color-danger-rgb));
}

.detail-btn--sm {
  padding: 0.28rem 0.55rem;
}

.detail-section {
  padding: 1rem;
  border: 1px solid var(--surface-card-border);
  border-radius: 1rem;
  background: var(--surface-card-bg);
  box-shadow: var(--surface-card-shadow);
}

.detail-section--effective {
  background: var(--surface-card-bg);
}

.detail-section__heading {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
  margin-bottom: 0.75rem;
}

.detail-section__title {
  color: var(--color-text-muted);
  font-size: 0.68rem;
  font-weight: 750;
  letter-spacing: 0.13em;
  text-transform: uppercase;
}

.detail-grid {
  display: grid;
  gap: 0.85rem;
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.detail-field--wide {
  grid-column: 1 / -1;
}

.detail-field__label {
  display: block;
  margin-bottom: 0.24rem;
  color: var(--color-text-muted);
  font-size: 0.65rem;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}

.detail-field__value {
  color: var(--color-text-primary);
  font-size: 0.82rem;
  word-break: break-all;
}

.detail-field__value--mono,
.detail-kv__key,
.detail-kv__value {
  font-family: var(--font-mono);
  font-size: 0.74rem;
}

.precedence-stack,
.detail-kv-list,
.detail-agent-list,
.diagnostic-list {
  display: flex;
  flex-direction: column;
  gap: 0.45rem;
}

.precedence-row,
.detail-agent-row,
.detail-kv,
.diagnostic-row {
  display: flex;
  align-items: center;
  gap: 0.7rem;
  border: 1px solid rgb(var(--color-border-default-rgb) / 28%);
  border-radius: 0.75rem;
  background: rgb(var(--color-bg-base-rgb) / 38%);
  padding: 0.55rem 0.65rem;
}

.precedence-row--active {
  border-color: rgb(var(--color-success-rgb) / 24%);
  background: rgb(var(--color-success-rgb) / 6%);
}

.precedence-row__dot {
  width: 0.46rem;
  height: 0.46rem;
  border-radius: 999px;
  background: rgb(var(--color-border-default-rgb) / 80%);
}

.precedence-row--active .precedence-row__dot {
  background: rgb(var(--color-success-rgb));
}

.precedence-row__body {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 0.12rem;
}

.precedence-row__body strong,
.detail-agent-scope {
  color: var(--color-text-primary);
  font-size: 0.78rem;
  font-weight: 720;
  text-transform: capitalize;
}

.precedence-row__body span,
.precedence-row__body em {
  overflow: hidden;
  color: var(--color-text-muted);
  font-family: var(--font-mono);
  font-size: 0.68rem;
  font-style: normal;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.state-pill {
  flex-shrink: 0;
  border: 1px solid transparent;
  border-radius: 999px;
  padding: 0.15rem 0.48rem;
  font-size: 0.62rem;
  font-weight: 800;
  letter-spacing: 0.07em;
  text-transform: uppercase;
}

.state-pill--ok {
  border-color: rgb(var(--color-success-rgb) / 24%);
  background: rgb(var(--color-success-rgb) / 10%);
  color: rgb(var(--color-success-rgb));
}

.state-pill--warning {
  border-color: rgb(var(--color-warning-rgb) / 26%);
  background: rgb(var(--color-warning-rgb) / 10%);
  color: rgb(var(--color-warning-rgb));
}

.state-pill--danger {
  border-color: rgb(var(--color-danger-rgb) / 24%);
  background: rgb(var(--color-danger-rgb) / 9%);
  color: rgb(var(--color-danger-rgb));
}

.state-pill--muted {
  border-color: rgb(var(--color-border-default-rgb) / 34%);
  background: rgb(var(--color-bg-elevated-rgb) / 44%);
  color: var(--color-text-muted);
}

.detail-kv {
  justify-content: space-between;
}

.detail-kv__key {
  color: var(--color-text-primary);
  font-weight: 700;
}

.detail-kv__value {
  color: var(--color-text-muted);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.detail-agent-status {
  margin-left: auto;
  font-size: 0.68rem;
  font-weight: 750;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.detail-agent-status--active {
  color: rgb(var(--color-success-rgb));
}

.detail-agent-status--disabled {
  color: var(--color-text-muted);
}

.diagnostic-row {
  align-items: baseline;
  color: var(--color-text-secondary);
  font-size: 0.76rem;
}

.diagnostic-row__level {
  color: rgb(var(--color-accent-primary-rgb) / 90%);
  font-size: 0.64rem;
  font-weight: 800;
  letter-spacing: 0.09em;
  text-transform: uppercase;
}

.raw-config-preview {
  overflow-x: auto;
  border: 1px solid rgb(var(--color-border-default-rgb) / 28%);
  border-radius: 0.75rem;
  background: rgb(var(--color-bg-base-rgb) / 42%);
  color: var(--color-text-secondary);
  font-family: var(--font-mono);
  font-size: 0.72rem;
  line-height: 1.55;
  padding: 0.75rem;
  white-space: pre-wrap;
}

@media (width <= 860px) {
  .detail-header {
    flex-direction: column;
  }

  .detail-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// ccr-ui/src/features/platform/mcp/McpDetailPanel.tsx
import { memo, useCallback } from 'react'
import type { McpGroup } from '@/types/mcpManager'
import type { UnifiedMcpDiagnostic, UnifiedMcpServer } from '@/types/unifiedMcp'
import type { TranslateFunction } from '@/utils/tf'
import { AgentIcons, SIcon, cn } from '@/ui'
import { buildRawConfigPreview, pickPrimaryServer, sortPrecedence } from './mcp-detail-model'
import {
  MCP_STATE_TONE_CLASS,
  maskSecret,
  mcpApprovalLabel,
  mcpScopeLabel,
  mcpStateLabel,
  mcpStateTone,
} from './mcp-format'

export interface McpDetailPanelProps {
  group: McpGroup | null
  diagnostics?: UnifiedMcpDiagnostic[]
  t: TranslateFunction
  onEdit: (groupName: string) => void
  onDelete: (group: McpGroup) => void
  onToggle: (server: UnifiedMcpServer) => void
}

interface McpInstanceRowProps {
  item: UnifiedMcpServer
  onToggle: (server: UnifiedMcpServer) => void
  t: TranslateFunction
}

const McpInstanceRow = memo(function McpInstanceRow({ item, onToggle, t }: McpInstanceRowProps) {
  const handleToggle = useCallback(() => {
    onToggle(item)
  }, [item, onToggle])

  return (
    <div className="flex items-center gap-3 rounded-xl border border-border-default/28 bg-bg-base/38 px-2.5 py-2">
      <AgentIcons agents={[item.platform]} compact={false} />
      <span className="text-sm font-semibold capitalize text-text-primary">
        {mcpScopeLabel(item.scope ?? 'global', t)}
      </span>
      <span
        className={cn(
          'ml-auto text-xs font-bold uppercase tracking-wide',
          item.disabled ? 'text-text-muted' : 'text-success',
        )}
      >
        {item.disabled ? t('mcp.manager.state.disabled') : t('mcp.manager.state.enabled')}
      </span>
      <button
        type="button"
        className="inline-flex items-center gap-1.5 rounded-full border border-border-default/55 bg-bg-elevated px-2 py-1 text-text-secondary hover:bg-bg-surface hover:text-text-primary"
        aria-label={`${item.platform}:${item.name}`}
        onClick={handleToggle}
      >
        <SIcon name={item.disabled ? 'ToggleLeft' : 'ToggleRight'} size="w-4 h-4" />
      </button>
    </div>
  )
})

function DetailEmpty({ icon, title, subtitle }: { icon: string; title: string; subtitle?: string }) {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-2.5 text-center text-text-muted">
      <SIcon name={icon} size="w-8 h-8" />
      <p className="font-bold text-text-primary">{title}</p>
      {subtitle ? <span className="text-sm">{subtitle}</span> : null}
    </div>
  )
}

function StatePill({ server, t }: { server: UnifiedMcpServer; t: TranslateFunction }) {
  return (
    <span
      className={cn(
        'shrink-0 rounded-full border px-2 py-0.5 text-[0.62rem] font-extrabold uppercase tracking-wide',
        MCP_STATE_TONE_CLASS[mcpStateTone(server)],
      )}
    >
      {mcpStateLabel(server, t)}
    </span>
  )
}

interface McpDetailBodyProps {
  group: McpGroup
  primaryServer: UnifiedMcpServer
  diagnostics: UnifiedMcpDiagnostic[]
  t: TranslateFunction
  onEdit: (groupName: string) => void
  onDelete: (group: McpGroup) => void
  onToggle: (server: UnifiedMcpServer) => void
}

function McpDetailBody({
  group,
  primaryServer,
  diagnostics,
  t,
  onEdit,
  onDelete,
  onToggle,
}: McpDetailBodyProps) {
  const handleEdit = useCallback(() => {
    onEdit(group.name)
  }, [group.name, onEdit])

  const handleDelete = useCallback(() => {
    onDelete(group)
  }, [group, onDelete])

  const envEntries = Object.entries(primaryServer.env ?? {})
  const headerEntries = Object.entries(primaryServer.headers ?? {})
  const precedenceItems = sortPrecedence(group.items)
  const commandOrUrl =
    group.transportType === 'stdio' ? t('mcp.manager.detail.commandLabel') : t('mcp.manager.detail.urlLabel')

  return (
    <div className="flex h-full flex-col gap-4 overflow-y-auto p-6">
      <div className="flex items-start justify-between gap-4 pb-2 max-[53.75rem]:flex-col">
        <div className="flex items-center gap-3.5">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-accent-primary/22 bg-accent-primary/10 text-accent-primary">
            <SIcon name={group.transportType === 'stdio' ? 'Terminal' : 'Globe'} size="w-5 h-5" />
          </div>
          <div>
            <p className="text-[0.64rem] font-bold uppercase tracking-[0.14em] text-accent-primary/88">
              {mcpScopeLabel(primaryServer.scope ?? 'global', t)} {t('mcp.manager.detail.scopeSuffix')} ·{' '}
              {mcpStateLabel(primaryServer, t)}
            </p>
            <h2 className="mt-0.5 font-serif text-[1.55rem] leading-tight tracking-tight text-text-primary">
              {group.name}
            </h2>
            <p className="mt-1 text-xs text-text-muted">
              {group.transportType.toUpperCase()} · {t('mcp.manager.detail.instanceCount', { count: group.items.length })}
            </p>
          </div>
        </div>
        <div className="flex shrink-0 gap-2">
          <button
            type="button"
            className="inline-flex items-center gap-1.5 rounded-full border border-border-default/55 bg-bg-elevated px-3 py-1.5 text-sm font-semibold text-text-secondary hover:bg-bg-surface hover:text-text-primary"
            onClick={handleEdit}
          >
            <SIcon name="Pencil" size="w-4 h-4" />
            <span>{t('common.edit')}</span>
          </button>
          <button
            type="button"
            className="inline-flex items-center gap-1.5 rounded-full border border-border-default/55 bg-bg-elevated px-3 py-1.5 text-sm font-semibold text-danger/85 hover:border-danger/22 hover:bg-danger/8 hover:text-danger"
            onClick={handleDelete}
          >
            <SIcon name="Trash2" size="w-4 h-4" />
            <span>{t('common.delete')}</span>
          </button>
        </div>
      </div>

      <section className="rounded-2xl border border-border-default/40 bg-bg-surface p-4 shadow-sm">
        <div className="mb-3 flex items-center justify-between gap-3">
          <h3 className="text-[0.68rem] font-bold uppercase tracking-[0.13em] text-text-muted">
            {t('mcp.manager.detail.effectiveTitle')}
          </h3>
          <StatePill server={primaryServer} t={t} />
        </div>
        <div className="grid grid-cols-2 gap-3.5 max-[53.75rem]:grid-cols-1">
          <div>
            <span className="mb-1 block text-[0.65rem] font-bold uppercase tracking-widest text-text-muted">
              {t('mcp.manager.detail.typeLabel')}
            </span>
            <span className="break-all text-sm text-text-primary">{group.transportType}</span>
          </div>
          <div className="col-span-full">
            <span className="mb-1 block text-[0.65rem] font-bold uppercase tracking-widest text-text-muted">
              {commandOrUrl}
            </span>
            <span className="break-all font-mono text-xs text-text-primary">{group.transportLabel || '—'}</span>
          </div>
          {primaryServer.args?.length ? (
            <div className="col-span-full">
              <span className="mb-1 block text-[0.65rem] font-bold uppercase tracking-widest text-text-muted">
                {t('mcp.manager.detail.argsLabel')}
              </span>
              <span className="break-all font-mono text-xs text-text-primary">{primaryServer.args.join(' ')}</span>
            </div>
          ) : null}
          {primaryServer.timeout ? (
            <div>
              <span className="mb-1 block text-[0.65rem] font-bold uppercase tracking-widest text-text-muted">
                {t('mcp.manager.detail.timeoutLabel')}
              </span>
              <span className="text-sm text-text-primary">{primaryServer.timeout}ms</span>
            </div>
          ) : null}
          {primaryServer.cwd ? (
            <div className="col-span-full">
              <span className="mb-1 block text-[0.65rem] font-bold uppercase tracking-widest text-text-muted">
                {t('mcp.manager.detail.cwdLabel')}
              </span>
              <span className="break-all font-mono text-xs text-text-primary">{primaryServer.cwd}</span>
            </div>
          ) : null}
        </div>
      </section>

      <section className="rounded-2xl border border-border-default/40 bg-bg-surface p-4 shadow-sm">
        <h3 className="mb-3 text-[0.68rem] font-bold uppercase tracking-[0.13em] text-text-muted">
          {t('mcp.manager.detail.precedenceTitle')}
        </h3>
        <div className="flex flex-col gap-1.5">
          {precedenceItems.map((item) => {
            const active = item.effective !== false && !item.hidden_by
            return (
              <div
                key={`${item.platform}-${item.scope ?? 'global'}-${item.name}`}
                className={cn(
                  'flex items-center gap-3 rounded-xl border px-2.5 py-2',
                  active
                    ? 'border-success/24 bg-success/10'
                    : 'border-border-default/28 bg-bg-base/38',
                )}
              >
                <span className={cn('h-2 w-2 rounded-full', active ? 'bg-success' : 'bg-border-default/80')} />
                <div className="flex min-w-0 flex-1 flex-col gap-0.5">
                  <strong className="text-sm font-semibold capitalize text-text-primary">
                    {mcpScopeLabel(item.scope ?? item.platform, t)}
                  </strong>
                  <span className="overflow-hidden text-ellipsis whitespace-nowrap font-mono text-[0.68rem] text-text-muted">
                    {item.source_path ?? t('mcp.manager.detail.sourceUnavailable')}
                  </span>
                  {item.hidden_by ? (
                    <em className="overflow-hidden text-ellipsis whitespace-nowrap font-mono text-[0.68rem] not-italic text-text-muted">
                      {t('mcp.manager.detail.hiddenBy', { hiddenBy: item.hidden_by })}
                    </em>
                  ) : null}
                  {!item.hidden_by && item.approval_state ? (
                    <em className="overflow-hidden text-ellipsis whitespace-nowrap font-mono text-[0.68rem] not-italic text-text-muted">
                      {t('mcp.manager.detail.approvalState', { state: mcpApprovalLabel(item.approval_state, t) })}
                    </em>
                  ) : null}
                </div>
                <StatePill server={item} t={t} />
              </div>
            )
          })}
        </div>
      </section>

      {envEntries.length > 0 || headerEntries.length > 0 ? (
        <section className="rounded-2xl border border-border-default/40 bg-bg-surface p-4 shadow-sm">
          <h3 className="mb-3 text-[0.68rem] font-bold uppercase tracking-[0.13em] text-text-muted">
            {t('mcp.manager.detail.envHeadersTitle')}
          </h3>
          <div className="flex flex-col gap-1.5">
            {envEntries.map(([key, value]) => (
              <div
                key={`env-${key}`}
                className="flex items-center justify-between gap-3 rounded-xl border border-border-default/28 bg-bg-base/38 px-2.5 py-2"
              >
                <span className="font-mono text-xs font-bold text-text-primary">{key}</span>
                <span className="overflow-hidden text-ellipsis whitespace-nowrap font-mono text-xs text-text-muted">
                  {maskSecret(String(value))}
                </span>
              </div>
            ))}
            {headerEntries.map(([key, value]) => (
              <div
                key={`header-${key}`}
                className="flex items-center justify-between gap-3 rounded-xl border border-border-default/28 bg-bg-base/38 px-2.5 py-2"
              >
                <span className="font-mono text-xs font-bold text-text-primary">{key}</span>
                <span className="overflow-hidden text-ellipsis whitespace-nowrap font-mono text-xs text-text-muted">
                  {maskSecret(String(value))}
                </span>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      <section className="rounded-2xl border border-border-default/40 bg-bg-surface p-4 shadow-sm">
        <h3 className="mb-3 text-[0.68rem] font-bold uppercase tracking-[0.13em] text-text-muted">
          {t('mcp.manager.detail.rawConfigTitle')}
        </h3>
        <pre className="overflow-x-auto whitespace-pre-wrap rounded-xl border border-border-default/28 bg-bg-base/42 p-3 font-mono text-xs leading-relaxed text-text-secondary">
          {buildRawConfigPreview(primaryServer)}
        </pre>
      </section>

      <section className="rounded-2xl border border-border-default/40 bg-bg-surface p-4 shadow-sm">
        <h3 className="mb-3 text-[0.68rem] font-bold uppercase tracking-[0.13em] text-text-muted">
          {t('mcp.manager.detail.instancesTitle')}
        </h3>
        <div className="flex flex-col gap-1.5">
          {group.items.map((item) => (
            <McpInstanceRow
              key={`${item.platform}-${item.scope ?? 'global'}-${item.name}-instance`}
              item={item}
              onToggle={onToggle}
              t={t}
            />
          ))}
        </div>
      </section>

      {diagnostics.length > 0 ? (
        <section className="rounded-2xl border border-border-default/40 bg-bg-surface p-4 shadow-sm">
          <h3 className="mb-3 text-[0.68rem] font-bold uppercase tracking-[0.13em] text-text-muted">
            {t('mcp.manager.detail.diagnosticsTitle')}
          </h3>
          <div className="flex flex-col gap-1.5">
            {diagnostics.map((diagnostic) => (
              <div
                key={`${diagnostic.source_path ?? 'diagnostic'}-${diagnostic.level}-${diagnostic.message}`}
                className="flex items-baseline gap-3 rounded-xl border border-border-default/28 bg-bg-base/38 px-2.5 py-2 text-sm text-text-secondary"
              >
                <span className="text-[0.64rem] font-extrabold uppercase tracking-wide text-accent-primary/90">
                  {diagnostic.level}
                </span>
                <span>{diagnostic.message}</span>
              </div>
            ))}
          </div>
        </section>
      ) : null}
    </div>
  )
}

export function McpDetailPanel({
  group,
  diagnostics = [],
  t,
  onEdit,
  onDelete,
  onToggle,
}: McpDetailPanelProps) {
  const primaryServer = pickPrimaryServer(group)

  if (!group) {
    return (
      <div className="flex h-full flex-col gap-4 overflow-y-auto p-6">
        <DetailEmpty
          icon="Server"
          title={t('mcp.manager.detail.emptyTitle')}
          subtitle={t('mcp.manager.detail.emptySubtitle')}
        />
      </div>
    )
  }

  if (!primaryServer) {
    return (
      <div className="flex h-full flex-col gap-4 overflow-y-auto p-6">
        <DetailEmpty icon="AlertCircle" title={t('mcp.manager.detail.noReadableInstance')} />
      </div>
    )
  }

  return (
    <McpDetailBody
      group={group}
      primaryServer={primaryServer}
      diagnostics={diagnostics}
      t={t}
      onEdit={onEdit}
      onDelete={onDelete}
      onToggle={onToggle}
    />
  )
}
