// ccr-ui/src/components/claude-observer/SubscriptionDialog.vue
<template>
  <BaseModal
    :model-value="modelValue"
    :title="$t('claudeCode.observer.subscription.dialogTitle')"
    size="sm"
    @update:model-value="onUpdateModelValue"
    @close="$emit('update:modelValue', false)"
  >
    <div class="subscription-dialog">
      <!-- 步骤 1：模式（auto / api_key / subscription） -->
      <label class="subscription-dialog__field">
        <span class="subscription-dialog__label">
          {{ $t('claudeCode.observer.subscription.fieldMode') }}
        </span>
        <select
          v-model="form.mode"
          class="subscription-dialog__control"
        >
          <option value="auto">
            {{ $t('claudeCode.observer.subscription.modeAuto') }}
          </option>
          <option value="api_key">
            {{ $t('claudeCode.observer.subscription.modeApiKey') }}
          </option>
          <option value="subscription">
            {{ $t('claudeCode.observer.subscription.modeSubscription') }}
          </option>
        </select>
      </label>

      <!-- 步骤 2：套餐 -->
      <label class="subscription-dialog__field">
        <span class="subscription-dialog__label">
          {{ $t('claudeCode.observer.subscription.fieldPlan') }}
        </span>
        <select
          v-model="form.plan"
          class="subscription-dialog__control"
          :disabled="form.mode !== 'subscription'"
        >
          <option value="free_pro">
            {{ $t('claudeCode.observer.subscription.planFreePro') }}
          </option>
          <option value="max5x">
            {{ $t('claudeCode.observer.subscription.planMax5x') }}
          </option>
          <option value="max20x">
            {{ $t('claudeCode.observer.subscription.planMax20x') }}
          </option>
          <option value="team">
            {{ $t('claudeCode.observer.subscription.planTeam') }}
          </option>
          <option value="enterprise">
            {{ $t('claudeCode.observer.subscription.planEnterprise') }}
          </option>
          <option value="custom">
            {{ $t('claudeCode.observer.subscription.planCustom') }}
          </option>
        </select>
      </label>

      <!-- 步骤 3：月费（美元） -->
      <label class="subscription-dialog__field">
        <span class="subscription-dialog__label">
          {{ $t('claudeCode.observer.subscription.fieldMonthlyUsd') }}
        </span>
        <input
          v-model.number="form.monthly_usd"
          type="number"
          min="0"
          step="1"
          class="subscription-dialog__control"
          :disabled="form.mode !== 'subscription'"
        >
      </label>

      <p
        v-if="error"
        class="subscription-dialog__error"
      >
        {{ error }}
      </p>
    </div>

    <template #footer>
      <div class="subscription-dialog__actions">
        <button
          type="button"
          class="subscription-dialog__btn subscription-dialog__btn--ghost"
          :disabled="saving"
          @click="$emit('update:modelValue', false)"
        >
          {{ $t('common.cancel') }}
        </button>
        <button
          type="button"
          class="subscription-dialog__btn subscription-dialog__btn--primary"
          :disabled="saving"
          @click="onSave"
        >
          {{ saving
            ? $t('claudeCode.observer.subscription.saving')
            : $t('common.save') }}
        </button>
      </div>
    </template>
  </BaseModal>
</template>

<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { getErrorMessage } from '@/utils/errorHandler'
import BaseModal from '@/components/common/BaseModal.vue'
import { useClaudeObserverStore } from '@/stores/claudeObserver'
import type { SubscriptionDto } from '@/types/claudeObserver'

interface Props {
  modelValue: boolean
  current: SubscriptionDto | null
}

const props = defineProps<Props>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  'saved': []
}>()

const store = useClaudeObserverStore()

/*
 * ========================================================================
 * 表单状态
 * ========================================================================
 * 1) 打开时由 props.current 初始化
 * 2) 保存时调用 store.updateSubscription()
 */
const form = reactive({
  mode: 'auto',
  plan: 'free_pro',
  monthly_usd: 0,
})

const saving = ref(false)
const error = ref<string | null>(null)

const syncForm = (next: SubscriptionDto | null) => {
  form.mode = next?.mode ?? 'auto'
  form.plan = next?.plan ?? 'free_pro'
  form.monthly_usd = next?.monthly_usd ?? 0
}

watch(
  () => props.current,
  (next) => syncForm(next),
  { immediate: true },
)

watch(
  () => props.modelValue,
  (open) => {
    // 1.1 打开时刷新表单初值，关闭时清错
    if (open) {
      syncForm(props.current)
      error.value = null
    }
  },
)

const onUpdateModelValue = (value: boolean) => {
  emit('update:modelValue', value)
}

const onSave = async () => {
  saving.value = true
  error.value = null
  try {
    await store.updateSubscription({
      mode: form.mode,
      plan: form.plan,
      monthly_usd: Number.isFinite(form.monthly_usd) ? form.monthly_usd : 0,
    })
    emit('saved')
    emit('update:modelValue', false)
  } catch (err) {
    error.value = getErrorMessage(err)
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.subscription-dialog {
  display: grid;
  gap: 0.9rem;
}

.subscription-dialog__field {
  display: grid;
  gap: 0.35rem;
}

.subscription-dialog__label {
  color: var(--color-text-secondary);
  font-size: 0.78rem;
  font-weight: 600;
  letter-spacing: 0.04em;
}

.subscription-dialog__control {
  width: 100%;
  border-radius: 0.65rem;
  border: 1px solid var(--color-border-default);
  background: var(--surface-card-bg);
  color: var(--color-text-primary);
  padding: 0.55rem 0.75rem;
  font-size: 0.88rem;
  transition: border-color var(--motion-subtle-duration) var(--motion-subtle-ease);
}

.subscription-dialog__control:focus-visible {
  outline: none;
  border-color: rgb(var(--color-accent-primary-rgb) / 55%);
  box-shadow: 0 0 0 3px rgb(var(--color-accent-primary-rgb) / 12%);
}

.subscription-dialog__control:disabled {
  opacity: 0.55;
}

.subscription-dialog__error {
  margin: 0;
  color: var(--color-danger);
  font-size: 0.78rem;
}

.subscription-dialog__actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.6rem;
}

.subscription-dialog__btn {
  min-width: 5rem;
  border-radius: 0.65rem;
  padding: 0.55rem 0.95rem;
  font-size: 0.84rem;
  font-weight: 600;
  transition: background-color var(--motion-subtle-duration) var(--motion-subtle-ease),
    border-color var(--motion-subtle-duration) var(--motion-subtle-ease);
}

.subscription-dialog__btn--ghost {
  border: 1px solid var(--color-border-default);
  background: transparent;
  color: var(--color-text-secondary);
}

.subscription-dialog__btn--ghost:hover {
  color: var(--color-text-primary);
}

.subscription-dialog__btn--primary {
  border: 1px solid rgb(var(--color-accent-primary-rgb) / 35%);
  background: var(--color-accent-primary);
  color: var(--color-accent-primary-contrast);
}

.subscription-dialog__btn--primary:hover {
  background: var(--color-accent-primary-hover);
}

.subscription-dialog__btn:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}
</style>

// ccr-ui/src/features/claude/observer/SubscriptionDialog.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useSetClaudeObserverSubscription } from '@/features/claude/queries'
import { t } from '@/features/claude/locale'
import { BaseModal } from '@/ui'
import { getErrorMessage } from '@/utils/errorHandler'
import type { SubscriptionDto } from '@/types/claudeObserver'

interface SubscriptionForm {
  mode: string
  plan: string
  monthlyUsd: number
}

interface SubscriptionDialogProps {
  modelValue: boolean
  current: SubscriptionDto | null
  onClose: () => void
}

const MODE_OPTIONS = [
  { value: 'auto', labelKey: 'claudeCode.observer.subscription.modeAuto' },
  { value: 'api_key', labelKey: 'claudeCode.observer.subscription.modeApiKey' },
  { value: 'subscription', labelKey: 'claudeCode.observer.subscription.modeSubscription' },
] as const

const PLAN_OPTIONS = [
  { value: 'free_pro', labelKey: 'claudeCode.observer.subscription.planFreePro' },
  { value: 'max5x', labelKey: 'claudeCode.observer.subscription.planMax5x' },
  { value: 'max20x', labelKey: 'claudeCode.observer.subscription.planMax20x' },
  { value: 'team', labelKey: 'claudeCode.observer.subscription.planTeam' },
  { value: 'enterprise', labelKey: 'claudeCode.observer.subscription.planEnterprise' },
  { value: 'custom', labelKey: 'claudeCode.observer.subscription.planCustom' },
] as const

const fieldClass =
  'w-full rounded-xl border border-border-default bg-[var(--surface-card-bg)] px-3 py-2 text-sm text-text-primary'

export function SubscriptionDialog({ modelValue, current, onClose }: SubscriptionDialogProps) {
  const mutation = useSetClaudeObserverSubscription()
  const [error, setError] = useState<string | null>(null)
  const form = useForm<SubscriptionForm>({
    defaultValues: { mode: 'auto', plan: 'free_pro', monthlyUsd: 0 },
  })
  const { register, handleSubmit, reset, watch } = form
  const mode = watch('mode')
  const subscriptionDisabled = mode !== 'subscription'

  useEffect(() => {
    if (!modelValue) return
    reset({
      mode: current?.mode ?? 'auto',
      plan: current?.plan ?? 'free_pro',
      monthlyUsd: current?.monthly_usd ?? 0,
    })
    setError(null)
  }, [current, modelValue, reset])

  const onValid = useCallback(
    async (values: SubscriptionForm) => {
      setError(null)
      try {
        await mutation.mutateAsync({
          mode: values.mode,
          plan: values.plan,
          monthlyUsd: Number.isFinite(values.monthlyUsd) ? values.monthlyUsd : 0,
        })
        onClose()
      } catch (err) {
        setError(getErrorMessage(err))
      }
    },
    [mutation, onClose],
  )
  const onSubmit = useMemo(() => handleSubmit(onValid), [handleSubmit, onValid])
  const handleOpenChange = useCallback(
    (open: boolean) => {
      if (!open) onClose()
    },
    [onClose],
  )

  return (
    <BaseModal
      modelValue={modelValue}
      title={t('claudeCode.observer.subscription.dialogTitle')}
      size="sm"
      onUpdateModelValue={handleOpenChange}
      onClose={onClose}
      footer={
        <div className="flex justify-end gap-2">
          <button
            type="button"
            className="rounded-xl border border-border-default px-4 py-2 text-sm font-semibold text-text-secondary"
            disabled={mutation.isPending}
            onClick={onClose}
          >
            {t('common.cancel')}
          </button>
          <button
            type="button"
            className="rounded-xl bg-accent-primary px-4 py-2 text-sm font-semibold text-[color:var(--color-accent-primary-contrast)]"
            disabled={mutation.isPending}
            onClick={onSubmit}
          >
            {mutation.isPending ? t('claudeCode.observer.subscription.saving') : t('common.save')}
          </button>
        </div>
      }
    >
      <div className="grid gap-3.5">
        <label className="grid gap-1">
          <span className="text-xs font-semibold tracking-wide text-text-secondary">
            {t('claudeCode.observer.subscription.fieldMode')}
          </span>
          <select className={fieldClass} {...register('mode')}>
            {MODE_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {t(option.labelKey)}
              </option>
            ))}
          </select>
        </label>
        <label className="grid gap-1">
          <span className="text-xs font-semibold tracking-wide text-text-secondary">
            {t('claudeCode.observer.subscription.fieldPlan')}
          </span>
          <select className={fieldClass} disabled={subscriptionDisabled} {...register('plan')}>
            {PLAN_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {t(option.labelKey)}
              </option>
            ))}
          </select>
        </label>
        <label className="grid gap-1">
          <span className="text-xs font-semibold tracking-wide text-text-secondary">
            {t('claudeCode.observer.subscription.fieldMonthlyUsd')}
          </span>
          <input
            type="number"
            min={0}
            step={1}
            className={fieldClass}
            disabled={subscriptionDisabled}
            {...register('monthlyUsd', { valueAsNumber: true })}
          />
        </label>
        {error ? <p className="m-0 text-xs text-accent-danger">{error}</p> : null}
      </div>
    </BaseModal>
  )
}
