// ccr-ui/src/views/ClaudeAuthView.vue
<template>
  <div class="claude-auth-view">
    <div class="claude-auth-view__shell">
      <ModuleSubnav module="claude-code" />

      <header class="claude-auth-view__header">
        <div>
          <p class="claude-auth-view__eyebrow">
            {{ tt('Claude 官方订阅', 'Claude Official Subscription') }}
          </p>
          <h1 class="claude-auth-view__title">
            {{ tt('官方账号管理', 'Official account management') }}
          </h1>
          <p class="claude-auth-view__subtitle">
            {{ tt('保存、切换、删除 Claude Code 官方订阅账号快照；切换只会改写', 'Save, switch, or delete Claude Code official subscription snapshots. Switching only rewrites') }}
            <code>{{ credentialsFile }}</code>{{ tt('。', '.') }}
          </p>
        </div>

        <div class="claude-auth-view__actions">
          <RouterLink
            to="/claude-code"
            class="claude-auth-view__ghost-button"
          >
            {{ tt('返回 Claude Code', 'Back to Claude Code') }}
          </RouterLink>
          <button
            type="button"
            class="claude-auth-view__ghost-button"
            :disabled="loading"
            @click="refreshAll"
          >
            {{ tt('刷新', 'Refresh') }}
          </button>
          <button
            type="button"
            class="claude-auth-view__primary-button"
            :disabled="saving"
            @click="showSaveForm = true"
          >
            {{ tt('保存当前登录', 'Save current login') }}
          </button>
        </div>
      </header>

      <div
        v-if="authActionError"
        class="claude-auth-view__banner claude-auth-view__banner--error"
      >
        {{ authActionError }}
      </div>

      <section class="claude-auth-view__stats">
        <article class="claude-auth-view__stat-card">
          <p class="claude-auth-view__stat-label">
            {{ tt('登录状态', 'Login state') }}
          </p>
          <p class="claude-auth-view__stat-value">
            {{ loginStateLabel }}
          </p>
        </article>
        <article class="claude-auth-view__stat-card">
          <p class="claude-auth-view__stat-label">
            {{ tt('运行时模式', 'Runtime mode') }}
          </p>
          <p class="claude-auth-view__stat-value">
            {{ runtimeModeLabel }}
          </p>
        </article>
        <article class="claude-auth-view__stat-card">
          <p class="claude-auth-view__stat-label">
            {{ tt('当前 Profile', 'Current profile') }}
          </p>
          <p class="claude-auth-view__stat-value">
            {{ currentProfileLabel }}
          </p>
        </article>
        <article class="claude-auth-view__stat-card">
          <p class="claude-auth-view__stat-label">
            {{ tt('已保存账号', 'Saved accounts') }}
          </p>
          <p class="claude-auth-view__stat-value">
            {{ accounts.length }}
          </p>
        </article>
      </section>

      <section
        v-if="currentInfo"
        class="claude-auth-view__panel"
      >
        <div class="claude-auth-view__panel-header">
          <h2 class="claude-auth-view__panel-title">
            {{ tt('当前运行时官方登录', 'Current runtime official login') }}
          </h2>
        </div>

        <div class="claude-auth-view__detail-grid">
          <div>
            <p class="claude-auth-view__detail-label">
              {{ tt('邮箱', 'Email') }}
            </p>
            <p class="claude-auth-view__detail-value">
              {{ currentInfo.email || '-' }}
            </p>
          </div>
          <div>
            <p class="claude-auth-view__detail-label">
              {{ tt('账号 UUID', 'Account UUID') }}
            </p>
            <p class="claude-auth-view__detail-value">
              {{ currentInfo.account_uuid || '-' }}
            </p>
          </div>
          <div>
            <p class="claude-auth-view__detail-label">
              {{ tt('订阅类型', 'Subscription type') }}
            </p>
            <p class="claude-auth-view__detail-value">
              {{ currentInfo.subscription_type || '-' }}
            </p>
          </div>
          <div>
            <p class="claude-auth-view__detail-label">
              {{ tt('计费类型', 'Billing type') }}
            </p>
            <p class="claude-auth-view__detail-value">
              {{ currentInfo.billing_type || '-' }}
            </p>
          </div>
          <div>
            <p class="claude-auth-view__detail-label">
              {{ tt('速率档位', 'Rate tier') }}
            </p>
            <p class="claude-auth-view__detail-value">
              {{ currentInfo.rate_limit_tier || '-' }}
            </p>
          </div>
          <div>
            <p class="claude-auth-view__detail-label">
              {{ tt('Access Token 到期', 'Access token expiry') }}
            </p>
            <p class="claude-auth-view__detail-value">
              {{ currentInfo.expires_at ? formatDate(currentInfo.expires_at) : '-' }}
            </p>
          </div>
        </div>
      </section>

      <section class="claude-auth-view__panel">
        <div class="claude-auth-view__panel-header">
          <div>
            <h2 class="claude-auth-view__panel-title">
              {{ tt('已保存账号快照', 'Saved account snapshots') }}
            </h2>
            <p class="claude-auth-view__panel-subtitle">
              {{ tt('每个快照都保存当前 `claudeAiOauth`，切换时不会改写', 'Each snapshot keeps the current `claudeAiOauth`, and switching will not rewrite') }}
              <code>{{ claudeJsonFile }}</code>{{ tt('。', '.') }}
            </p>
          </div>
        </div>

        <div
          v-if="loading"
          class="claude-auth-view__empty"
        >
          {{ tt('正在加载账号信息…', 'Loading account details...') }}
        </div>

        <EmptyState
          v-else-if="accounts.length === 0"
          icon="User"
          :title="tt('尚未保存任何官方账号快照。', 'No official account snapshots saved yet.')"
          :action-text="tt('保存当前登录', 'Save current login')"
          action-icon="Plus"
          :on-action="() => { showSaveForm = true }"
        />

        <div
          v-else
          class="claude-auth-view__table-wrap"
        >
          <table class="claude-auth-view__table">
            <thead>
              <tr>
                <th>{{ tt('名称', 'Name') }}</th>
                <th>{{ tt('邮箱', 'Email') }}</th>
                <th>{{ tt('订阅', 'Subscription') }}</th>
                <th>{{ tt('到期', 'Expiry') }}</th>
                <th>{{ tt('状态', 'State') }}</th>
                <th>{{ tt('操作', 'Actions') }}</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="account in accounts"
                :key="account.name"
              >
                <td>
                  <div class="claude-auth-view__account-name">
                    <span>{{ account.name }}</span>
                    <span
                      v-if="account.is_current"
                      class="claude-auth-view__pill"
                    >
                      {{ tt('当前', 'Current') }}
                    </span>
                  </div>
                  <p
                    v-if="account.description"
                    class="claude-auth-view__muted"
                  >
                    {{ account.description }}
                  </p>
                </td>
                <td>{{ account.email || '-' }}</td>
                <td>{{ account.subscription_type || '-' }}</td>
                <td>
                  {{ account.expires_at ? formatDate(account.expires_at) : '-' }}
                </td>
                <td>
                  {{ account.is_current ? tt('当前生效', 'Active now') : account.is_logged_in ? tt('已登录', 'Logged in') : tt('已保存', 'Saved') }}
                </td>
                <td>
                  <div class="claude-auth-view__row-actions">
                    <button
                      type="button"
                      class="claude-auth-view__table-button"
                      :disabled="busyName === account.name"
                      @click="handleSwitch(account.name)"
                    >
                      {{ tt('切换', 'Switch') }}
                    </button>
                    <button
                      type="button"
                      class="claude-auth-view__table-button claude-auth-view__table-button--danger"
                      :disabled="busyName === account.name"
                      @click="handleDelete(account.name)"
                    >
                      {{ tt('删除', 'Delete') }}
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <BaseModal
        v-model="showSaveForm"
        :title="tt('保存当前官方登录', 'Save current official login')"
        size="md"
        surface="solid"
      >
        <p class="claude-auth-view__modal-subtitle">
          {{ tt('当前必须已经通过 `claude login` 拿到官方登录，CCR 只负责保存快照和切换。', 'You must already have an official login from `claude login`. CCR only saves and switches snapshots.') }}
        </p>

        <label class="claude-auth-view__field">
          <span>{{ tt('账号名称', 'Account name') }}</span>
          <input
            v-model="saveForm.name"
            type="text"
            :placeholder="tt('例如 work / personal', 'e.g. work / personal')"
          >
        </label>

        <label class="claude-auth-view__field">
          <span>{{ tt('描述（可选）', 'Description (optional)') }}</span>
          <input
            v-model="saveForm.description"
            type="text"
            :placeholder="tt('例如 公司订阅 / 个人订阅', 'e.g. company plan / personal plan')"
          >
        </label>

        <label class="claude-auth-view__checkbox">
          <input
            v-model="saveForm.force"
            type="checkbox"
          >
          <span>{{ tt('覆盖同名账号', 'Overwrite same-name account') }}</span>
        </label>

        <template #footer>
          <button
            type="button"
            class="claude-auth-view__ghost-button"
            @click="showSaveForm = false"
          >
            {{ tt('取消', 'Cancel') }}
          </button>
          <button
            type="button"
            class="claude-auth-view__primary-button"
            :disabled="saving"
            @click="handleSave"
          >
            {{ saving ? tt('保存中…', 'Saving...') : tt('保存', 'Save') }}
          </button>
        </template>
      </BaseModal>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onActivated, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import ModuleSubnav from '@/components/ModuleSubnav.vue'
import BaseModal from '@/components/common/BaseModal.vue'
import EmptyState from '@/components/ui/EmptyState.vue'
import {
  deleteClaudeAuth,
  getClaudeAuthCurrent,
  listClaudeAuthAccounts,
  saveClaudeAuth,
  switchClaudeAuth,
} from '@/api'
import type {
  ClaudeAuthAccountItem,
  ClaudeAuthCurrentInfo,
  ClaudeAuthCurrentResponse,
  ClaudeAuthListResponse,
  ClaudeAuthSaveRequest,
  ClaudeLoginState,
  ClaudeRuntimeSummary,
} from '@/types'
import { logger } from '@/utils/logger'
import { useUIStore } from '@/stores/ui'

defineOptions({ name: 'ClaudeAuthView' })

const { locale } = useI18n()
const uiStore = useUIStore()
const isZh = computed(() => locale.value.startsWith('zh'))
const tt = (zh: string, en: string) => (isZh.value ? zh : en)
const credentialsFile = '~/.claude/.credentials.json'
const claudeJsonFile = '~/.claude.json'

const loading = ref(false)
const saving = ref(false)
const busyName = ref<string | null>(null)
const showSaveForm = ref(false)
const authActionError = ref<string | null>(null)

const accounts = ref<ClaudeAuthAccountItem[]>([])
const currentInfo = ref<ClaudeAuthCurrentInfo | null>(null)
const runtimeSummary = ref<ClaudeRuntimeSummary | null>(null)
const loginState = ref<ClaudeLoginState>({ type: 'NotLoggedIn' })

const saveForm = reactive({
  name: '',
  description: '',
  force: false,
})

const extractErrorMessage = (error: unknown): string => {
  if (error instanceof Error && error.message) return error.message
  if (typeof error === 'string') return error
  return tt('请求失败', 'Request failed')
}

const loginStateLabel = computed(() => {
  switch (loginState.value.type) {
    case 'LoggedInSaved':
      return tt(`已登录（已保存为 ${loginState.value.account_name}）`, `Logged in (saved as ${loginState.value.account_name})`)
    case 'LoggedInUnsaved':
      return tt('已登录（未保存）', 'Logged in (unsaved)')
    case 'ApiKeyActive':
      return tt('当前由 API key profile 控制', 'Currently controlled by the API key profile')
    case 'NotLoggedIn':
    default:
      return tt('未登录', 'Not logged in')
  }
})

const runtimeModeLabel = computed(() => {
  switch (runtimeSummary.value?.mode) {
    case 'profile_with_auth':
      return tt('Profile + 官方订阅', 'Profile + official subscription')
    case 'profile_pending_auth':
      return tt('Profile 等待官方订阅', 'Profile waiting for official subscription')
    case 'profile_only':
      return tt('Profile 驱动（API key）', 'Profile-driven (API key)')
    case 'runtime_only':
      return tt('仅官方订阅运行时', 'Official subscription runtime only')
    case 'unresolved':
    default:
      return tt('未解析', 'Unresolved')
  }
})

const currentProfileLabel = computed(() => {
  const summary = runtimeSummary.value
  if (!summary?.current_profile_name) {
    return tt('未绑定', 'Unbound')
  }

  const authMode = summary.current_profile_auth_mode
  return authMode
    ? `${summary.current_profile_name} · ${authMode}`
    : summary.current_profile_name
})

const formatDate = (date: string) => {
  try {
    return new Date(date).toLocaleString(isZh.value ? 'zh-CN' : 'en-US')
  } catch {
    return date
  }
}

const refreshAll = async () => {
  try {
    loading.value = true
    authActionError.value = null

    const [accountsData, currentData] = await Promise.all([
      listClaudeAuthAccounts<ClaudeAuthListResponse>(),
      getClaudeAuthCurrent<ClaudeAuthCurrentResponse>(),
    ])

    accounts.value = accountsData.accounts || []
    runtimeSummary.value = accountsData.runtime_summary || currentData.runtime_summary
    loginState.value = accountsData.login_state || currentData.login_state
    currentInfo.value = currentData.info || null
  } catch (error) {
    logger.error('Failed to load Claude auth data:', error)
    authActionError.value = extractErrorMessage(error)
    uiStore.showError(authActionError.value)
  } finally {
    loading.value = false
  }
}

const handleSave = async () => {
  if (!saveForm.name.trim()) {
    uiStore.showError(tt('账号名称不能为空', 'Account name is required'))
    return
  }

  try {
    saving.value = true
    authActionError.value = null

    const payload: ClaudeAuthSaveRequest = {
      name: saveForm.name.trim(),
      description: saveForm.description.trim() || null,
      force: saveForm.force,
    }

    await saveClaudeAuth(payload)
    uiStore.showSuccess(tt('Claude 官方账号已保存', 'Claude official account saved'))
    showSaveForm.value = false
    saveForm.name = ''
    saveForm.description = ''
    saveForm.force = false
    await refreshAll()
  } catch (error) {
    logger.error('Failed to save Claude auth:', error)
    authActionError.value = extractErrorMessage(error)
    uiStore.showError(authActionError.value)
  } finally {
    saving.value = false
  }
}

const handleSwitch = async (name: string) => {
  const confirmed = await uiStore.requestConfirm({
    title: tt('切换官方账号', 'Switch official account'),
    message: tt(`确定切换到官方账号 "${name}" 吗？`, `Switch to official account "${name}"?`),
    confirmText: tt('切换', 'Switch'),
    cancelText: tt('取消', 'Cancel'),
    type: 'warning',
  })
  if (!confirmed) return

  try {
    busyName.value = name
    authActionError.value = null
    await switchClaudeAuth(name)
    uiStore.showSuccess(tt(`已切换到 ${name}`, `Switched to ${name}`))
    await refreshAll()
  } catch (error) {
    logger.error('Failed to switch Claude auth:', error)
    authActionError.value = extractErrorMessage(error)
    uiStore.showError(authActionError.value)
  } finally {
    busyName.value = null
  }
}

const handleDelete = async (name: string) => {
  const confirmed = await uiStore.requestConfirm({
    title: tt('删除官方账号', 'Delete official account'),
    message: tt(`确定删除官方账号 "${name}" 吗？`, `Delete official account "${name}"?`),
    confirmText: tt('删除', 'Delete'),
    cancelText: tt('取消', 'Cancel'),
    type: 'danger',
  })
  if (!confirmed) return

  try {
    busyName.value = name
    authActionError.value = null
    await deleteClaudeAuth(name)
    uiStore.showSuccess(tt(`已删除 ${name}`, `Deleted ${name}`))
    await refreshAll()
  } catch (error) {
    logger.error('Failed to delete Claude auth:', error)
    authActionError.value = extractErrorMessage(error)
    uiStore.showError(authActionError.value)
  } finally {
    busyName.value = null
  }
}

onMounted(async () => {
  await refreshAll()
})

onActivated(() => {
  void refreshAll()
})
</script>

<style scoped>
.claude-auth-view {
  min-height: 100%;
  padding: 1.5rem;
}

.claude-auth-view__shell {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
  max-width: 1440px;
  margin: 0 auto;
}

.claude-auth-view__header,
.claude-auth-view__actions,
.claude-auth-view__panel-header,
.claude-auth-view__row-actions,
.claude-auth-view__account-name {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.claude-auth-view__header,
.claude-auth-view__panel-header {
  justify-content: space-between;
}

.claude-auth-view__eyebrow {
  color: var(--stage-text-quiet);
  font-size: 0.75rem;
  line-height: 1rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.claude-auth-view__title {
  color: var(--stage-text-primary);
  font-size: 1.875rem;
  line-height: 2.25rem;
  font-weight: 700;
}

.claude-auth-view__subtitle,
.claude-auth-view__panel-subtitle,
.claude-auth-view__muted,
.claude-auth-view__detail-label {
  color: var(--stage-text-secondary);
  font-size: 0.875rem;
  line-height: 1.4;
}

.claude-auth-view__ghost-button,
.claude-auth-view__primary-button,
.claude-auth-view__table-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 9999px;
  padding: 0.75rem 1rem;
  font-size: 0.875rem;
  line-height: 1;
  font-weight: 600;
  transition: opacity 0.2s ease, transform 0.2s ease;
}

.claude-auth-view__ghost-button,
.claude-auth-view__table-button {
  border: 1px solid var(--stage-border-soft);
  background: var(--stage-surface-soft);
  color: var(--stage-text-primary);
}

.claude-auth-view__primary-button {
  border: 1px solid rgb(var(--color-accent-primary-rgb) / 25%);
  background: rgb(var(--color-accent-primary-rgb) / 12%);
  color: var(--color-accent-primary);
}

.claude-auth-view__table-button--danger {
  color: var(--color-danger);
}

.claude-auth-view__ghost-button:disabled,
.claude-auth-view__primary-button:disabled,
.claude-auth-view__table-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.claude-auth-view__stats {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 1rem;
}

.claude-auth-view__stat-card,
.claude-auth-view__panel,
.claude-auth-view__banner {
  border: 1px solid var(--stage-border-soft);
  border-radius: 1rem;
  background: var(--stage-surface-elevated);
  padding: 1rem 1.125rem;
}

.claude-auth-view__stat-label {
  color: var(--stage-text-quiet);
  font-size: 0.75rem;
  line-height: 1rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.claude-auth-view__stat-value,
.claude-auth-view__panel-title {
  color: var(--stage-text-primary);
  font-size: 1.125rem;
  line-height: 1.5rem;
  font-weight: 700;
  margin-top: 0.35rem;
}

.claude-auth-view__banner--error {
  border-color: rgb(var(--color-danger-rgb) / 25%);
  background: rgb(var(--color-danger-rgb) / 10%);
  color: var(--color-danger);
}

.claude-auth-view__detail-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 1rem;
  margin-top: 1rem;
}

.claude-auth-view__detail-value {
  color: var(--stage-text-primary);
  font-size: 0.95rem;
  line-height: 1.4;
  margin-top: 0.25rem;
  overflow-wrap: anywhere;
}

.claude-auth-view__freshness {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  font-size: 0.8rem;
  line-height: 1rem;
  font-weight: 600;
}

.claude-auth-view__freshness--fresh {
  color: var(--color-success);
}

.claude-auth-view__freshness--stale {
  color: var(--color-warning);
}

.claude-auth-view__freshness--old {
  color: var(--color-danger);
}

.claude-auth-view__table-wrap {
  overflow-x: auto;
  margin-top: 1rem;
}

.claude-auth-view__table {
  width: 100%;
  border-collapse: collapse;
}

.claude-auth-view__table th,
.claude-auth-view__table td {
  border-bottom: 1px solid var(--stage-border-soft);
  padding: 0.875rem 0.75rem;
  text-align: left;
  vertical-align: top;
}

.claude-auth-view__table th {
  color: var(--stage-text-quiet);
  font-size: 0.75rem;
  line-height: 1rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.claude-auth-view__table td {
  color: var(--stage-text-primary);
  font-size: 0.9rem;
  line-height: 1.4;
}

.claude-auth-view__pill {
  border: 1px solid rgb(var(--color-accent-primary-rgb) / 25%);
  border-radius: 9999px;
  background: rgb(var(--color-accent-primary-rgb) / 10%);
  padding: 0.1rem 0.5rem;
  color: var(--color-accent-primary);
  font-size: 0.75rem;
  line-height: 1rem;
  font-weight: 700;
}

.claude-auth-view__empty {
  padding: 2rem 1rem;
  color: var(--stage-text-secondary);
  text-align: center;
}

.claude-auth-view__modal-subtitle {
  margin-top: 0.5rem;
  color: var(--stage-text-secondary);
  font-size: 0.875rem;
  line-height: 1.5;
}

.claude-auth-view__field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-top: 1rem;
  color: var(--stage-text-primary);
  font-size: 0.875rem;
  font-weight: 600;
}

.claude-auth-view__field input {
  border: 1px solid var(--stage-border-soft);
  border-radius: 0.75rem;
  background: var(--stage-surface-soft);
  color: var(--stage-text-primary);
  padding: 0.8rem 0.9rem;
}

.claude-auth-view__checkbox {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  margin-top: 1rem;
  color: var(--stage-text-primary);
  font-size: 0.875rem;
}

@media (width <= 1024px) {
  .claude-auth-view__stats {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .claude-auth-view__detail-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (width <= 768px) {
  .claude-auth-view__header,
  .claude-auth-view__actions,
  .claude-auth-view__panel-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .claude-auth-view__stats,
  .claude-auth-view__detail-grid {
    grid-template-columns: 1fr;
  }

  .claude-auth-view__row-actions {
    flex-wrap: wrap;
  }
}
</style>

// ccr-ui/src/features/claude/ClaudeAuthView.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router'
import { useForm } from 'react-hook-form'
import {
  deleteClaudeAuth,
  getClaudeAuthCurrent,
  listClaudeAuthAccounts,
  saveClaudeAuth,
  switchClaudeAuth,
} from '@/api'
import { claudeAuthOff, claudeProfileOff, listClaudeProfiles } from '@/api/domains/claude'
import { surfaceNotify } from '@/configs/surfaceNotify'
import {
  AuthAccountsPanel,
  AuthCurrentPanel,
  AuthDiagnosis,
  AuthStatCard,
} from '@/features/claude/auth/AuthPanels'
import {
  authOwnershipLabel,
  currentProfileLabel,
  extractAuthError,
  formatAuthSource,
  loginStateLabel,
  runtimeModeLabel,
  authConfidenceLabel,
} from '@/features/claude/auth/authLabels'
import { ClaudeSubnav } from '@/features/claude/ClaudeSubnav'
import { t, tt } from '@/features/claude/locale'
import type {
  ClaudeAuthAccountItem,
  ClaudeAuthCurrentInfo,
  ClaudeAuthSaveRequest,
  ClaudeLoginState,
  ClaudeRuntimeSummary,
} from '@/types'
import { BaseModal, PageHeader, PageShell } from '@/ui'
import { logger } from '@/utils/logger'

interface SaveForm {
  name: string
  description: string
  force: boolean
}

const CREDENTIALS_FILE = '~/.claude/.credentials.json'

/** Claude 官方账号快照（OAuth 余量）。session/auth-off 语义与 BaseAuth 对齐。 */
export function ClaudeAuthView() {
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [busyName, setBusyName] = useState<string | null>(null)
  const [showSaveForm, setShowSaveForm] = useState(false)
  const [authActionError, setAuthActionError] = useState<string | null>(null)
  const [accounts, setAccounts] = useState<ClaudeAuthAccountItem[]>([])
  const [currentInfo, setCurrentInfo] = useState<ClaudeAuthCurrentInfo | null>(null)
  const [runtimeSummary, setRuntimeSummary] = useState<ClaudeRuntimeSummary | null>(null)
  const [loginState, setLoginState] = useState<ClaudeLoginState>({ type: 'NotLoggedIn' })
  const [canOff, setCanOff] = useState(false)
  const [canAuthOff, setCanAuthOff] = useState(false)
  const form = useForm<SaveForm>({ defaultValues: { name: '', description: '', force: false } })
  const { register, handleSubmit, reset } = form

  const refreshAll = useCallback(async () => {
    try {
      setLoading(true)
      setAuthActionError(null)
      const [accountsData, currentData, profilesData] = await Promise.all([
        listClaudeAuthAccounts(),
        getClaudeAuthCurrent(),
        listClaudeProfiles().catch(() => ({ can_off: false })),
      ])
      setAccounts(accountsData.accounts || [])
      setRuntimeSummary(accountsData.runtime_summary || currentData.runtime_summary)
      setLoginState(accountsData.login_state || currentData.login_state)
      setCurrentInfo(currentData.info || null)
      setCanOff(profilesData.can_off === true)
      setCanAuthOff(accountsData.can_auth_off === true || currentData.can_auth_off === true)
    } catch (error) {
      logger.error('Failed to load Claude auth data:', error)
      const message = extractAuthError(error)
      setAuthActionError(message)
      surfaceNotify.error(message)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void refreshAll()
  }, [refreshAll])

  const openSave = useCallback(() => setShowSaveForm(true), [])
  const closeSave = useCallback(() => setShowSaveForm(false), [])
  const handleOpenChange = useCallback((open: boolean) => {
    if (!open) setShowSaveForm(false)
  }, [])

  const onSaveValid = useCallback(
    async (values: SaveForm) => {
      if (!values.name.trim()) {
        surfaceNotify.error(tt('账号名称不能为空', 'Account name is required'))
        return
      }
      try {
        setSaving(true)
        setAuthActionError(null)
        const payload: ClaudeAuthSaveRequest = {
          name: values.name.trim(),
          description: values.description.trim() || null,
          force: values.force,
        }
        await saveClaudeAuth(payload)
        surfaceNotify.success(tt('Claude 官方账号已保存', 'Claude official account saved'))
        setShowSaveForm(false)
        reset({ name: '', description: '', force: false })
        await refreshAll()
      } catch (error) {
        logger.error('Failed to save Claude auth:', error)
        const message = extractAuthError(error)
        setAuthActionError(message)
        surfaceNotify.error(message)
      } finally {
        setSaving(false)
      }
    },
    [refreshAll, reset],
  )
  const onSave = useMemo(() => handleSubmit(onSaveValid), [handleSubmit, onSaveValid])

  const handleAuthOff = useCallback(async () => {
    const confirmed = await surfaceNotify.confirm({
      title: t('auth.confirmOffTitle'),
      message: t('auth.confirmOffClaude'),
      confirmText: t('auth.off'),
      cancelText: t('common.cancel'),
      type: 'warning',
    })
    if (!confirmed) return
    try {
      setLoading(true)
      setAuthActionError(null)
      const result = await claudeAuthOff()
      surfaceNotify.success(result.changed ? t('auth.offSuccess') : t('auth.offUnchanged'))
      for (const warning of result.warnings) surfaceNotify.warning(warning)
      await refreshAll()
    } catch (error) {
      logger.error('Failed to log out Claude official session:', error)
      const message = extractAuthError(error)
      setAuthActionError(message)
      surfaceNotify.error(message || t('auth.offFailed'))
    } finally {
      setLoading(false)
    }
  }, [refreshAll])

  const handleProfileOff = useCallback(async () => {
    const confirmed = await surfaceNotify.confirm({
      title: tt('退出 Profile', 'Exit profile'),
      message: tt(
        '退出当前 Profile 并清理会压制官方登录的 CCR 运行时残留？已保存的账号不会删除。',
        'Exit the current profile and clear CCR leftovers that can suppress official login? Saved accounts stay.',
      ),
      confirmText: tt('退出 Profile', 'Exit profile'),
      cancelText: tt('取消', 'Cancel'),
      type: 'warning',
    })
    if (!confirmed) return
    try {
      setLoading(true)
      setAuthActionError(null)
      const result = await claudeProfileOff()
      surfaceNotify.success(tt('已退出 Profile 并清理登录残留', 'Exited profile mode and cleared login leftovers'))
      const warnings = result.remaining_suppressors.map((source) =>
        tt(
          `退出 Profile 后仍存在${authOwnershipLabel(source.ownership)}认证来源：${formatAuthSource(source)}（${authConfidenceLabel(source.confidence)}）`,
          `${authOwnershipLabel(source.ownership)} auth source remains after exit profile: ${formatAuthSource(source)} (${authConfidenceLabel(source.confidence)})`,
        ),
      )
      for (const warning of warnings.length > 0 ? warnings : result.warnings) surfaceNotify.warning(warning)
      await refreshAll()
    } catch (error) {
      logger.error('Failed to exit Claude profile mode:', error)
      const message = extractAuthError(error)
      setAuthActionError(message)
      surfaceNotify.error(message)
    } finally {
      setLoading(false)
    }
  }, [refreshAll])

  const handleSwitch = useCallback(
    async (name: string) => {
      const confirmed = await surfaceNotify.confirm({
        title: tt('切换官方账号', 'Switch official account'),
        message: tt(`确定切换到官方账号 "${name}" 吗？`, `Switch to official account "${name}"?`),
        confirmText: tt('切换', 'Switch'),
        cancelText: tt('取消', 'Cancel'),
        type: 'warning',
      })
      if (!confirmed) return
      try {
        setBusyName(name)
        setAuthActionError(null)
        const result = await switchClaudeAuth(name)
        const clearedCount = result.cleared_managed_sources.length
        surfaceNotify.success(
          clearedCount > 0
            ? tt(`已切换到 ${name}，并清理 ${clearedCount} 个 CCR 托管设置`, `Switched to ${name} and cleared ${clearedCount} CCR-managed setting(s)`)
            : tt(`已切换到 ${name}`, `Switched to ${name}`),
        )
        const structured = result.remaining_suppressors.map((source) =>
          tt(
            `切换后仍存在${authOwnershipLabel(source.ownership)}认证来源：${formatAuthSource(source)}（${authConfidenceLabel(source.confidence)}）`,
            `${authOwnershipLabel(source.ownership)} auth source remains after switching: ${formatAuthSource(source)} (${authConfidenceLabel(source.confidence)})`,
          ),
        )
        for (const warning of structured.length > 0 ? structured : result.warnings) surfaceNotify.warning(warning)
        await refreshAll()
      } catch (error) {
        logger.error('Failed to switch Claude auth:', error)
        const message = extractAuthError(error)
        setAuthActionError(message)
        surfaceNotify.error(message)
      } finally {
        setBusyName(null)
      }
    },
    [refreshAll],
  )

  const handleDelete = useCallback(
    async (name: string) => {
      const confirmed = await surfaceNotify.confirm({
        title: tt('删除官方账号', 'Delete official account'),
        message: tt(`确定删除官方账号 "${name}" 吗？`, `Delete official account "${name}"?`),
        confirmText: tt('删除', 'Delete'),
        cancelText: tt('取消', 'Cancel'),
        type: 'danger',
      })
      if (!confirmed) return
      try {
        setBusyName(name)
        setAuthActionError(null)
        await deleteClaudeAuth(name)
        surfaceNotify.success(tt(`已删除 ${name}`, `Deleted ${name}`))
        await refreshAll()
      } catch (error) {
        logger.error('Failed to delete Claude auth:', error)
        const message = extractAuthError(error)
        setAuthActionError(message)
        surfaceNotify.error(message)
      } finally {
        setBusyName(null)
      }
    },
    [refreshAll],
  )

  const header = (
    <PageHeader
      title={tt('官方账号管理', 'Official account management')}
      eyebrow={tt('Claude 官方订阅', 'Claude Official Subscription')}
      description={tt(
        `保存、切换、删除 Claude Code 官方订阅账号快照；切换会更新 ${CREDENTIALS_FILE}，并只清理 CCR 托管的 Profile 设置。`,
        `Save, switch, or delete Claude Code official subscription snapshots. Switching updates ${CREDENTIALS_FILE} and clears only CCR-managed profile settings.`,
      )}
      actions={
        <div className="flex flex-wrap gap-2">
          <Link to="/claude-code" className="inline-flex rounded-lg border border-border-default px-3 py-2 text-sm">
            {tt('返回 Claude Code', 'Back to Claude Code')}
          </Link>
          <button type="button" className="rounded-lg border border-border-default px-3 py-2 text-sm" disabled={loading} onClick={refreshAll}>
            {tt('刷新', 'Refresh')}
          </button>
          <button type="button" className="rounded-lg bg-accent-primary px-3 py-2 text-sm text-[color:var(--color-accent-primary-contrast)]" disabled={saving} onClick={openSave}>
            {tt('保存当前登录', 'Save current login')}
          </button>
        </div>
      }
    />
  )

  return (
    <PageShell className="claude-auth-view" header={header} subnav={<ClaudeSubnav />}>
      <div className="grid gap-4">
        {authActionError ? (
          <div className="rounded-2xl border border-accent-danger/25 bg-accent-danger/10 px-4 py-3 text-accent-danger">
            {authActionError}
          </div>
        ) : null}
        <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <AuthStatCard label={tt('登录状态', 'Login state')} value={loginStateLabel(loginState)} />
          <AuthStatCard label={tt('运行时模式', 'Runtime mode')} value={runtimeModeLabel(runtimeSummary)} />
          <AuthStatCard label={tt('当前 Profile', 'Current profile')} value={currentProfileLabel(runtimeSummary)} />
          <AuthStatCard label={tt('已保存账号', 'Saved accounts')} value={String(accounts.length)} />
        </section>
        {runtimeSummary ? (
          <AuthDiagnosis
            summary={runtimeSummary}
            canAuthOff={canAuthOff}
            canOff={canOff}
            loading={loading}
            onAuthOff={handleAuthOff}
            onProfileOff={handleProfileOff}
          />
        ) : null}
        {currentInfo ? <AuthCurrentPanel info={currentInfo} /> : null}
        <AuthAccountsPanel
          loading={loading}
          accounts={accounts}
          busyName={busyName}
          onSave={openSave}
          onSwitch={handleSwitch}
          onDelete={handleDelete}
        />
      </div>
      <BaseModal
        modelValue={showSaveForm}
        title={tt('保存当前官方登录', 'Save current official login')}
        size="md"
        surface="solid"
        onUpdateModelValue={handleOpenChange}
        onClose={closeSave}
        footer={
          <div className="flex w-full gap-4">
            <button type="button" className="flex-1 rounded-full border border-[color:var(--stage-border-soft)] px-4 py-3 text-sm" onClick={closeSave}>
              {tt('取消', 'Cancel')}
            </button>
            <button
              type="button"
              className="flex-1 rounded-full border border-accent-primary/25 bg-accent-primary/12 px-4 py-3 text-sm font-semibold text-accent-primary"
              disabled={saving}
              onClick={onSave}
            >
              {saving ? tt('保存中…', 'Saving...') : tt('保存', 'Save')}
            </button>
          </div>
        }
      >
        <p className="mt-2 text-sm leading-6 text-[color:var(--stage-text-secondary)]">
          {tt('当前必须已经通过 `claude login` 拿到官方登录，CCR 只负责保存快照和切换。', 'You must already have an official login from `claude login`. CCR only saves and switches snapshots.')}
        </p>
        <label className="mt-4 grid gap-2 text-sm font-semibold text-[color:var(--stage-text-primary)]">
          <span>{tt('账号名称', 'Account name')}</span>
          <input
            type="text"
            className="rounded-xl border border-[color:var(--stage-border-soft)] bg-[var(--stage-surface-soft)] px-3 py-3"
            placeholder={tt('例如 work / personal', 'e.g. work / personal')}
            {...register('name')}
          />
        </label>
        <label className="mt-4 grid gap-2 text-sm font-semibold text-[color:var(--stage-text-primary)]">
          <span>{tt('描述（可选）', 'Description (optional)')}</span>
          <input
            type="text"
            className="rounded-xl border border-[color:var(--stage-border-soft)] bg-[var(--stage-surface-soft)] px-3 py-3"
            placeholder={tt('例如 公司订阅 / 个人订阅', 'e.g. company plan / personal plan')}
            {...register('description')}
          />
        </label>
        <label className="mt-4 inline-flex items-center gap-2 text-sm text-[color:var(--stage-text-primary)]">
          <input type="checkbox" {...register('force')} />
          <span>{tt('覆盖同名账号', 'Overwrite same-name account')}</span>
        </label>
      </BaseModal>
    </PageShell>
  )
}
