// ccr-ui/src/views/GeminiCliView.vue
<template>
  <div class="gemini-view stage-page">
    <!-- Background Mesh -->
    <!-- Standard Animated Background -->
    <AnimatedBackground
      contained
      variant="complex"
    />

    <div class="gemini-shell">
      <!-- HEADER -->
      <section class="animate-slide-up">
        <div class="gemini-header">
          <div class="gemini-brand">
            <div class="gemini-brand__icon">
              <SIcon
                name="Sparkles"
                size="w-8 h-8"
              />
            </div>
            <div>
              <h1 class="gemini-brand__title">
                Gemini CLI
              </h1>
              <p class="gemini-brand__subtitle">
                {{ $t('gemini.overview.description') }}
              </p>
            </div>
          </div>

          <RouterLink to="/">
            <Button
              variant="glass"
              class="gemini-home-button"
            >
              <SIcon
                name="Home"
                size="w-4 h-4"
              />
              {{ $t('common.backToHome') }}
            </Button>
          </RouterLink>
        </div>

        <!-- Tags -->
        <div class="gemini-tag-row">
          <span class="gemini-tag gemini-tag--gemini">
            <SIcon
              name="Server"
              size="w-3 h-3"
            /> MCP Server
          </span>
          <span class="gemini-tag gemini-tag--success">
            <SIcon
              name="Bot"
              size="w-3 h-3"
            /> Smart Agents
          </span>
          <span class="gemini-tag gemini-tag--claude">
            <SIcon
              name="Puzzle"
              size="w-3 h-3"
            /> Plugin System
          </span>
          <span class="gemini-tag gemini-tag--secondary">
            <SIcon
              name="Sparkles"
              size="w-3 h-3"
            /> Multimodal
          </span>
        </div>
      </section>

      <!-- MODULES -->
      <section class="animate-slide-up">
        <div class="gemini-section-heading">
          <SIcon
            name="Boxes"
            size="w-5 h-5"
            class="gemini-section-heading__icon"
          />
          <h2 class="gemini-section-heading__title">
            {{ $t('common.modules') }}
          </h2>
          <div class="gemini-section-heading__rule" />
        </div>

        <div class="gemini-module-grid">
          <!-- MCP -->
          <RouterLink
            to="/gemini-cli/mcp"
            class="gemini-module-link"
          >
            <Card
              variant="glass"
              hover
              glow
              class="gemini-module-card"
            >
              <div class="gemini-module-card__icon gemini-module-card__icon--gemini">
                <SIcon
                  name="Server"
                  size="w-6 h-6"
                />
              </div>
              <div>
                <h3 class="gemini-module-card__title gemini-module-card__title--gemini">
                  {{ $t('gemini.mcp.title') }}
                </h3>
                <p class="gemini-module-card__desc">
                  {{ $t('gemini.mcp.subtitle') }}
                </p>
                <span class="gemini-module-card__badge gemini-module-card__badge--gemini">MCP</span>
              </div>
            </Card>
          </RouterLink>

          <!-- Agents -->
          <RouterLink
            to="/gemini-cli/agents"
            class="gemini-module-link"
          >
            <Card
              variant="glass"
              hover
              glow
              class="gemini-module-card"
            >
              <div class="gemini-module-card__icon gemini-module-card__icon--success">
                <SIcon
                  name="Bot"
                  size="w-6 h-6"
                />
              </div>
              <div>
                <h3 class="gemini-module-card__title gemini-module-card__title--success">
                  {{ $t('gemini.agents.title') }}
                </h3>
                <p class="gemini-module-card__desc">
                  {{ $t('gemini.agents.subtitle') }}
                </p>
                <span class="gemini-module-card__badge gemini-module-card__badge--success">AI Agents</span>
              </div>
            </Card>
          </RouterLink>

          <!-- Plugins -->
          <RouterLink
            to="/gemini-cli/plugins"
            class="gemini-module-link"
          >
            <Card
              variant="glass"
              hover
              glow
              class="gemini-module-card"
            >
              <div class="gemini-module-card__icon gemini-module-card__icon--claude">
                <SIcon
                  name="Puzzle"
                  size="w-6 h-6"
                />
              </div>
              <div>
                <h3 class="gemini-module-card__title gemini-module-card__title--claude">
                  {{ $t('gemini.plugins.title') }}
                </h3>
                <p class="gemini-module-card__desc">
                  {{ $t('gemini.plugins.subtitle') }}
                </p>
                <span class="gemini-module-card__badge gemini-module-card__badge--claude">Plugins</span>
              </div>
            </Card>
          </RouterLink>

          <!-- Slash Commands -->
          <RouterLink
            to="/gemini-cli/slash-commands"
            class="gemini-module-link gemini-module-link--wide"
          >
            <Card
              variant="glass"
              hover
              glow
              class="gemini-module-card"
            >
              <div class="gemini-module-card__icon gemini-module-card__icon--secondary">
                <SIcon
                  name="Command"
                  size="w-6 h-6"
                />
              </div>
              <div>
                <h3 class="gemini-module-card__title gemini-module-card__title--secondary">
                  {{ $t('gemini.slashCommands.title') }}
                </h3>
                <p class="gemini-module-card__desc">
                  {{ $t('gemini.slashCommands.subtitle') }}
                </p>
                <span class="gemini-module-card__badge gemini-module-card__badge--secondary">Commands</span>
              </div>
            </Card>
          </RouterLink>
        </div>
      </section>

      <!-- INFO -->
      <section
        class="animate-slide-up"
        style="animation-delay: 200ms"
      >
        <Card
          variant="glass"
          class="gemini-info-card"
        >
          <div class="gemini-info-card__content">
            <div class="gemini-info-card__icon">
              <SIcon
                name="Info"
                size="w-6 h-6"
              />
            </div>
            <div class="gemini-info-card__body">
              <h3 class="gemini-info-card__title">
                💡 {{ $t('gemini.overview.welcome') }}
              </h3>
              <div class="gemini-info-grid">
                <div class="gemini-info-feature">
                  <div class="gemini-info-dot" />
                  <span class="gemini-info-feature__text">{{ $t('gemini.overview.feature1') }}</span>
                </div>
                <div class="gemini-info-feature">
                  <div class="gemini-info-dot" />
                  <span class="gemini-info-feature__text">{{ $t('gemini.overview.feature2') }}</span>
                </div>
                <div class="gemini-info-feature">
                  <div class="gemini-info-dot" />
                  <span class="gemini-info-feature__text">{{ $t('gemini.overview.feature3') }}</span>
                </div>
                <div class="gemini-info-feature">
                  <div class="gemini-info-dot" />
                  <span class="gemini-info-feature__text">{{ $t('gemini.overview.feature4') }}</span>
                </div>
              </div>
            </div>
          </div>
        </Card>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { RouterLink } from 'vue-router'
import AnimatedBackground from '@/components/common/AnimatedBackground.vue'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
</script>

<style scoped>
.gemini-view {
  @apply relative min-h-full overflow-hidden p-6 lg:p-10;
}

.gemini-shell {
  @apply relative z-10 mx-auto max-w-7xl space-y-8;
}

.gemini-header {
  @apply mb-8 flex flex-col justify-between gap-6 md:flex-row md:items-center;
}

.gemini-brand {
  @apply flex items-center gap-5;
}

.gemini-brand__icon {
  @apply flex h-16 w-16 items-center justify-center rounded-2xl border shadow-lg backdrop-blur-md;

  color: var(--platform-gemini);
  background: rgb(var(--color-platform-gemini-rgb) / 10%);
  border-color: rgb(var(--color-platform-gemini-rgb) / 20%);
}

.gemini-brand__title {
  @apply text-[2.6rem] font-semibold tracking-[-0.04em];

  font-family: var(--font-brand);
  color: var(--stage-text-primary);
}

.gemini-brand__subtitle {
  color: var(--stage-text-secondary);

  @apply mt-1 max-w-xl text-lg;
}

.gemini-home-button {
  @apply gap-2;
}

.gemini-tag-row {
  @apply flex flex-wrap gap-3;
}

.gemini-tag {
  @apply flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold;

  letter-spacing: 0.04em;
}

.gemini-tag--gemini {
  color: var(--platform-gemini);
  background: rgb(var(--color-platform-gemini-rgb) / 10%);
  border: 1px solid rgb(var(--color-platform-gemini-rgb) / 20%);
}

.gemini-tag--success {
  @apply border border-accent-success/20 bg-accent-success/10 text-accent-success;
}

.gemini-tag--claude {
  @apply border border-platform-claude/20 bg-platform-claude/10 text-platform-claude;
}

.gemini-tag--secondary {
  color: var(--color-accent-secondary);
  background: rgb(var(--color-accent-secondary-rgb) / 10%);
  border: 1px solid rgb(var(--color-accent-secondary-rgb) / 20%);
}

.gemini-section-heading {
  @apply mb-6 flex items-center gap-3;
}

.gemini-section-heading__icon {
  color: var(--platform-gemini);
}

.gemini-section-heading__title {
  color: var(--stage-text-muted);

  @apply text-lg font-semibold;

  letter-spacing: 0.04em;
}

.gemini-section-heading__rule {
  @apply h-px flex-1 bg-border-subtle;
}

.gemini-module-grid {
  @apply grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3;
}

.gemini-module-link {
  @apply block h-full;
}

.gemini-module-link--wide {
  @apply md:col-span-2 lg:col-span-1;
}

.gemini-module-card {
  @apply flex h-full items-start gap-4 p-6;
}

.gemini-module-card__icon {
  @apply rounded-xl p-3 transition-transform duration-300;
}

.gemini-module-link:hover .gemini-module-card__icon {
  transform: scale(1.1);
}

.gemini-module-card__icon--gemini {
  color: var(--platform-gemini);
  background: rgb(var(--color-platform-gemini-rgb) / 10%);
}

.gemini-module-card__icon--success {
  @apply bg-accent-success/10 text-accent-success;
}

.gemini-module-card__icon--claude {
  @apply bg-platform-claude/10 text-platform-claude;
}

.gemini-module-card__icon--secondary {
  color: var(--color-accent-secondary);
  background: rgb(var(--color-accent-secondary-rgb) / 10%);
}

.gemini-module-card__title {
  color: var(--stage-text-primary);

  @apply mb-1 text-lg font-semibold transition-colors;
}

.gemini-module-card__desc {
  color: var(--stage-text-secondary);

  @apply mb-3 text-sm leading-relaxed;
}

.gemini-module-card__badge {
  @apply inline-flex rounded border px-2 py-1 font-semibold;

  font-size: 10px;
  letter-spacing: 0.04em;
}

.gemini-module-link:hover .gemini-module-card__title--gemini {
  color: var(--platform-gemini);
}

.gemini-module-link:hover .gemini-module-card__title--success {
  @apply text-accent-success;
}

.gemini-module-link:hover .gemini-module-card__title--claude {
  @apply text-platform-claude;
}

.gemini-module-link:hover .gemini-module-card__title--secondary {
  color: var(--color-accent-secondary);
}

.gemini-module-card__badge--gemini {
  color: var(--platform-gemini);
  background: rgb(var(--color-platform-gemini-rgb) / 10%);
  border-color: rgb(var(--color-platform-gemini-rgb) / 20%);
}

.gemini-module-card__badge--success {
  @apply border-accent-success/20 bg-accent-success/10 text-accent-success;
}

.gemini-module-card__badge--claude {
  @apply border-platform-claude/20 bg-platform-claude/10 text-platform-claude;
}

.gemini-module-card__badge--secondary {
  color: var(--color-accent-secondary);
  background: rgb(var(--color-accent-secondary-rgb) / 10%);
  border-color: rgb(var(--color-accent-secondary-rgb) / 20%);
}

.gemini-info-card {
  @apply p-6;
}

.gemini-info-card__content {
  @apply flex items-start gap-4;
}

.gemini-info-card__icon {
  @apply shrink-0 rounded-xl p-3;

  color: var(--platform-gemini);
  background: rgb(var(--color-platform-gemini-rgb) / 10%);
}

.gemini-info-card__body {
  @apply space-y-4;
}

.gemini-info-card__title {
  color: var(--stage-text-primary);

  @apply text-lg font-semibold;
}

.gemini-info-grid {
  @apply grid grid-cols-1 gap-4 md:grid-cols-2;
}

.gemini-info-feature {
  background: var(--stage-surface-soft);
  border: 1px solid var(--stage-border-soft);

  @apply flex items-center gap-3 rounded-lg p-3;
}

.gemini-info-dot {
  @apply h-2 w-2 rounded-full;

  background: var(--platform-gemini);
  box-shadow: 0 0 6px rgb(var(--color-platform-gemini-rgb) / 28%);
}

.gemini-info-feature__text {
  color: var(--stage-text-secondary);

  @apply text-sm;
}
</style>

// ccr-ui/src/features/gemini/GeminiCliView.tsx
import { useCallback, useMemo, useState } from 'react'
import { Link } from 'react-router'
import { PageHeader, PageShell, SIcon } from '@/ui'
import { copyText } from '@/utils/clipboard'
import { GeminiSubnav } from './GeminiSubnav'
import { HeroTag, ModuleCard, QuickCard, TerminalRow } from './home/GeminiHomeGrids'
import { GeminiUsageStrip } from './home/GeminiUsageStrip'
import {
  geminiConfigPreview,
  geminiHeroTags,
  geminiModuleCards,
  geminiQuickCards,
  geminiTerminalSnippets,
} from './home/geminiHomeModel'
import { t } from './locale'

export function GeminiCliView() {
  const tags = useMemo(() => geminiHeroTags(), [])
  const snippets = useMemo(() => geminiTerminalSnippets(), [])
  const preview = useMemo(() => geminiConfigPreview(), [])
  const modules = useMemo(() => geminiModuleCards(), [])
  const quick = useMemo(() => geminiQuickCards(), [])
  const [copiedCommand, setCopiedCommand] = useState<string | null>(null)

  const copyCommand = useCallback(async (command: string) => {
    if (!(await copyText(command))) return
    setCopiedCommand(command)
    window.setTimeout(() => {
      setCopiedCommand((current) => (current === command ? null : current))
    }, 1600)
  }, [])

  return (
    <PageShell
      className="gemini-view bg-bg-elevated"
      header={
        <PageHeader
          title={t('gemini.overview.breadcrumb')}
          eyebrow={t('gemini.overview.hero.eyebrow')}
          description={t('gemini.overview.hero.description')}
          actions={
            <div className="flex flex-wrap gap-2">
              <Link
                to="/antigravity/mcp"
                className="inline-flex items-center rounded-lg bg-accent-primary px-3 py-2 text-sm text-[color:var(--color-accent-primary-contrast)]"
              >
                <SIcon name="Server" size="w-4 h-4" className="mr-2" />
                {t('gemini.overview.hero.primaryAction')}
              </Link>
              <Link
                to="/antigravity/slash-commands"
                className="inline-flex items-center rounded-lg border border-border-default px-3 py-2 text-sm"
              >
                <SIcon name="Command" size="w-4 h-4" className="mr-2" />
                {t('gemini.overview.hero.secondaryAction')}
              </Link>
              <Link to="/" className="inline-flex items-center rounded-lg px-3 py-2 text-sm text-text-secondary">
                <SIcon name="Home" size="w-4 h-4" className="mr-2" />
                {t('common.backToHome')}
              </Link>
            </div>
          }
        />
      }
      subnav={<GeminiSubnav />}
    >
      <div className="gemini-tag-row relative z-10 mt-2 flex flex-wrap gap-2.5">
        {tags.map((tag) => (
          <HeroTag key={tag.key} tag={tag} />
        ))}
      </div>

      <section className="mt-6">
        <article className="gemini-terminal-card relative overflow-hidden rounded-[2rem] border border-border-subtle bg-bg-surface p-5">
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-wide text-[color:var(--stage-text-muted)]">
                {t('gemini.overview.terminal.eyebrow')}
              </p>
              <h2 className="mt-1 text-xl font-semibold tracking-tight text-[color:var(--stage-text-primary)]">
                {t('gemini.overview.terminal.title')}
              </h2>
            </div>
            <div className="flex gap-1.5 rounded-full border border-[color:var(--stage-border-soft)] bg-[var(--stage-surface-soft)] px-2 py-1.5">
              <span className="h-2 w-2 rounded-full bg-accent-danger" />
              <span className="h-2 w-2 rounded-full bg-accent-warning" />
              <span className="h-2 w-2 rounded-full bg-accent-success" />
            </div>
          </div>
          <div className="mt-5 space-y-2">
            {snippets.map((snippet) => (
              <TerminalRow
                key={snippet.command}
                snippet={snippet}
                copied={copiedCommand === snippet.command}
                onCopy={copyCommand}
              />
            ))}
          </div>
          <div className="mt-4 grid gap-2 sm:grid-cols-2">
            {preview.map((item) => (
              <div key={item.label} className="rounded-2xl border border-[color:var(--stage-border-soft)] bg-[var(--stage-surface-soft)] p-3">
                <span className="block text-xs font-semibold uppercase tracking-wide text-[color:var(--stage-text-muted)]">
                  {item.label}
                </span>
                <code className="mt-1 block truncate font-mono text-xs text-[color:var(--stage-text-primary)]">{item.value}</code>
              </div>
            ))}
          </div>
        </article>
      </section>

      <div className="mt-6">
        <GeminiUsageStrip platform="antigravity" />
      </div>

      <section className="mt-6 space-y-5" aria-label="Gemini modules">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-[color:var(--stage-text-muted)]">
              {t('gemini.overview.modules.eyebrow')}
            </p>
            <h2 className="mt-1 text-2xl font-semibold tracking-tight text-[color:var(--stage-text-primary)]">
              {t('gemini.overview.modules.title')}
            </h2>
          </div>
          <p className="max-w-xl text-sm leading-6 text-[color:var(--stage-text-secondary)]">
            {t('gemini.overview.modules.subtitle')}
          </p>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
          {modules.map((item) => (
            <ModuleCard key={item.key} item={item} />
          ))}
        </div>
      </section>

      <section className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
        {quick.map((card) => (
          <QuickCard key={card.key} card={card} />
        ))}
      </section>
    </PageShell>
  )
}
