// ccr-ui/src/ui/async-state-panel.tsx
import { cn } from './cn'
import { SIcon } from './s-icon'
import { Spinner } from './spinner'

export type AsyncPanelState = 'loading' | 'error' | 'empty' | 'runtime-unavailable'

interface AsyncStatePanelProps {
  state: AsyncPanelState
  title: string
  description?: string
  icon?: string
  actionLabel?: string
  actionIcon?: string
  compact?: boolean
  onAction?: () => void
  className?: string
}

const iconNameOf = (state: AsyncPanelState, icon?: string): string => {
  if (icon) return icon
  if (state === 'error') return 'AlertCircle'
  if (state === 'runtime-unavailable') return 'MonitorOff'
  if (state === 'empty') return 'FileX'
  return 'Loader2'
}

export function AsyncStatePanel({
  state,
  title,
  description,
  icon,
  actionLabel,
  actionIcon,
  compact = false,
  onAction,
  className,
}: AsyncStatePanelProps) {
  const iconName = iconNameOf(state, icon)
  const iconClass =
    state === 'error'
      ? 'text-accent-danger'
      : state === 'runtime-unavailable'
        ? 'text-accent-secondary'
        : 'text-text-muted'
  const iconWrapClass =
    state === 'error'
      ? 'bg-danger/10 border-danger/18'
      : state === 'runtime-unavailable'
        ? 'bg-accent-primary/10 border-accent-primary/18'
        : 'bg-bg-surface border-border-default/55'

  return (
    <div
      className={cn('async-state-panel', compact && 'async-state-panel--compact', className)}
      role="status"
      aria-live="polite"
    >
      {state === 'loading' ? (
        <>
          <Spinner size="xl" className="text-accent-primary" />
          <p className="mt-3 text-sm text-text-secondary">{title}</p>
          {description ? (
            <p className="mt-1 text-center text-xs text-text-muted">{description}</p>
          ) : null}
        </>
      ) : (
        <>
          <div className={cn('async-state-panel__icon', iconWrapClass)}>
            <SIcon name={iconName} size="w-8 h-8" className={iconClass} />
          </div>
          <h3 className="mt-4 text-lg font-semibold text-text-primary">{title}</h3>
          {description ? (
            <p className="mt-2 max-w-[520px] text-center text-sm text-text-secondary">
              {description}
            </p>
          ) : null}
          {actionLabel ? (
            <button
              type="button"
              className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-xl bg-accent-primary px-4 py-2 text-sm font-medium text-text-inverted"
              onClick={onAction}
            >
              {actionIcon ? <SIcon name={actionIcon} size="w-4 h-4" /> : null}
              {actionLabel}
            </button>
          ) : null}
        </>
      )}
    </div>
  )
}

// ccr-ui/src/components/ui/AsyncStatePanel.vue
<template>
  <div
    class="async-state-panel"
    :class="panelClass"
    role="status"
    aria-live="polite"
  >
    <template v-if="state === 'loading'">
      <Spinner
        size="xl"
        class="text-accent-primary"
      />
      <p class="mt-3 text-sm text-text-secondary">
        {{ title }}
      </p>
      <p
        v-if="description"
        class="mt-1 text-center text-xs text-text-muted"
      >
        {{ description }}
      </p>
    </template>

    <template v-else>
      <div
        class="async-state-panel__icon"
        :class="iconContainerClass"
      >
        <SIcon
          :name="iconName"
          size="w-8 h-8"
          :class="iconClass"
        />
      </div>
      <h3 class="mt-4 text-lg font-semibold text-text-primary">
        {{ title }}
      </h3>
      <p
        v-if="description"
        class="mt-2 max-w-[520px] text-center text-sm text-text-secondary"
      >
        {{ description }}
      </p>
      <Button
        v-if="actionLabel"
        variant="primary"
        size="md"
        class="mt-5"
        @click="$emit('action')"
      >
        <template
          v-if="actionIcon"
          #leading
        >
          <SIcon
            :name="actionIcon"
            size="w-4 h-4"
          />
        </template>
        {{ actionLabel }}
      </Button>
    </template>
  </div>
</template>

<script setup lang="ts">
import Button from '@/components/ui/Button.vue'
import SIcon from '@/components/ui/SIcon.vue'
import Spinner from '@/components/ui/Spinner.vue'
import { computed } from 'vue'

type AsyncState = 'loading' | 'error' | 'empty' | 'runtime-unavailable'

const props = withDefaults(defineProps<{
  state: AsyncState
  title: string
  description?: string
  icon?: string
  actionLabel?: string
  actionIcon?: string
  compact?: boolean
}>(), {
  compact: false,
})

defineEmits<{
  (e: 'action'): void
}>()

const iconName = computed(() => {
  if (props.icon) return props.icon
  if (props.state === 'error') return 'AlertCircle'
  if (props.state === 'runtime-unavailable') return 'MonitorOff'
  if (props.state === 'empty') return 'FileX'
  return 'Loader2'
})

const iconClass = computed(() => {
  if (props.state === 'error') return 'text-accent-danger'
  if (props.state === 'runtime-unavailable') return 'text-accent-secondary'
  return 'text-text-muted'
})

const iconContainerClass = computed(() => {
  if (props.state === 'error') return 'bg-accent-danger/10 border-accent-danger/20'
  if (props.state === 'runtime-unavailable') return 'bg-accent-secondary/10 border-accent-secondary/20'
  return 'bg-bg-surface/80 border-border-default/60'
})

const panelClass = computed(() => (props.compact ? 'async-state-panel--compact' : ''))
</script>

<style scoped>
.async-state-panel {
  @apply flex flex-col items-center justify-center rounded-2xl px-6 py-16 text-center;

  background: var(--surface-workspace-bg);
  border: 1px solid var(--surface-workspace-border);
  box-shadow: var(--surface-workspace-shadow);
  backdrop-filter: var(--surface-workspace-blur);
}

.async-state-panel--compact {
  @apply py-12;
}

.async-state-panel__icon {
  @apply flex h-16 w-16 items-center justify-center rounded-full border;
}
</style>
