// ccr-ui/src/components/common/AnimatedBackground.vue
<template>
  <div
    :class="backgroundLayerClass"
    aria-hidden="true"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue'

type BackgroundVariant = 'default' | 'complex' | 'aurora' | 'spotlight' | 'mesh' | 'orbs' | 'minimal'
type SpotlightColor = 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'info'

// 氛围层收敛：组件壳保留（3 处挂载点不动），props 契约不变；
// halo / grain / spotlight 等动画层已随配色系统重构移除，统一渲染静态不透明基底。
const props = withDefaults(defineProps<{
  variant?: BackgroundVariant
  spotlightColor?: SpotlightColor
  contained?: boolean
  complex?: boolean
}>(), {
  variant: 'default',
  spotlightColor: 'primary',
  contained: false,
  complex: false,
})

const backgroundLayerClass = computed(() => (
  props.contained
    ? 'background-layer background-layer--contained absolute inset-0 overflow-hidden pointer-events-none -z-10 transition-colors duration-500'
    : 'background-layer fixed inset-0 overflow-hidden pointer-events-none -z-10 transition-colors duration-500'
))
</script>

<style scoped>
.background-layer {
  isolation: isolate;
  background: var(--color-bg-base);
}
</style>

// ccr-ui/src/shell/AnimatedBackground.tsx
import { cn } from '@/ui/cn'

type BackgroundVariant = 'default' | 'complex' | 'aurora' | 'spotlight' | 'mesh' | 'orbs' | 'minimal'

interface AnimatedBackgroundProps {
  variant?: BackgroundVariant
  contained?: boolean
}

/** 氛围层壳。动画层已收敛为静态基底，保留 props 以免消费方改签名。 */
export function AnimatedBackground({ contained = false }: AnimatedBackgroundProps) {
  return (
    <div
      className={cn(
        'background-layer overflow-hidden pointer-events-none -z-10 transition-colors duration-500',
        contained ? 'absolute inset-0' : 'fixed inset-0',
      )}
      aria-hidden="true"
    />
  )
}
