// ccr-ui/src/App.vue
<template>
  <AnimeBackground v-if="showGlobalBackground" />
  <Titlebar v-if="showCustomTitlebar" />
  <div
    class="flex h-screen w-screen flex-col overflow-hidden bg-bg-base"
    :class="{ 'pt-9': showCustomTitlebar }"
  >
    <RouterView class="flex-1 overflow-hidden" />
  </div>
  <ToastContainer />
  <GlobalConfirmDialog />
</template>

<script setup lang="ts">
import { computed, defineAsyncComponent } from 'vue'
import { useRoute } from 'vue-router'
import { shouldUseCustomTitlebar } from '@/utils/windowChrome'

const Titlebar = defineAsyncComponent({
  loader: () => import('@/components/layout/Titlebar.vue'),
  suspensible: false,
})

const ToastContainer = defineAsyncComponent({
  loader: () => import('@/components/common/ToastContainer.vue'),
  suspensible: false,
})

const AnimeBackground = defineAsyncComponent({
  loader: () => import('@/components/common/AnimeBackground.vue'),
  suspensible: false,
})

const GlobalConfirmDialog = defineAsyncComponent({
  loader: () => import('@/components/common/GlobalConfirmDialog.vue'),
  suspensible: false,
})

const route = useRoute()
const showCustomTitlebar = shouldUseCustomTitlebar()

const showGlobalBackground = computed(() => {
  return !route.meta.hideGlobalBackground
})
</script>

// ccr-ui/src/shell/App.tsx
import { Outlet } from 'react-router'
import { getWindowChromeTopInset, shouldUseCustomTitlebar } from '@/utils/windowChrome'
import { GlobalConfirmDialog } from './GlobalConfirmDialog'
import { StageBackground } from './StageBackground'
import { Titlebar } from './Titlebar'
import { ToastContainer } from './ToastContainer'
import { useRouteHandle } from './routeHandle'
import { useShellRuntime } from './useShellRuntime'

export function App() {
  useShellRuntime()
  const handle = useRouteHandle()
  const showCustomTitlebar = shouldUseCustomTitlebar()
  const inset = getWindowChromeTopInset()

  return (
    <>
      {handle.hideGlobalBackground ? null : <StageBackground />}
      {showCustomTitlebar ? <Titlebar /> : null}
      <div
        className="flex h-screen w-screen flex-col overflow-hidden bg-bg-base"
        style={inset > 0 ? { paddingTop: `${inset}px` } : undefined}
      >
        <Outlet />
      </div>
      <ToastContainer />
      <GlobalConfirmDialog />
    </>
  )
}
