// ccr-ui/src/components/ModuleSubnav.vue
<template>
  <nav
    v-if="items.length > 0"
    class="module-subnav"
    aria-label="Module navigation"
  >
    <template
      v-for="item in items"
      :key="item.href"
    >
      <RouterLink
        v-if="!item.localOnly || isLocalEnvironment"
        :to="item.href"
        class="module-subnav__item"
        :class="{ 'module-subnav__item--active': isActive(item.href) }"
        :aria-current="isActive(item.href) ? 'page' : undefined"
      >
        <SIcon
          :name="item.icon"
          size="w-4 h-4"
        />
        <span>{{ item.labelKey ? t(item.labelKey) : item.label }}</span>
      </RouterLink>
      <span
        v-else
        class="module-subnav__item module-subnav__item--disabled"
        :title="t('settingsRaw.unsupportedEnvironment')"
        aria-disabled="true"
      >
        <SIcon
          :name="item.icon"
          size="w-4 h-4"
        />
        <span>{{ item.labelKey ? t(item.labelKey) : item.label }}</span>
      </span>
    </template>
  </nav>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'
import SIcon from '@/components/ui/SIcon.vue'
import { getModuleSubnavItems } from '@/config/moduleSubnav'
import { getCurrentEnvironment } from '@/api'

interface Props {
  module: string
}

const props = defineProps<Props>()
const route = useRoute()
const { t } = useI18n()
const isLocalEnvironment = ref(false)

const items = computed(() => getModuleSubnavItems(props.module))
const activeHref = computed(() => {
  return items.value
    .map(item => item.href)
    .filter(href => route.path === href || route.path.startsWith(`${href}/`))
    .sort((left, right) => right.length - left.length)[0]
})

const isActive = (href: string) => activeHref.value === href

onMounted(async () => {
  if (!items.value.some(item => item.localOnly)) {
    isLocalEnvironment.value = true
    return
  }
  try {
    const environment = await getCurrentEnvironment()
    isLocalEnvironment.value = !environment || environment.env_type === 'local'
  } catch {
    isLocalEnvironment.value = false
  }
})
</script>

<style scoped>
.module-subnav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  padding: 0.75rem;
  border-radius: 1rem;
  background: var(--surface-status-bg);
  border: 1px solid var(--surface-status-border);
  backdrop-filter: var(--surface-status-blur);
}

.module-subnav__item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  min-height: 2.5rem;
  padding: 0.5rem 0.875rem;
  border-radius: 0.75rem;
  color: var(--color-text-secondary);
  border: 1px solid transparent;
  transition: color 150ms ease, background-color 150ms ease, border-color 150ms ease;
}

.module-subnav__item:hover {
  color: var(--color-text-primary);
  background: rgb(var(--color-bg-surface-rgb) / 70%);
  border-color: rgb(var(--color-border-default-rgb) / 70%);
}

.module-subnav__item--active {
  color: var(--color-accent-primary);
  background: rgb(var(--color-accent-primary-rgb) / 10%);
  border-color: rgb(var(--color-accent-primary-rgb) / 25%);
  box-shadow: 0 8px 24px rgb(var(--color-accent-primary-rgb) / 10%);
}

.module-subnav__item--disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>

// ccr-ui/src/shell/ModuleSubnav.tsx
import { useEffect, useState } from 'react'
import { NavLink, useLocation } from 'react-router'
import { getCurrentEnvironment } from '@/api'
import { getModuleSubnavItems } from '@/config/moduleSubnav'
import { useShellT } from '@/shell/i18n'
import { SIcon } from '@/ui/s-icon'

interface ModuleSubnavProps {
  module: string
}

export function ModuleSubnav({ module }: ModuleSubnavProps) {
  const t = useShellT()
  const location = useLocation()
  const items = getModuleSubnavItems(module)
  const [isLocalEnvironment, setIsLocalEnvironment] = useState(false)

  useEffect(() => {
    const needsLocal = getModuleSubnavItems(module).some((item) => item.localOnly)
    if (!needsLocal) {
      setIsLocalEnvironment(true)
      return
    }
    void getCurrentEnvironment()
      .then((environment) => {
        setIsLocalEnvironment(!environment || environment.env_type === 'local')
      })
      .catch(() => setIsLocalEnvironment(false))
  }, [module])

  const activeHref = items
    .map((item) => item.href)
    .filter((href) => location.pathname === href || location.pathname.startsWith(`${href}/`))
    .sort((left, right) => right.length - left.length)[0]

  if (items.length === 0) return null

  return (
    <nav className="module-subnav" aria-label="Module navigation">
      {items.map((item) => {
        const label = item.labelKey ? t(item.labelKey) : item.label
        if (item.localOnly && !isLocalEnvironment) {
          return (
            <span
              key={item.href}
              className="module-subnav__item module-subnav__item--disabled"
              title={t('settingsRaw.unsupportedEnvironment')}
              aria-disabled="true"
            >
              <SIcon name={item.icon} size="w-4 h-4" />
              <span>{label}</span>
            </span>
          )
        }
        return (
          <NavLink
            key={item.href}
            to={item.href}
            className={
              activeHref === item.href
                ? 'module-subnav__item module-subnav__item--active'
                : 'module-subnav__item'
            }
            aria-current={activeHref === item.href ? 'page' : undefined}
          >
            <SIcon name={item.icon} size="w-4 h-4" />
            <span>{label}</span>
          </NavLink>
        )
      })}
    </nav>
  )
}
