// ccr-ui/src/components/ThemeToggle.vue
<template>
  <button
    type="button"
    class="inline-flex min-h-[44px] min-w-[44px] flex-shrink-0 items-center justify-center rounded-full border p-0 leading-none text-text-secondary shadow-sm transition-interactive duration-200 hover:text-accent-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-primary/30 focus-visible:ring-offset-2 focus-visible:ring-offset-bg-base active:scale-95"
    :title="`切换到${currentTheme === 'dark' ? '明亮' : '深色'}模式`"
    :aria-label="`切换到${currentTheme === 'dark' ? '明亮' : '深色'}模式`"
    style="background: var(--surface-status-bg); border-color: var(--surface-status-border); backdrop-filter: var(--surface-status-blur); box-shadow: var(--surface-status-shadow), inset 0 1px 0 rgb(255 251 245 / 12%);"
    @click.stop="toggleTheme"
  >
    <SIcon
      v-if="currentTheme === 'dark'"
      name="Moon"
      size="w-4 h-4"
      class="pointer-events-none block"
    />
    <SIcon
      v-else
      name="Sun"
      size="w-4 h-4"
      class="pointer-events-none block"
    />
  </button>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { computed } from 'vue'
import { useShellPreferencesStore } from '@/stores/shellPreferences'

const shellPreferencesStore = useShellPreferencesStore()

const currentTheme = computed(() => shellPreferencesStore.effectiveTheme)

const toggleTheme = () => {
  shellPreferencesStore.toggleTheme()
}
</script>

// ccr-ui/src/shell/ThemeToggle.tsx
import { useShellPreferencesStore } from '@/shell/stores/shellPreferences'
import { SIcon } from '@/ui/s-icon'

export function ThemeToggle() {
  const theme = useShellPreferencesStore((state) => state.effectiveTheme)
  const toggleTheme = useShellPreferencesStore((state) => state.toggleTheme)
  const nextLabel = theme === 'dark' ? '明亮' : '深色'

  return (
    <button
      type="button"
      className="inline-flex min-h-11 min-w-11 flex-shrink-0 items-center justify-center rounded-full border p-0 leading-none text-text-secondary shadow-sm transition-interactive duration-200 hover:text-accent-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-primary/30"
      title={`切换到${nextLabel}模式`}
      aria-label={`切换到${nextLabel}模式`}
      style={{
        background: 'var(--surface-status-bg)',
        borderColor: 'var(--surface-status-border)',
      }}
      onClick={(event) => {
        event.stopPropagation()
        toggleTheme()
      }}
    >
      <SIcon name={theme === 'dark' ? 'Moon' : 'Sun'} size="w-4 h-4" className="pointer-events-none block" />
    </button>
  )
}
