// ccr-ui/src/components/AddConfigModal.vue
<!-- -->
<template>
  <BaseModal
    :model-value="isOpen"
    size="4xl"
    scrollable
    surface="solid"
    :title="$t('configs.addConfig.title')"
    @update:model-value="(value: boolean) => { if (!value) handleClose() }"
    @close="handleClose"
  >
    <!-- Header -->
    <template #header="{ titleId }">
      <div class="flex items-center gap-3">
        <div class="p-2 rounded-lg bg-accent-success/10 text-accent-success">
          <SIcon
            name="Plus"
            size="w-5 h-5"
          />
        </div>
        <div>
          <h2
            :id="titleId"
            class="text-lg font-bold text-text-primary"
          >
            {{ $t('configs.addConfig.title') }}
          </h2>
          <p class="text-xs text-text-secondary">
            {{ $t('configs.addConfig.subtitle') }}
          </p>
        </div>
      </div>
    </template>

    <!-- Preset Provider Selection -->
    <ProviderTemplateSelector
      platform="claude"
      :selected-template-id="selectedTemplate"
      :selected-endpoint="selectedEndpoint"
      :draft-context="claudeLegacyTemplateDraft"
      label="Provider template"
      helper="Search built-in and custom non-secret templates, then fill provider fields in one step."
      @select="applyTemplate"
      @manual="applyManualTemplate"
    />

    <div class="h-px bg-border-subtle my-6" />

    <!-- Form -->
    <form
      class="space-y-6"
      @submit.prevent="handleSave"
    >
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Input
          v-model="formData.name"
          :label="$t('configs.addConfig.name')"

          :placeholder="$t('configs.addConfig.namePlaceholder')"
        >
          <template #leading>
            <span class="text-text-muted">#</span>
          </template>
        </Input>

        <Input
          v-model="formData.description"
          :label="$t('configs.addConfig.description')"
          :placeholder="$t('configs.addConfig.descriptionPlaceholder')"
        >
          <template #leading>
            <SIcon
              name="FileText"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <Input
          v-model="formData.base_url"
          label="Base URL"

          placeholder="https://api.example.com"
          class="md:col-span-2"
        >
          <template #leading>
            <SIcon
              name="Globe"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <Input
          v-model="formData.auth_token"
          label="Auth Token"

          type="password"
          :placeholder="$t('configs.addConfig.tokenPlaceholder')"
          class="md:col-span-2"
        >
          <template #leading>
            <SIcon
              name="KeyRound"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <Input
          v-model="formData.model"
          label="Model"
          :placeholder="$t('configs.addConfig.modelPlaceholder')"
        >
          <template #leading>
            <SIcon
              name="Bot"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <Input
          v-model="formData.small_fast_model"
          label="Fast Model"
          :placeholder="$t('configs.addConfig.smallModelPlaceholder')"
        >
          <template #leading>
            <SIcon
              name="Zap"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <div class="w-full">
          <label class="block text-xs font-bold uppercase tracking-wider text-text-muted mb-1.5 ml-1">
            {{ $t('configs.addConfig.providerType') }}
          </label>
          <div class="relative">
            <select
              v-model="formData.provider_type"
              class="w-full bg-bg-elevated border border-border-default rounded-xl px-4 py-2.5 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-accent-primary/20 appearance-none hover:border-border-strong cursor-pointer"
            >
              <option value="">
                {{ $t('configs.addConfig.providerUncategorized') }}
              </option>
              <option value="official_relay">
                {{ $t('configs.addConfig.providerOfficialRelay') }}
              </option>
              <option value="third_party_model">
                {{ $t('configs.addConfig.providerThirdParty') }}
              </option>
            </select>
            <div class="absolute inset-y-0 right-3 flex items-center pointer-events-none text-text-muted">
              <SIcon
                name="ChevronDown"
                size="w-4 h-4"
              />
            </div>
          </div>
        </div>

        <Input
          v-model="formData.provider"
          :label="$t('configs.addConfig.providerName')"
          :placeholder="$t('configs.addConfig.providerNamePlaceholder')"
          :hint="$t('configs.addConfig.providerNameHint')"
        >
          <template #leading>
            <SIcon
              name="Building2"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <Input
          v-model="formData.account"
          :label="$t('configs.addConfig.account')"
          :placeholder="$t('configs.addConfig.accountPlaceholder')"
          :hint="$t('configs.addConfig.accountHint')"
        >
          <template #leading>
            <SIcon
              name="User"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>

        <Input
          v-model="tagsInput"
          :label="$t('configs.addConfig.tags')"
          :placeholder="$t('configs.addConfig.tagsPlaceholder')"
          :hint="$t('configs.addConfig.tagsHint')"
        >
          <template #leading>
            <SIcon
              name="Tags"
              size="w-4 h-4"
              class="text-text-muted"
            />
          </template>
        </Input>
      </div>
    </form>

    <!-- Footer -->
    <template #footer>
      <Button
        variant="ghost"
        @click="handleClose"
      >
        Cancel
      </Button>
      <Button
        variant="primary"
        :loading="saving"
        :disabled="!isFormValid"
        @click="handleSave"
      >
        {{ saving ? $t('configs.addConfig.saving') : $t('configs.addConfig.save') }}
      </Button>
    </template>
  </BaseModal>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { addConfig } from '@/api'
import BaseModal from '@/components/common/BaseModal.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import ProviderTemplateSelector from '@/components/provider-templates/ProviderTemplateSelector.vue'
import { useUIStore } from '@/stores/ui'
import type { UpdateConfigRequest } from '@/types'
import type { ProviderTemplateDraftContext, ProviderTemplateSelection } from '@/types/providerTemplates'
import { mapTemplateToClaudeLegacyConfigPatch } from '@/utils/providerTemplates'

const props = defineProps<{ isOpen: boolean }>()
const emit = defineEmits(['close', 'saved'])
useI18n()

const handleClose = () => emit('close')

// Form Logic
const uiStore = useUIStore()
const saving = ref(false)
const selectedTemplate = ref<string | null>(null)
const selectedEndpoint = ref('')
const tagsInput = ref('')
const formData = ref<UpdateConfigRequest>({
  name: '', description: '', base_url: '', auth_token: '',
  model: '', small_fast_model: '', provider: '',
  provider_type: '', account: '', tags: []
})

const isFormValid = computed(() =>
  formData.value.name.trim() && formData.value.base_url.trim() && formData.value.auth_token.trim()
)

const claudeLegacyTemplateDraft = computed<ProviderTemplateDraftContext>(() => ({
  platform: 'claude',
  defaultName: formData.value.provider || formData.value.name || 'Claude provider',
  name: formData.value.provider || formData.value.name,
  category: 'third_party',
  baseUrls: formData.value.base_url.trim() ? [formData.value.base_url.trim()] : [],
  modelCatalog: [formData.value.model, formData.value.small_fast_model].filter(Boolean) as string[],
  platformOverride: {
    baseUrl: formData.value.base_url,
    provider: formData.value.provider,
    providerType: formData.value.provider_type,
    model: formData.value.model,
    smallFastModel: formData.value.small_fast_model,
    description: formData.value.description,
  },
}))

const applyManualTemplate = () => {
  selectedTemplate.value = null
  selectedEndpoint.value = ''
  formData.value = {
    name: '', description: '', base_url: '', auth_token: '',
    model: '', small_fast_model: '', provider: '',
    provider_type: '', account: '', tags: [],
  }
}

const applyTemplate = (selection: ProviderTemplateSelection) => {
  const patch = mapTemplateToClaudeLegacyConfigPatch(selection.template, selection.endpoint)

  selectedTemplate.value = selection.template.id
  selectedEndpoint.value = selection.endpoint || ''
  formData.value = {
    ...formData.value,
    base_url: patch.base_url || '',
    model: patch.model || '',
    small_fast_model: patch.small_fast_model || '',
    provider: patch.provider || selection.template.name,
    provider_type: patch.provider_type || '',
    description: patch.description || formData.value.description,
  }

  if (!formData.value.name) {
    formData.value.name = patch.suggestedName || selection.template.id
  }
}

const handleSave = async () => {
  if (!isFormValid.value) return
  saving.value = true
  try {
    const tags = tagsInput.value.split(',').map(t => t.trim()).filter(Boolean)
    await addConfig({ ...formData.value, tags: tags.length ? tags : undefined })
    uiStore.showSuccess('Configuration added successfully')
    emit('saved')
    handleClose()
  } catch (e) {
    uiStore.showError((e instanceof Error ? e.message : "Error") || 'Failed to add configuration')
  }
  finally { saving.value = false }
}

const resetForm = () => {
  formData.value = { name: '', description: '', base_url: '', auth_token: '', model: '', small_fast_model: '', provider: '', provider_type: '', account: '', tags: [] }
  tagsInput.value = ''
  selectedTemplate.value = null
  selectedEndpoint.value = ''
}

watch(() => props.isOpen, val => val && resetForm())
</script>

// ccr-ui/src/features/configs/components/AddConfigModal.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { addConfig } from '@/api'
import { getErrorMessage } from '@/utils/errorHandler'
import { mapTemplateToClaudeLegacyConfigPatch } from '@/utils/providerTemplates'
import type { ProviderTemplateSelection } from '@/types/providerTemplates'
import { BaseModal, SIcon } from '@/ui'
import { t } from '../locale'
import { configsNotify } from '../notify'
import {
  addConfigFormSchema,
  draftContextFromValues,
  emptyConfigForm,
  toConfigPatch,
  type ConfigFormValues,
} from '../lib/configForm'
import { NEW_CONFIG_DRAFT_ID } from '../types'
import { useConfigsViewStore } from '../stores'
import { ProviderTemplateSelector } from '../provider-templates/ProviderTemplateSelector'
import { ConfigFormFields } from './ConfigFormFields'

interface AddConfigModalProps {
  isOpen: boolean
  onClose: () => void
  onSaved: () => void
}

export function AddConfigModal({ isOpen, onClose, onSaved }: AddConfigModalProps) {
  const setFormDraft = useConfigsViewStore((state) => state.setFormDraft)
  const clearFormDraft = useConfigsViewStore((state) => state.clearFormDraft)
  const [saving, setSaving] = useState(false)
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null)
  const [selectedEndpoint, setSelectedEndpoint] = useState('')
  const form = useForm<ConfigFormValues>({
    resolver: zodResolver(addConfigFormSchema),
    defaultValues: emptyConfigForm(),
  })
  const { register, handleSubmit, reset, setValue, getValues } = form

  useEffect(() => {
    if (!isOpen) return
    const formDraft = useConfigsViewStore.getState().formDrafts[NEW_CONFIG_DRAFT_ID]
    const draft = formDraft && typeof formDraft === 'object' ? { ...emptyConfigForm(), ...(formDraft as object) } : emptyConfigForm()
    reset({ ...draft, auth_token: '' } as ConfigFormValues)
    setSelectedTemplateId(null)
    setSelectedEndpoint('')
  }, [isOpen, reset])

  useEffect(() => {
    if (!isOpen) return
    const sub = form.watch((values) => {
      setFormDraft(NEW_CONFIG_DRAFT_ID, { ...values, auth_token: '' })
    })
    return () => sub.unsubscribe()
  }, [form, isOpen, setFormDraft])

  const getDraftContext = useCallback(() => draftContextFromValues(getValues()), [getValues])

  const applyManual = useCallback(() => {
    setSelectedTemplateId(null)
    setSelectedEndpoint('')
    reset(emptyConfigForm())
  }, [reset])

  const applyTemplate = useCallback(
    (selection: ProviderTemplateSelection) => {
      const patch = mapTemplateToClaudeLegacyConfigPatch(selection.template, selection.endpoint)
      setSelectedTemplateId(selection.template.id)
      setSelectedEndpoint(selection.endpoint || '')
      setValue('base_url', patch.base_url || '')
      setValue('model', patch.model || '')
      setValue('small_fast_model', patch.small_fast_model || '')
      setValue('provider', patch.provider || selection.template.name)
      setValue('provider_type', patch.provider_type || '')
      if (patch.description) setValue('description', patch.description)
      if (!getValues('name')) setValue('name', patch.suggestedName || selection.template.id)
    },
    [getValues, setValue],
  )

  const onValid = useCallback(
    async (values: ConfigFormValues) => {
      setSaving(true)
      try {
        await addConfig({ platform: 'claude', name: values.name.trim(), data: toConfigPatch(values) })
        configsNotify.success('Configuration added successfully')
        clearFormDraft(NEW_CONFIG_DRAFT_ID)
        onSaved()
        onClose()
      } catch (error) {
        configsNotify.error(getErrorMessage(error) || 'Failed to add configuration')
      } finally {
        setSaving(false)
      }
    },
    [clearFormDraft, onClose, onSaved],
  )

  const onSubmit = useMemo(() => handleSubmit(onValid), [handleSubmit, onValid])
  const handleOpenChange = useCallback(
    (open: boolean) => {
      if (!open) onClose()
    },
    [onClose],
  )

  const renderHeader = useCallback(
    (scope: { titleId: string }) => (
      <div className="flex items-center gap-3">
        <div className="rounded-lg bg-accent-success/10 p-2 text-accent-success">
          <SIcon name="Plus" size="w-5 h-5" />
        </div>
        <div>
          <h2 id={scope.titleId} className="text-lg font-bold text-text-primary">
            {t('configs.addConfig.title')}
          </h2>
          <p className="text-xs text-text-secondary">{t('configs.addConfig.subtitle')}</p>
        </div>
      </div>
    ),
    [],
  )

  return (
    <BaseModal
      modelValue={isOpen}
      size="4xl"
      scrollable
      surface="solid"
      title={t('configs.addConfig.title')}
      header={renderHeader}
      onUpdateModelValue={handleOpenChange}
      onClose={onClose}
      footer={
        <>
          <button type="button" className="rounded-lg px-4 py-2 text-sm text-text-secondary" onClick={onClose}>
            {t('common.cancel')}
          </button>
          <button
            type="button"
            className="rounded-lg bg-accent-primary px-4 py-2 text-sm text-[color:var(--color-accent-primary-contrast)] disabled:opacity-50"
            disabled={saving}
            onClick={onSubmit}
          >
            {saving ? t('configs.addConfig.saving') : t('configs.addConfig.save')}
          </button>
        </>
      }
    >
      <ProviderTemplateSelector
        platform="claude"
        selectedTemplateId={selectedTemplateId}
        selectedEndpoint={selectedEndpoint}
        getDraftContext={getDraftContext}
        label="Provider template"
        helper="Search built-in and custom non-secret templates, then fill provider fields in one step."
        onSelect={applyTemplate}
        onManual={applyManual}
      />
      <div className="my-6 h-px bg-border-subtle" />
      <form className="space-y-6" onSubmit={onSubmit}>
        <ConfigFormFields register={register} showName />
      </form>
    </BaseModal>
  )
}
