// ccr-ui/src/components/configs/ConfigFilters.vue
<template>
  <div class="flex gap-4 mb-6 items-center">
    <!-- 筛选按钮组 - Enhanced Glass Style -->
    <div class="flex gap-2 flex-1 p-1.5 rounded-2xl glass-filter-container">
      <button
        v-for="filter in filters"
        :key="filter.type"
        class="filter-btn flex-1 py-2.5 px-4 rounded-xl text-sm font-semibold transition-colors duration-300 flex items-center justify-center gap-2"
        :class="{ 'filter-btn-active': currentFilter === filter.type }"
        @click="$emit('update:currentFilter', filter.type)"
      >
        <SIcon
          :name="filter.icon"
          size="w-4 h-4"
          :class="currentFilter === filter.type ? 'text-[color:var(--color-accent-primary-contrast)]' : filter.iconColor"
        />
        <span>{{ filter.label }}</span>
      </button>
    </div>

    <!-- 排序和操作区 -->
    <div class="flex items-center gap-3">
      <!-- 排序下拉菜单 -->
      <div class="flex items-center gap-2">
        <label class="text-sm font-medium whitespace-nowrap text-text-primary">
          {{ $t('configs.sort.label') }}
        </label>
        <div class="relative">
          <select
            :value="currentSort"
            class="sort-select appearance-none pl-9 pr-8 py-2.5 rounded-xl text-sm font-semibold transition-colors cursor-pointer outline-none"
            @change="$emit('update:currentSort', ($event.target as HTMLSelectElement).value as SortType)"
          >
            <option value="name">
              {{ $t('configs.sort.name') }}
            </option>
            <option value="usage_count">
              {{ $t('configs.sort.usageCount') }}
            </option>
            <option value="recent">
              {{ $t('configs.sort.recent') }}
            </option>
          </select>
          <SIcon
            :name="sortIcons[currentSort]"
            size="w-4 h-4"
            class="absolute left-3 top-1/2 -translate-y-1/2 text-accent-primary pointer-events-none"
          />
          <SIcon
            name="ChevronDown"
            size="w-4 h-4"
            class="absolute right-2.5 top-1/2 -translate-y-1/2 text-text-muted pointer-events-none"
          />
        </div>
      </div>

      <!-- 提供商统计按钮 -->
      <button
        class="stats-btn px-3 py-2.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-colors duration-200"
        @click="$emit('showProviderStats')"
      >
        <SIcon
          name="BarChart3"
          size="w-4 h-4"
        />
        <span>{{ $t('configs.provider.title') }}</span>
      </button>

      <!-- 添加配置按钮 -->
      <button
        class="add-btn px-4 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 text-[color:var(--color-accent-primary-contrast)] transition-[background-color,transform] duration-200 hover:scale-105"
        @click="$emit('addConfig')"
      >
        <SIcon
          name="PlusCircle"
          size="w-4 h-4"
        />
        <span>{{ $t('configs.buttons.add') }}</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { useI18n } from 'vue-i18n'
import { computed } from 'vue'

type FilterType = 'all' | 'official_relay' | 'third_party_model' | 'uncategorized'
type SortType = 'name' | 'usage_count' | 'recent'

interface Props {
  currentFilter: FilterType
  currentSort: SortType
}

defineProps<Props>()

interface Emits {
  (e: 'update:currentFilter', value: FilterType): void
  (e: 'update:currentSort', value: SortType): void
  (e: 'showProviderStats'): void
  (e: 'addConfig'): void
}

defineEmits<Emits>()

const { t } = useI18n()

// Sort icons mapping
const sortIcons = {
  name: 'FileText',
  usage_count: 'TrendingUp',
  recent: 'Clock'
}

// 筛选选项 - 使用 SVG 图标替代 emoji
const filters = computed(() => [
  {
    type: 'all' as FilterType,
    label: t('configs.filters.all'),
    icon: 'LayoutGrid',
    iconColor: 'text-emerald-400'
  },
  {
    type: 'official_relay' as FilterType,
    label: t('configs.filters.officialRelay'),
    icon: 'Zap',
    iconColor: 'text-cyan-400'
  },
  {
    type: 'third_party_model' as FilterType,
    label: t('configs.filters.thirdPartyModel'),
    icon: 'Cpu',
    iconColor: 'text-violet-400'
  },
  {
    type: 'uncategorized' as FilterType,
    label: t('configs.filters.uncategorized'),
    icon: 'HelpCircle',
    iconColor: 'text-amber-400'
  },
])
</script>

<style scoped>
/* Glass filter container */
.glass-filter-container {
  background: var(--surface-status-bg);
  backdrop-filter: var(--surface-status-blur);
  border: 1px solid var(--surface-status-border);
  box-shadow: var(--shadow-sm);
}

/* Filter button base */
.filter-btn {
  background: transparent;
  color: var(--text-secondary);
  border: 1px solid transparent;
}

.filter-btn:hover:not(.filter-btn-active) {
  background: var(--glass-bg-medium);
  color: var(--text-primary);
}

/* Filter button active state */
.filter-btn-active {
  background: var(--color-accent-primary);
  color: var(--color-accent-primary-contrast);
  border-color: transparent;
  box-shadow: none;
}

/* Sort select */
.sort-select {
  background: var(--surface-status-bg);
  backdrop-filter: var(--surface-status-blur);
  border: 1px solid var(--surface-status-border);
  color: var(--text-primary);
  min-width: 140px;
}

.sort-select:hover {
  border-color: var(--color-accent-primary);
}

.sort-select:focus {
  border-color: var(--color-accent-primary);
  box-shadow: 0 0 0 3px rgb(var(--color-accent-primary-rgb) / 15%);
}

/* Stats button */
.stats-btn {
  background: var(--glass-bg-light);
  border: 1px solid var(--glass-border-light);
  color: var(--text-secondary);
}

.stats-btn:hover {
  background: var(--glass-bg-medium);
  border-color: var(--color-accent-primary);
  color: var(--color-accent-primary);
}

/* Add button */
.add-btn {
  background: var(--color-accent-primary);
  box-shadow: none;
}

.add-btn:hover {
  box-shadow: 0 6px 24px rgb(var(--color-accent-primary-rgb) / 40%);
}
</style>

// ccr-ui/src/features/configs/components/ConfigFilters.tsx
import { memo, useCallback, useMemo } from 'react'
import { SIcon } from '@/ui'
import { t } from '../locale'
import type { ConfigFilter, ConfigSort } from '../types'
import { FilterChip } from './FilterChip'
import '../styles/config-filters.css'

interface ConfigFiltersProps {
  currentFilter: ConfigFilter
  currentSort: ConfigSort
  onUpdateFilter: (value: ConfigFilter) => void
  onUpdateSort: (value: ConfigSort) => void
  onShowProviderStats: () => void
  onAddConfig: () => void
}

const SORT_ICONS: Record<ConfigSort, string> = {
  name: 'FileText',
  usage_count: 'TrendingUp',
  recent: 'Clock',
}

export const ConfigFilters = memo(function ConfigFilters({
  currentFilter,
  currentSort,
  onUpdateFilter,
  onUpdateSort,
  onShowProviderStats,
  onAddConfig,
}: ConfigFiltersProps) {
  const filters = useMemo(
    () => [
      { type: 'all' as const, label: t('configs.filters.all'), icon: 'LayoutGrid', iconColor: 'text-emerald-400' },
      {
        type: 'official_relay' as const,
        label: t('configs.filters.officialRelay'),
        icon: 'Zap',
        iconColor: 'text-cyan-400',
      },
      {
        type: 'third_party_model' as const,
        label: t('configs.filters.thirdPartyModel'),
        icon: 'Cpu',
        iconColor: 'text-violet-400',
      },
      {
        type: 'uncategorized' as const,
        label: t('configs.filters.uncategorized'),
        icon: 'HelpCircle',
        iconColor: 'text-amber-400',
      },
    ],
    [],
  )

  const handleSort = useCallback(
    (event: { target: EventTarget | null }) => {
      const value = (event.target as HTMLSelectElement).value as ConfigSort
      onUpdateSort(value)
    },
    [onUpdateSort],
  )

  return (
    <div className="mb-6 flex items-center gap-4">
      <div className="glass-filter-container flex flex-1 gap-2 rounded-2xl p-1.5">
        {filters.map((filter) => (
          <FilterChip
            key={filter.type}
            type={filter.type}
            label={filter.label}
            icon={filter.icon}
            iconColor={filter.iconColor}
            active={currentFilter === filter.type}
            onSelect={onUpdateFilter}
          />
        ))}
      </div>
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-2">
          <label className="whitespace-nowrap text-sm font-medium text-text-primary">{t('configs.sort.label')}</label>
          <div className="relative">
            <select value={currentSort} className="sort-select appearance-none rounded-xl py-2.5 pr-8 pl-9 text-sm font-semibold" onChange={handleSort}>
              <option value="name">{t('configs.sort.name')}</option>
              <option value="usage_count">{t('configs.sort.usageCount')}</option>
              <option value="recent">{t('configs.sort.recent')}</option>
            </select>
            <SIcon
              name={SORT_ICONS[currentSort]}
              size="w-4 h-4"
              className="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-accent-primary"
            />
            <SIcon
              name="ChevronDown"
              size="w-4 h-4"
              className="pointer-events-none absolute top-1/2 right-2.5 -translate-y-1/2 text-text-muted"
            />
          </div>
        </div>
        <button
          type="button"
          className="stats-btn flex items-center gap-1.5 rounded-xl px-3 py-2.5 text-xs font-semibold transition-colors duration-200"
          onClick={onShowProviderStats}
        >
          <SIcon name="BarChart3" size="w-4 h-4" />
          <span>{t('configs.provider.title')}</span>
        </button>
        <button
          type="button"
          className="add-btn flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-[color:var(--color-accent-primary-contrast)] transition-[background-color,transform] duration-200 hover:scale-105"
          onClick={onAddConfig}
        >
          <SIcon name="PlusCircle" size="w-4 h-4" />
          <span>{t('configs.buttons.add')}</span>
        </button>
      </div>
    </div>
  )
})
