// ccr-ui/src/components/ConfigCard.vue
<template>
  <div
    v-bind="{ 'data-config-name': config.name }"
    class="config-row group relative flex items-stretch transition-colors duration-300 rounded-xl overflow-hidden"
    :class="{
      'config-row--current': config.is_current,
      'config-row--disabled': config.enabled === false,
    }"
  >
    <!-- Left Accent Bar -->
    <div
      class="accent-bar w-[3px] shrink-0 transition-colors duration-300"
      :class="accentBarClass"
    />

    <!-- Main Content -->
    <button
      type="button"
      class="config-row-main flex-1 flex items-center gap-4 px-5 py-4 min-w-0 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-primary/35 focus-visible:ring-offset-2 focus-visible:ring-offset-bg-base"
      :aria-label="t('common.edit') + ': ' + config.name"
      @click="emit('edit', config.name)"
    >
      <!-- Provider Avatar -->
      <div
        class="avatar-wrapper relative shrink-0 w-10 h-10 rounded-xl flex items-center justify-center text-sm font-bold text-white shadow-md transition-transform duration-300 group-hover:scale-105"
        :class="avatarClass"
      >
        {{ config.provider?.[0]?.toUpperCase() || 'C' }}
        <!-- Active Indicator Dot -->
        <span
          v-if="config.is_current"
          class="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-emerald-400 border-2 border-bg-elevated shadow-sm"
        >
          <span class="absolute inset-0 rounded-full bg-emerald-400 animate-ping opacity-60" />
        </span>
      </div>

      <!-- Info Block -->
      <div class="flex-1 min-w-0 space-y-1.5">
        <!-- Top Row: Name + Status -->
        <div class="flex items-center gap-2.5 min-w-0">
          <h3
            class="text-sm font-bold font-display truncate transition-colors duration-300"
            :class="nameColorClass"
          >
            {{ config.name }}
          </h3>

          <!-- Status Badges -->
          <div class="flex gap-1.5 shrink-0">
            <span
              v-if="config.is_current"
              class="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-emerald-400 bg-emerald-400/10 px-2 py-0.5 rounded-full ring-1 ring-emerald-400/20"
            >
              {{ t('configs.currentBadge') }}
            </span>
            <span
              v-if="config.is_default"
              class="inline-flex items-center text-[10px] font-bold uppercase tracking-wider text-amber-400 bg-amber-400/10 px-2 py-0.5 rounded-full ring-1 ring-amber-400/20"
            >
              {{ t('configs.defaultBadge') }}
            </span>
          </div>
        </div>

        <!-- Description -->
        <p class="text-xs text-white/80 truncate leading-relaxed">
          {{ config.description || t('configs.noDescription') }}
        </p>
      </div>

      <!-- Meta Chips -->
      <div class="hidden md:flex items-center gap-2 shrink-0">
        <!-- Model -->
        <div
          v-if="config.model"
          class="meta-chip"
          :title="config.model"
        >
          <SIcon
            name="Sparkles"
            size="w-3 h-3"
            class="text-accent-primary opacity-70"
          />
          <span class="truncate max-w-[120px]">{{ config.model }}</span>
        </div>

        <!-- Provider -->
        <div
          v-if="config.provider"
          class="meta-chip"
        >
          <SIcon
            name="Building2"
            size="w-3 h-3"
            class="opacity-50"
          />
          <span>{{ config.provider }}</span>
        </div>

        <!-- Calls Count -->
        <div
          v-if="(config.usage_count ?? 0) > 0"
          class="meta-chip"
        >
          <SIcon
            name="TrendingUp"
            size="w-3 h-3"
            class="text-accent-secondary opacity-70"
          />
          <span class="font-bold text-accent-secondary">{{ config.usage_count }}</span>
        </div>
      </div>
    </button>

    <!-- Right Action Area -->
    <div class="flex items-center gap-2 pr-4 shrink-0">
      <!-- Switch Button -->
      <button
        v-if="!config.is_current"
        type="button"
        class="switch-btn px-3.5 py-1.5 rounded-lg text-xs font-bold transition-[color,background-color,opacity] duration-200 opacity-0 group-hover:opacity-100 focus:opacity-100"
        :aria-label="t('configs.switch') + ': ' + config.name"
        :title="t('configs.switch')"
        @click="emit('switch', config.name)"
      >
        <SIcon
          name="ArrowRightLeft"
          size="w-3.5 h-3.5"
          class="mr-1 inline-block"
        />
        {{ t('configs.switch') }}
      </button>
      <span
        v-else
        class="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-bold text-emerald-400/70 bg-emerald-400/5 cursor-default"
      >
        <SIcon
          name="CheckCircle"
          size="w-3.5 h-3.5"
        />
        {{ t('configs.inUse') }}
      </span>

      <!-- Edit Button -->
      <button
        type="button"
        class="edit-btn p-2 rounded-lg transition-[color,background-color,opacity] duration-200 opacity-0 group-hover:opacity-100 focus:opacity-100"
        :class="config.is_current ? 'opacity-60' : ''"
        :aria-label="t('common.edit') + ': ' + config.name"
        :title="t('common.edit')"
        @click="emit('edit', config.name)"
      >
        <SIcon
          name="Settings"
          size="w-4 h-4"
        />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { ConfigItem } from '@/types'

interface Props {
  config: ConfigItem
}

const props = defineProps<Props>()
const { t } = useI18n()

const emit = defineEmits<{
  switch: [name: string]
  edit: [name: string]
  delete: [name: string]
  enable: [name: string]
  disable: [name: string]
}>()

// Provider type detection
const providerType = computed(() => {
  const type = props.config.provider_type?.toLowerCase() || ''
  if (type.includes('official')) return 'official'
  if (type.includes('third')) return 'third'
  return 'uncategorized'
})

// Left accent bar color by provider type
const accentBarClass = computed(() => {
  const map = {
    official: 'bg-cyan-400 group-hover:bg-cyan-300',
    third: 'bg-violet-400 group-hover:bg-violet-300',
    uncategorized: 'bg-amber-400 group-hover:bg-amber-300',
  }
  return map[providerType.value]
})

// Avatar gradient by provider type
const avatarClass = computed(() => {
  const map = {
    official: 'bg-gradient-to-br from-cyan-500 to-cyan-700',
    third: 'bg-gradient-to-br from-violet-500 to-violet-700',
    uncategorized: 'bg-gradient-to-br from-amber-500 to-amber-700',
  }
  return map[providerType.value]
})

// Name color by provider type
const nameColorClass = computed(() => {
  const map = {
    official: 'text-cyan-400 group-hover:text-cyan-300',
    third: 'text-violet-400 group-hover:text-violet-300',
    uncategorized: 'text-amber-400 group-hover:text-amber-300',
  }
  return map[providerType.value]
})
</script>

<style scoped>
/* === Row Base - 液态玻璃 === */
.config-row {
  background: var(--liquid-glass-bg);
  backdrop-filter: var(--liquid-glass-blur);
  border: 1px solid var(--liquid-glass-border);
  box-shadow: var(--liquid-glass-highlight);
}

.config-row-main {
  appearance: none;
  background: transparent;
  border: 0;
  color: inherit;
  cursor: pointer;
  font: inherit;
}

.config-row:hover {
  background: var(--glass-bg-medium);
  border-color: var(--glass-border-medium);
  box-shadow: var(--liquid-glass-shadow);
  transform: translateX(2px);
}

/* === Current Config Highlight === */
.config-row--current {
  background: linear-gradient(135deg,
    rgb(6 182 212 / 6%) 0%,
    rgb(139 92 246 / 4%) 100%
  );
  border-color: rgb(6 182 212 / 15%);
  box-shadow: var(--glow-primary);
}

.config-row--current:hover {
  border-color: rgb(6 182 212 / 25%);
  box-shadow:
    var(--glow-primary),
    var(--shadow-md);
}

/* === Disabled Config === */
.config-row--disabled {
  opacity: 0.5;
}

/* === Meta Chips === */
.meta-chip {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  padding: 0.25rem 0.625rem;
  border-radius: 9999px;
  font-size: 0.6875rem;
  font-family: var(--font-mono);
  color: var(--color-text-secondary);
  background: var(--glass-bg-light);
  border: 1px solid var(--color-border-subtle);
  white-space: nowrap;
  transition: all 0.2s;
}

.config-row:hover .meta-chip {
  background: var(--glass-bg-medium);
  border-color: var(--color-border-default);
}

/* === Switch Button === */
.switch-btn {
  background: linear-gradient(135deg, var(--color-accent-primary), var(--color-accent-secondary));
  color: white;
  box-shadow: 0 2px 8px rgb(var(--color-accent-primary-rgb) / 25%);
}

.switch-btn:hover {
  box-shadow: 0 4px 16px rgb(var(--color-accent-primary-rgb) / 40%);
  transform: translateY(-1px);
}

/* === Edit Button === */
.edit-btn {
  color: var(--color-text-muted);
  background: transparent;
}

.edit-btn:hover {
  color: var(--color-accent-primary);
  background: var(--glass-bg-medium);
}

/* === Highlight Pulse (scroll-to) === */
.config-row.highlight-pulse {
  animation: row-highlight-pulse 1.5s ease-out;
}

@keyframes row-highlight-pulse {
  0% {
    box-shadow: 0 0 0 0 rgb(6 182 212 / 40%);
  }

  50% {
    box-shadow: 0 0 0 6px rgb(6 182 212 / 10%);
  }

  100% {
    box-shadow: 0 0 0 0 rgb(6 182 212 / 0%);
  }
}

/* === Accent bar glow for current === */
.config-row--current .accent-bar {
  box-shadow: 2px 0 8px rgb(6 182 212 / 30%);
}
</style>

// ccr-ui/src/features/configs/components/ConfigCard.tsx
import { memo, useCallback } from 'react'
import type { ConfigItem } from '@/types'
import { SIcon } from '@/ui'
import { useAppT } from '@/i18n'
import { providerKind } from '../lib/configList'
import { ConfigBadges, ConfigMetaChips } from './ConfigBadges'
import '../styles/config-card.css'

interface ConfigCardProps {
  config: ConfigItem
  highlighted: boolean
  onSwitch: (name: string) => void
  onEnable: (name: string) => void
  onEdit: (name: string) => void
}

const ACCENT: Record<string, string> = {
  official: 'bg-cyan-400 group-hover:bg-cyan-300',
  third: 'bg-violet-400 group-hover:bg-violet-300',
  uncategorized: 'bg-amber-400 group-hover:bg-amber-300',
}

const AVATAR: Record<string, string> = {
  official: 'bg-gradient-to-br from-cyan-500 to-cyan-700',
  third: 'bg-gradient-to-br from-violet-500 to-violet-700',
  uncategorized: 'bg-gradient-to-br from-amber-500 to-amber-700',
}

const NAME: Record<string, string> = {
  official: 'text-cyan-400 group-hover:text-cyan-300',
  third: 'text-violet-400 group-hover:text-violet-300',
  uncategorized: 'text-amber-400 group-hover:text-amber-300',
}

export const ConfigCard = memo(function ConfigCard({
  config,
  highlighted,
  onSwitch,
  onEnable,
  onEdit,
}: ConfigCardProps) {
  const t = useAppT()
  const kind = providerKind(config)
  const handleEdit = useCallback(() => {
    onEdit(config.name)
  }, [config.name, onEdit])
  const handleSwitch = useCallback(() => {
    if (config.enabled === false) onEnable(config.name)
    else onSwitch(config.name)
  }, [config.enabled, config.name, onEnable, onSwitch])
  const actionLabel = config.enabled === false ? t('configs.enable') : t('configs.switch')

  const rowClass = [
    'config-row group relative flex items-stretch overflow-hidden rounded-xl transition-colors duration-300',
    config.is_current ? 'config-row--current' : '',
    config.enabled === false ? 'config-row--disabled' : '',
    highlighted ? 'highlight-pulse' : '',
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={rowClass} data-config-name={config.name}>
      <div className={`accent-bar w-[0.1875rem] shrink-0 transition-colors duration-300 ${ACCENT[kind]}`} />
      <button
        type="button"
        className="config-row-main flex min-w-0 flex-1 items-center gap-4 px-5 py-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-primary/35"
        aria-label={`${t('common.edit')}: ${config.name}`}
        onClick={handleEdit}
      >
        <div
          className={`avatar-wrapper relative flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-sm font-bold text-white shadow-md transition-transform duration-300 group-hover:scale-105 ${AVATAR[kind]}`}
        >
          {config.provider?.[0]?.toUpperCase() || 'C'}
          {config.is_current ? (
            <span className="absolute -top-1 -right-1 h-3 w-3 rounded-full border-2 border-bg-elevated bg-emerald-400 shadow-sm">
              <span className="absolute inset-0 rounded-full bg-emerald-400 opacity-60 animate-ping" />
            </span>
          ) : null}
        </div>
        <div className="min-w-0 flex-1 space-y-1.5">
          <div className="flex min-w-0 items-center gap-2.5">
            <h3 className={`truncate font-display text-sm font-bold transition-colors duration-300 ${NAME[kind]}`}>
              {config.name}
            </h3>
            <ConfigBadges config={config} />
          </div>
          <p className="truncate text-xs leading-relaxed text-text-primary">
            {config.description || t('configs.noDescription')}
          </p>
        </div>
        <ConfigMetaChips config={config} />
      </button>
      <div className="flex shrink-0 items-center gap-2 pr-4">
        {config.is_current && config.enabled !== false ? (
          <span className="inline-flex cursor-default items-center gap-1 rounded-lg bg-emerald-400/5 px-3 py-1.5 text-xs font-bold text-emerald-400/70">
            <SIcon name="CheckCircle" size="w-3.5 h-3.5" />
            {t('configs.inUse')}
          </span>
        ) : (
          <button
            type="button"
            className="switch-btn rounded-lg px-3.5 py-1.5 text-xs font-bold opacity-0 transition-[color,background-color,opacity] duration-200 group-hover:opacity-100 focus:opacity-100"
            aria-label={`${actionLabel}: ${config.name}`}
            title={actionLabel}
            onClick={handleSwitch}
          >
            <SIcon name="ArrowRightLeft" size="w-3.5 h-3.5" className="mr-1 inline-block" />
            {actionLabel}
          </button>
        )}
        <button
          type="button"
          className={`edit-btn rounded-lg p-2 opacity-0 transition-[color,background-color,opacity] duration-200 group-hover:opacity-100 focus:opacity-100 ${config.is_current ? 'opacity-60' : ''}`}
          aria-label={`${t('common.edit')}: ${config.name}`}
          title={t('common.edit')}
          onClick={handleEdit}
        >
          <SIcon name="Settings" size="w-4 h-4" />
        </button>
      </div>
    </div>
  )
})
