// ccr-ui/src/features/commands/CommandFormModal.tsx
import { useCallback, useEffect, type FormEvent } from 'react'
import { useForm } from 'react-hook-form'
import type { SlashCommand, SlashCommandRequest } from '@/types/platform'
import { BaseModal, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/ui'
import { useCommandsT } from './locale'

interface CommandFormModalProps {
  visible: boolean
  editingCommand: SlashCommand | null
  folders: string[]
  onClose: () => void
  onSubmit: (data: SlashCommandRequest) => void
}

const empty = (): SlashCommandRequest => ({ name: '', command: '', description: '', folder: '' })

export function CommandFormModal({ visible, editingCommand, folders, onClose, onSubmit }: CommandFormModalProps) {
  const t = useCommandsT()
  const form = useForm<SlashCommandRequest>({ defaultValues: empty() })
  const folder = form.watch('folder')
  const isEditing = Boolean(editingCommand)

  useEffect(() => {
    if (editingCommand) {
      form.reset({
        name: editingCommand.name,
        command: editingCommand.command,
        description: editingCommand.description,
        folder: editingCommand.folder,
      })
      return
    }
    form.reset(empty())
  }, [editingCommand, form])

  const handleOpenChange = useCallback((open: boolean) => {
    if (!open) onClose()
  }, [onClose])
  const handleFolder = useCallback((value: string) => {
    form.setValue('folder', value)
  }, [form])
  const submit = useCallback(() => {
    onSubmit(form.getValues())
    onClose()
  }, [form, onClose, onSubmit])
  const handleSubmit = useCallback((event: FormEvent) => {
    event.preventDefault()
    submit()
  }, [submit])

  return (
    <BaseModal
      modelValue={visible}
      title={isEditing ? t('common.edit') : t('common.add')}
      size="md"
      scrollable
      surface="solid"
      onUpdateModelValue={handleOpenChange}
      onClose={onClose}
      footer={
        <div className="flex w-full justify-end gap-3">
          <button type="button" className="rounded-lg border border-border-default px-4 py-2" onClick={onClose}>{t('common.cancel')}</button>
          <button type="button" className="rounded-lg bg-accent-primary px-4 py-2 text-[color:var(--color-accent-primary-contrast)]" onClick={submit}>
            {isEditing ? t('common.update') : t('common.create')}
          </button>
        </div>
      }
    >
      <form className="space-y-4" onSubmit={handleSubmit}>
        <label className="block text-sm font-medium text-text-primary">
          {t('common.name')}
          <input className="mt-1 w-full rounded-lg border border-border-default bg-bg-surface px-3 py-2 text-sm" required disabled={isEditing} placeholder={t('slashCommands.namePlaceholder')} {...form.register('name')} />
        </label>
        <label className="block text-sm font-medium text-text-primary">
          {t('common.command')}
          <input className="mt-1 w-full rounded-lg border border-border-default bg-bg-surface px-3 py-2 font-mono text-sm" required placeholder={t('slashCommands.commandPlaceholder')} {...form.register('command')} />
        </label>
        <label className="block text-sm font-medium text-text-primary">
          {t('common.description')}
          <textarea className="mt-1 min-h-20 w-full rounded-lg border border-border-default bg-bg-surface px-3 py-2 text-sm" required placeholder={t('slashCommands.descriptionPlaceholder')} {...form.register('description')} />
        </label>
        <label className="block text-sm font-medium text-text-primary">
          {t('common.folder')}
          <Select value={folder} onValueChange={handleFolder}>
            <SelectTrigger><SelectValue placeholder={t('slashCommands.selectFolder')} /></SelectTrigger>
            <SelectContent>
              {folders.map((item) => (
                <SelectItem key={item} value={item}>{item}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </label>
      </form>
    </BaseModal>
  )
}

// ccr-ui/src/components/CommandFormModal.vue
<template>
  <BaseModal
    :model-value="visible"
    size="md"
    scrollable
    surface="solid"
    :title="isEditing ? $t('common.edit') : $t('common.add')"
    @close="close"
  >
    <!-- 模态框标题 -->
    <template #header="{ titleId }">
      <h3
        :id="titleId"
        class="text-lg font-semibold text-text-primary"
      >
        {{ isEditing ? $t('common.edit') : $t('common.add') }}
      </h3>
    </template>

    <!-- 表单内容 -->
    <form @submit.prevent="handleSubmit">
      <div class="space-y-4">
        <!-- 名称 -->
        <div>
          <label
            class="block text-sm font-medium mb-1"
            :style="{ color: 'var(--color-text-primary)' }"
          >
            {{ $t('common.name') }}
          </label>
          <input
            v-model="form.name"
            type="text"
            required
            :disabled="isEditing"
            class="w-full px-3 py-2 rounded-lg text-sm focus:outline-none focus:ring-2"
            :style="{
              border: '1px solid var(--color-border-default)',
              background: 'var(--color-bg-surface)',
              color: 'var(--color-text-primary)',
              '--tw-ring-color': 'var(--color-accent-primary)'
            }"
            :placeholder="$t('slashCommands.namePlaceholder')"
          >
        </div>

        <!-- 命令 -->
        <div>
          <label
            class="block text-sm font-medium mb-1"
            :style="{ color: 'var(--color-text-primary)' }"
          >
            {{ $t('common.command') }}
          </label>
          <input
            v-model="form.command"
            type="text"
            required
            class="w-full px-3 py-2 rounded-lg text-sm focus:outline-none focus:ring-2"
            :style="{
              border: '1px solid var(--color-border-default)',
              background: 'var(--color-bg-surface)',
              color: 'var(--color-text-primary)',
              '--tw-ring-color': 'var(--color-accent-primary)'
            }"
            :placeholder="$t('slashCommands.commandPlaceholder')"
          >
        </div>

        <!-- 描述 -->
        <div>
          <label
            class="block text-sm font-medium mb-1"
            :style="{ color: 'var(--color-text-primary)' }"
          >
            {{ $t('common.description') }}
          </label>
          <textarea
            v-model="form.description"
            rows="3"
            required
            class="w-full px-3 py-2 rounded-lg text-sm focus:outline-none focus:ring-2 resize-y min-h-[80px]"
            :style="{
              border: '1px solid var(--color-border-default)',
              background: 'var(--color-bg-surface)',
              color: 'var(--color-text-primary)',
              '--tw-ring-color': 'var(--color-accent-primary)'
            }"
            :placeholder="$t('slashCommands.descriptionPlaceholder')"
          />
        </div>

        <!-- 文件夹 -->
        <div>
          <label
            class="block text-sm font-medium mb-1"
            :style="{ color: 'var(--color-text-primary)' }"
          >
            {{ $t('common.folder') }}
          </label>
          <select
            v-model="form.folder"
            required
            class="w-full px-3 py-2 rounded-lg text-sm focus:outline-none focus:ring-2"
            :style="{
              border: '1px solid var(--color-border-default)',
              background: 'var(--color-bg-surface)',
              color: 'var(--color-text-primary)',
              '--tw-ring-color': 'var(--color-accent-primary)'
            }"
          >
            <option
              value=""
              disabled
            >
              {{ $t('slashCommands.selectFolder') }}
            </option>
            <option
              v-for="folder in folders"
              :key="folder"
              :value="folder"
            >
              {{ folder }}
            </option>
          </select>
        </div>
      </div>

      <!-- 表单按钮 -->
      <div class="flex justify-end gap-3 mt-6">
        <button
          type="button"
          class="px-4 py-2 rounded-lg transition-colors hover:opacity-80"
          :style="{
            background: 'var(--color-bg-surface)',
            color: 'var(--color-text-secondary)',
            border: '1px solid var(--color-border-default)'
          }"
          @click="close"
        >
          {{ $t('common.cancel') }}
        </button>
        <button
          type="submit"
          :disabled="loading"
          class="px-4 py-2 rounded-lg inline-flex items-center transition-colors hover:opacity-90"
          :style="{
            background: 'var(--color-accent-primary)',
            color: 'var(--color-accent-primary-contrast)',
            opacity: loading ? 0.7 : 1,
            cursor: loading ? 'not-allowed' : 'pointer'
          }"
        >
          <SIcon
            v-if="loading"
            name="RefreshCw"
            size="w-4 h-4"
            class="animate-spin mr-2"
          />
          {{ isEditing ? $t('common.update') : $t('common.create') }}
        </button>
      </div>
    </form>
  </BaseModal>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { ref, computed, watch } from 'vue'
import BaseModal from '@/components/common/BaseModal.vue'
import type { SlashCommand, SlashCommandRequest } from '@/types/platform'

// Props
interface Props {
  visible: boolean
  editingCommand: SlashCommand | null
  folders: string[]
}

const props = defineProps<Props>()

// Emits
interface Emits {
  (e: 'update:visible', value: boolean): void
  (e: 'update:editingCommand', value: SlashCommand | null): void
  (e: 'submit', data: SlashCommandRequest): void
}

const emit = defineEmits<Emits>()

// 状态
const loading = ref(false)
const form = ref<SlashCommandRequest>({
  name: '',
  command: '',
  description: '',
  folder: ''
})

// 计算属性
const isEditing = computed(() => !!props.editingCommand)

// Close handler
const close = () => {
  emit('update:visible', false)
  emit('update:editingCommand', null)
  resetForm()
}

// 方法
const resetForm = () => {
  form.value = {
    name: '',
    command: '',
    description: '',
    folder: ''
  }
}

const handleSubmit = async () => {
  loading.value = true
  try {
    emit('submit', { ...form.value })
    close()
  } finally {
    loading.value = false
  }
}

// 监听编辑命令变化
watch(
  () => props.editingCommand,
  (cmd) => {
    if (cmd) {
      form.value = {
        name: cmd.name,
        command: cmd.command,
        description: cmd.description,
        folder: cmd.folder
      }
    } else {
      resetForm()
    }
  },
  { immediate: true }
)
</script>
