// ccr-ui/src/ui/history-list.tsx
import { useRef } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import type { HistoryEntry } from '@/types'
import { formatRelativeTime } from '@/utils/codexHelpers'
import { SIcon } from './s-icon'
import { Spinner } from './spinner'

interface HistoryListProps {
  entries: HistoryEntry[]
  loading?: boolean
  emptyTitle?: string
  emptyDescription?: string
  recordsLabel?: string
  title?: string
}

const OPERATION_LABEL: Record<string, string> = {
  switch: 'Switched Config',
  init: 'Initialized',
  update: 'Updated Config',
  delete: 'Deleted Config',
  validate: 'Validation Run',
  clean: 'Cleaned Backups',
  import: 'Imported',
  export: 'Exported',
}

const OPERATION_ICON: Record<string, string> = {
  switch: 'GitBranch',
  init: 'CheckCircle',
  update: 'FileEdit',
  delete: 'Trash2',
  validate: 'CheckCircle',
  clean: 'RefreshCw',
  import: 'ArrowRight',
  export: 'ArrowRight',
}

const OPERATION_COLOR: Record<string, string> = {
  switch: 'var(--chart-color-0)',
  init: 'var(--chart-color-1)',
  update: 'var(--chart-color-3)',
  delete: 'var(--chart-color-4)',
  validate: 'var(--chart-color-2)',
  clean: 'var(--chart-color-3)',
  import: 'var(--chart-color-1)',
  export: 'var(--chart-color-0)',
}

export function HistoryList({
  entries,
  loading = false,
  emptyTitle = '暂无历史记录',
  emptyDescription = '配置变更会显示在这里。',
  recordsLabel,
  title = 'History',
}: HistoryListProps) {
  const parentRef = useRef<HTMLDivElement | null>(null)
  const virtualizer = useVirtualizer({
    count: entries.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 160,
    overscan: 5,
  })

  return (
    <div className="flex h-[600px] flex-col">
      <div className="mb-4 flex flex-shrink-0 items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-text-primary">{title}</h2>
          <p className="text-sm text-text-primary">
            {recordsLabel ?? `${entries.length} records`}
          </p>
        </div>
      </div>
      {loading ? (
        <div className="flex flex-1 items-center justify-center">
          <Spinner size="xl" className="text-accent-primary" />
        </div>
      ) : null}
      {!loading && entries.length === 0 ? (
        <div className="flex flex-1 flex-col items-center justify-center text-text-muted">
          <div className="glass-surface mb-4 rounded-full p-6">
            <SIcon name="History" size="w-8 h-8" className="opacity-20" />
          </div>
          <p className="text-lg font-medium text-text-primary">{emptyTitle}</p>
          <p className="text-sm">{emptyDescription}</p>
        </div>
      ) : null}
      {!loading && entries.length > 0 ? (
        <div ref={parentRef} className="scrollbar-thin flex-1 overflow-auto pr-2">
          <div
            className="relative w-full"
            style={{ height: `${virtualizer.getTotalSize()}px` }}
          >
            {virtualizer.getVirtualItems().map((row) => {
              const entry = entries[row.index]
              const color = OPERATION_COLOR[entry.operation] || 'var(--color-text-muted)'
              return (
                <div
                  key={entry.id}
                  className="absolute top-0 left-0 w-full pb-3"
                  style={{ transform: `translateY(${row.start}px)` }}
                >
                  <HistoryCard entry={entry} color={color} />
                </div>
              )
            })}
          </div>
        </div>
      ) : null}
    </div>
  )
}

function HistoryCard({ entry, color }: { entry: HistoryEntry; color: string }) {
  const changes = entry.changes ?? []
  return (
    <article
      className="group relative rounded-2xl border border-border-default/40 bg-bg-surface p-4 transition-colors duration-300"
      style={{ borderLeftWidth: 4, borderLeftColor: color }}
    >
      <div className="flex gap-4">
        <div
          className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border"
          style={{
            borderColor: color,
            backgroundColor: 'transparent',
            color,
          }}
        >
          <SIcon name={OPERATION_ICON[entry.operation] || 'GitBranch'} size="w-5 h-5" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="mb-2 flex items-start justify-between">
            <div>
              <h3 className="font-bold text-text-primary">
                {OPERATION_LABEL[entry.operation] || entry.operation}
              </h3>
              <div className="mt-1 flex items-center gap-3 text-xs text-text-primary">
                <span className="inline-flex items-center gap-1">
                  <SIcon name="Clock" size="w-3 h-3" />
                  {formatRelativeTime(entry.timestamp)}
                </span>
                <span className="inline-flex items-center gap-1">
                  <SIcon name="User" size="w-3 h-3" />
                  {entry.actor}
                </span>
              </div>
            </div>
            <span
              className="rounded px-2 py-0.5 text-[10px] font-bold tracking-wider uppercase"
              style={{ color }}
            >
              {entry.operation}
            </span>
          </div>
          {entry.from_config && entry.to_config ? (
            <div className="mb-2 flex items-center gap-2 rounded border border-border-default/15 bg-bg-elevated p-2">
              <code className="rounded bg-accent-danger/10 px-1.5 py-0.5 text-xs text-accent-danger">
                {entry.from_config}
              </code>
              <SIcon name="ArrowRight" size="w-3 h-3" className="text-text-muted" />
              <code className="rounded bg-accent-success/10 px-1.5 py-0.5 text-xs text-accent-success">
                {entry.to_config}
              </code>
            </div>
          ) : null}
          {changes.length > 0 ? (
            <div className="my-2 space-y-1">
              {changes.slice(0, 3).map((change) => (
                <div
                  key={change.key}
                  className="grid grid-cols-[auto_1fr] gap-2 rounded border border-border-default/10 bg-bg-elevated p-1.5 font-mono text-xs"
                >
                  <span className="font-bold text-text-primary">{change.key}</span>
                  <div className="flex items-center gap-1 truncate text-text-muted">
                    <span className="truncate">{change.old_value || '_'}</span>
                    <SIcon name="ArrowRight" size="h-3 w-3" />
                    <span className="truncate text-text-primary">{change.new_value || '_'}</span>
                  </div>
                </div>
              ))}
            </div>
          ) : null}
          <div className="mt-2 border-t border-border-default/10 pt-2 font-mono text-[10px] text-text-muted">
            {entry.id}
          </div>
        </div>
      </div>
    </article>
  )
}

// ccr-ui/src/components/HistoryList.vue
<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useVirtualizer } from '@tanstack/vue-virtual'
import type { HistoryEntry } from '@/types'
import { formatRelativeTime } from '@/utils/codexHelpers'
import Spinner from '@/components/ui/Spinner.vue'
import Card from '@/components/ui/Card.vue'

const props = withDefaults(defineProps<{
  entries: HistoryEntry[]
  loading?: boolean
}>(), { loading: false })

const { t } = useI18n()
const parentRef = ref<HTMLElement | null>(null)

const rowVirtualizer = useVirtualizer(computed(() => ({
  count: props.entries.length,
  getScrollElement: () => parentRef.value,
  estimateSize: () => 160,
  overscan: 5,
})))

const measureElement = (element: unknown) => {
  rowVirtualizer.value.measureElement(element instanceof Element ? element : null)
}

const getOperationLabel = (op: string) => ({
  'switch': 'Switched Config',
  'init': 'Initialized',
  'update': 'Updated Config',
  'delete': 'Deleted Config',
  'validate': 'Validation Run',
  'clean': 'Cleaned Backups',
  'import': 'Imported',
  'export': 'Exported'
}[op] || op)

const getOperationIcon = (op: string) => ({
  'switch': 'GitBranch',
  'init': 'CheckCircle',
  'update': 'FileEdit',
  'delete': 'Trash2',
  'validate': 'CheckCircle',
  'clean': 'RefreshCw',
  'import': 'ArrowRight',
  'export': 'ArrowRight'
}[op] || 'GitBranch')

const getOperationColor = (op: string) => ({
  'switch': 'var(--chart-color-0)',
  'init': 'var(--chart-color-1)',
  'update': 'var(--chart-color-3)',
  'delete': 'var(--chart-color-4)',
  'validate': 'var(--chart-color-2)',
  'clean': 'var(--chart-color-3)',
  'import': 'var(--chart-color-1)',
  'export': 'var(--chart-color-0)'
}[op] || 'var(--color-text-muted)')
</script>

<template>
  <div class="h-[600px] flex flex-col">
    <div class="flex items-center justify-between mb-4 flex-shrink-0">
      <div>
        <h2 class="text-xl font-bold text-white">
          {{ t('common.historyPanel.title') }}
        </h2>
        <p class="text-sm text-text-primary">
          {{ t('common.historyPanel.recordsFound', { count: entries.length }) }}
        </p>
      </div>
    </div>

    <!-- Loading State -->
    <div
      v-if="loading"
      class="flex-1 flex items-center justify-center"
    >
      <Spinner
        size="xl"
        class="text-accent-primary"
      />
    </div>

    <!-- Empty State -->
    <div
      v-else-if="entries.length === 0"
      class="flex-1 flex flex-col items-center justify-center text-text-muted"
    >
      <div class="p-6 rounded-full glass-surface mb-4">
        <SIcon
          name="History"
          size="w-8 h-8"
          class="opacity-20"
        />
      </div>
      <p class="text-lg font-medium text-text-primary">
        {{ t('common.historyPanel.emptyTitle') }}
      </p>
      <p class="text-sm">
        {{ t('common.historyPanel.emptyDescription') }}
      </p>
    </div>

    <!-- Virtual List -->
    <div
      v-else
      ref="parentRef"
      class="flex-1 overflow-auto pr-2 scrollbar-thin"
    >
      <div
        :style="{
          height: `${rowVirtualizer.getTotalSize()}px`,
          width: '100%',
          position: 'relative',
        }"
      >
        <div
          v-for="virtualRow in rowVirtualizer.getVirtualItems()"
          :key="entries[virtualRow.index].id"
          class="absolute top-0 left-0 w-full"
          :style="{ transform: `translateY(${virtualRow.start}px)` }"
        >
          <div
            :ref="(el) => measureElement(el)"
            :data-index="virtualRow.index"
            class="pb-3"
          >
            <Card 
              variant="glass" 
              hover 
              class="p-4 group transition-colors duration-300 border-l-4"
              :style="{ borderLeftColor: getOperationColor(entries[virtualRow.index].operation) }"
            >
              <!-- Timeline Line -->
              <div
                v-if="virtualRow.index < entries.length - 1"
                class="absolute left-8 top-full w-px h-4 bg-border-subtle -z-10"
              />

              <div class="flex gap-4">
                <!-- Icon -->
                <div 
                  class="w-10 h-10 rounded-lg flex items-center justify-center shrink-0 border"
                  :style="{ 
                    borderColor: getOperationColor(entries[virtualRow.index].operation) + '40',
                    backgroundColor: getOperationColor(entries[virtualRow.index].operation) + '15',
                    color: getOperationColor(entries[virtualRow.index].operation)
                  }"
                >
                  <SIcon
                    :name="getOperationIcon(entries[virtualRow.index].operation)"
                    size="w-5 h-5"
                  />
                </div>

                <!-- Content -->
                <div class="flex-1 min-w-0">
                  <div class="flex justify-between items-start mb-2">
                    <div>
                      <h3 class="font-bold text-white">
                        {{ getOperationLabel(entries[virtualRow.index].operation) }}
                      </h3>
                      <div class="flex items-center gap-3 text-xs text-text-primary mt-1">
                        <span class="flex items-center gap-1"><SIcon
                          name="Clock"
                          size="w-3 h-3"
                        /> {{ formatRelativeTime(entries[virtualRow.index].timestamp) }}</span>
                        <span class="flex items-center gap-1"><SIcon
                          name="User"
                          size="w-3 h-3"
                        /> {{ entries[virtualRow.index].actor }}</span>
                      </div>
                    </div>
                    <span 
                      class="px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider"
                      :style="{ 
                        backgroundColor: getOperationColor(entries[virtualRow.index].operation) + '20',
                        color: getOperationColor(entries[virtualRow.index].operation)
                      }"
                    >
                      {{ entries[virtualRow.index].operation }}
                    </span>
                  </div>

                  <!-- Config Change -->
                  <div
                    v-if="entries[virtualRow.index].from_config && entries[virtualRow.index].to_config"
                    class="flex items-center gap-2 p-2 rounded bg-bg-surface/70 border border-border-default/15 mb-2"
                  >
                    <code class="text-xs text-accent-danger bg-accent-danger/10 px-1.5 py-0.5 rounded">{{ entries[virtualRow.index].from_config }}</code>
                    <SIcon
                      name="ArrowRight"
                      size="w-3 h-3"
                      class="text-text-muted"
                    />
                    <code class="text-xs text-accent-success bg-accent-success/10 px-1.5 py-0.5 rounded">{{ entries[virtualRow.index].to_config }}</code>
                  </div>

                  <!-- Env Changes -->
                  <div
                    v-if="entries[virtualRow.index].changes?.length"
                    class="space-y-1 my-2"
                  >
                    <div
                      v-for="change in entries[virtualRow.index].changes?.slice(0, 3) ?? []"
                      :key="change.key"
                      class="text-xs font-mono p-1.5 rounded bg-bg-surface/60 border border-border-default/10 grid grid-cols-[auto_1fr] gap-2"
                    >
                      <span class="font-bold text-white">{{ change.key }}</span>
                      <div class="flex items-center gap-1 truncate text-text-muted">
                        <span class="truncate">{{ change.old_value || '_' }}</span>
                        <SIcon
                          name="ArrowRight"
                          size="h-3 w-3"
                        />
                        <span class="text-white truncate">{{ change.new_value || '_' }}</span>
                      </div>
                    </div>
                    <button
                      v-if="(entries[virtualRow.index].changes?.length ?? 0) > 3"
                      class="text-[10px] text-accent-primary hover:underline"
                    >
                      + {{ (entries[virtualRow.index].changes?.length ?? 0) - 3 }} {{ t('common.historyPanel.moreChanges') }}
                    </button>
                  </div>
                    
                  <div class="mt-2 pt-2 border-t border-border-default/10 text-[10px] text-text-muted font-mono">
                    {{ t('common.historyPanel.idLabel', { id: entries[virtualRow.index].id }) }}
                  </div>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
