// ccr-ui/src/features/mcp/McpPresetsPanel.tsx
import { memo, useCallback, useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { installMcpPreset, listMcpPresets } from '@/api'
import type { McpPreset } from '@/types/api'
import type { SyncResult } from '@/types/sync'
import { logger } from '@/utils/logger'
import { BaseModal, SIcon, cn } from '@/ui'
import { useMcpT } from './locale'
import { mcpNotify } from './notify'

const PLATFORMS = [
  { id: 'claude', name: 'Claude', icon: 'Bot' },
  { id: 'codex', name: 'Codex', icon: 'Terminal' },
  { id: 'gemini', name: 'Antigravity CLI', icon: 'Sparkles' },
]

interface McpPresetsPanelProps {
  onInstalled: () => void
}

const PresetCard = memo(function PresetCard({
  preset,
  onOpen,
}: {
  preset: McpPreset
  onOpen: (preset: McpPreset) => void
}) {
  const t = useMcpT()
  const handleOpen = useCallback(() => {
    onOpen(preset)
  }, [onOpen, preset])
  return (
    <button type="button" className="rounded-2xl border border-border-default/15 bg-bg-elevated p-4 text-left hover:border-accent-secondary/30" onClick={handleOpen}>
      <div className="mb-3 flex flex-wrap gap-1.5">
        {preset.tags.slice(0, 2).map((tag) => (
          <span key={tag} className="rounded-full bg-accent-secondary/10 px-2 py-0.5 text-[0.625rem] font-medium text-accent-secondary">
            {tag}
          </span>
        ))}
        {preset.requires_api_key ? (
          <span className="inline-flex items-center gap-1 rounded-full bg-accent-warning/10 px-2 py-0.5 text-[0.625rem] font-medium text-accent-warning">
            <SIcon name="KeyRound" size="w-3 h-3" />
            {t('mcp.presets.apiKeyBadge')}
          </span>
        ) : null}
      </div>
      <h3 className="mb-1 truncate text-sm font-bold text-text-primary">{preset.name}</h3>
      <p className="mb-3 line-clamp-2 text-xs text-text-muted">{preset.description}</p>
      <div className="flex items-center gap-1.5 overflow-hidden rounded-lg bg-bg-base px-2 py-1.5 font-mono text-[0.625rem] text-text-muted">
        <SIcon name="Terminal" size="w-3 h-3" />
        <span className="truncate">{preset.command} {(preset.args || []).join(' ')}</span>
      </div>
    </button>
  )
})

export function McpPresetsPanel({ onInstalled }: McpPresetsPanelProps) {
  const t = useMcpT()
  const [open, setOpen] = useState(true)
  const [loading, setLoading] = useState(true)
  const [presets, setPresets] = useState<McpPreset[]>([])
  const [selected, setSelected] = useState<McpPreset | null>(null)
  const [platforms, setPlatforms] = useState<string[]>(['claude'])
  const [installing, setInstalling] = useState(false)
  const [results, setResults] = useState<SyncResult[]>([])
  const form = useForm<{ apiKey: string }>({ defaultValues: { apiKey: '' } })

  const loadPresets = useCallback(async () => {
    try {
      setLoading(true)
      setPresets(await listMcpPresets<McpPreset[]>())
    } catch (err) {
      logger.error('Failed to load MCP presets:', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void loadPresets()
  }, [loadPresets])

  const togglePanel = useCallback(() => {
    setOpen((value) => !value)
  }, [])
  const closeModal = useCallback(() => {
    setSelected(null)
    form.reset({ apiKey: '' })
    setResults([])
  }, [form])
  const handleOpenChange = useCallback((next: boolean) => {
    if (!next) closeModal()
  }, [closeModal])
  const openPreset = useCallback((preset: McpPreset) => {
    setSelected(preset)
    setPlatforms(['claude'])
    form.reset({ apiKey: '' })
    setResults([])
  }, [form])

  const togglePlatform = useCallback((id: string) => {
    setPlatforms((current) => (current.includes(id) ? current.filter((item) => item !== id) : [...current, id]))
  }, [])

  const confirmInstall = useCallback(async () => {
    if (!selected || platforms.length === 0) return
    const apiKey = form.getValues('apiKey')
    if (selected.requires_api_key && selected.api_key_env && !apiKey) {
      mcpNotify.warning(t('mcp.presets.apiKeyRequired'))
      return
    }
    setInstalling(true)
    try {
      const env: Record<string, string> = {}
      if (selected.api_key_env && apiKey) env[selected.api_key_env] = apiKey
      const result = await installMcpPreset<{ results: SyncResult[] }>(selected.id, platforms, env)
      const next = result.results ?? []
      const failed = next.filter((item) => !item.success)
      if (failed.length > 0) {
        setResults(next)
        onInstalled()
      } else {
        mcpNotify.success(t('mcp.presets.installSuccess'))
        closeModal()
        onInstalled()
      }
    } catch (err) {
      logger.error('Failed to install preset:', err)
      mcpNotify.error(`${t('mcp.presets.installFailed')}: ${err instanceof Error ? err.message : 'Unknown error'}`)
    } finally {
      setInstalling(false)
    }
  }, [closeModal, form, onInstalled, platforms, selected, t])

  const handleConfirm = useCallback(() => {
    void confirmInstall()
  }, [confirmInstall])

  return (
    <div className="rounded-3xl border border-border-default/25 bg-bg-elevated p-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-text-primary">{t('mcp.presets.title')}</h2>
          <p className="text-xs text-text-muted">{t('mcp.presets.subtitle')}</p>
        </div>
        <button type="button" className="flex items-center gap-1.5 rounded-lg bg-bg-surface px-3 py-1.5 text-xs text-text-secondary" onClick={togglePanel}>
          <SIcon name={open ? 'ChevronUp' : 'ChevronDown'} size="w-4 h-4" />
          {open ? t('mcp.presets.collapse') : t('mcp.presets.expand')}
        </button>
      </div>
      {open && loading ? <div className="flex justify-center py-8"><div className="loading-spinner h-8 w-8 border-accent-secondary/30 border-t-accent-secondary" /></div> : null}
      {open && !loading ? (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
          {presets.map((preset) => (
            <PresetCard key={preset.id} preset={preset} onOpen={openPreset} />
          ))}
        </div>
      ) : null}

      <BaseModal modelValue={Boolean(selected)} title={selected?.name ?? t('mcp.presets.install')} size="md" surface="solid" onUpdateModelValue={handleOpenChange} onClose={closeModal} footer={
        <div className="flex w-full gap-3">
          <button type="button" className="flex-1 rounded-xl border border-border-default bg-bg-elevated px-4 py-2 text-text-secondary" onClick={closeModal}>{t('common.cancel')}</button>
          <button type="button" className="flex-1 rounded-xl bg-accent-secondary px-4 py-2 text-[color:var(--color-accent-primary-contrast)] disabled:opacity-60" disabled={installing || platforms.length === 0} onClick={handleConfirm}>
            {installing ? t('mcp.presets.installing') : t('mcp.presets.confirmInstall')}
          </button>
        </div>
      }>
        <div className="grid gap-3">
          <p className="text-sm text-text-secondary">{selected?.description}</p>
          <div className="flex flex-wrap gap-2">
            {PLATFORMS.map((platform) => (
              <PlatformChip key={platform.id} id={platform.id} name={platform.name} icon={platform.icon} active={platforms.includes(platform.id)} onToggle={togglePlatform} />
            ))}
          </div>
          {selected?.requires_api_key ? (
            <input className="rounded-xl border border-border-default bg-bg-base px-3 py-2 font-mono text-sm" placeholder={selected.api_key_env ?? 'API key'} {...form.register('apiKey')} />
          ) : null}
          {results.map((result) => (
            <p key={result.platform} className={result.success ? 'text-accent-success' : 'text-accent-danger'}>
              {result.platform}: {result.message}
            </p>
          ))}
        </div>
      </BaseModal>
    </div>
  )
}

const PlatformChip = memo(function PlatformChip({
  id,
  name,
  icon,
  active,
  onToggle,
}: {
  id: string
  name: string
  icon: string
  active: boolean
  onToggle: (id: string) => void
}) {
  const handleClick = useCallback(() => {
    onToggle(id)
  }, [id, onToggle])
  return (
    <button type="button" className={cn('inline-flex items-center gap-1.5 rounded-xl border px-3 py-2 text-xs', active ? 'border-accent-secondary/30 bg-accent-secondary/20 text-accent-secondary' : 'border-transparent bg-bg-surface text-text-muted')} onClick={handleClick}>
      <SIcon name={icon} size="w-3.5 h-3.5" />
      {name}
    </button>
  )
})

// ccr-ui/src/components/McpPresetsPanel.vue
<template>
  <div class="glass-effect rounded-3xl p-6 border border-border-default/25 mb-6">
    <!-- Header -->
    <div class="flex items-center justify-between mb-6">
      <div class="flex items-center gap-3">
        <div class="p-2.5 rounded-xl bg-gradient-to-br from-accent-secondary/20 to-accent-primary/20 text-accent-secondary">
          <SIcon
            name="Sparkles"
            size="w-5 h-5"
          />
        </div>
        <div>
          <h2 class="text-lg font-bold text-text-primary">
            {{ $t('mcp.presets.title') }}
          </h2>
          <p class="text-xs text-text-muted">
            {{ $t('mcp.presets.subtitle') }}
          </p>
        </div>
      </div>
      <button
        class="text-xs px-3 py-1.5 rounded-lg bg-bg-surface hover:bg-accent-secondary/10 text-text-secondary hover:text-accent-secondary transition-colors flex items-center gap-1.5"
        @click="showPresetsPanel = !showPresetsPanel"
      >
        <SIcon
          :name="showPresetsPanel ? 'ChevronUp' : 'ChevronDown'"
          size="w-4 h-4"
        />
        {{ showPresetsPanel ? $t('mcp.presets.collapse') : $t('mcp.presets.expand') }}
      </button>
    </div>

    <!-- Presets Grid -->
    <div
      v-show="showPresetsPanel"
      class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4"
    >
      <!-- Loading State -->
      <div
        v-if="loading"
        class="col-span-full flex justify-center py-8"
      >
        <div class="w-8 h-8 rounded-full border-3 border-accent-secondary/30 border-t-accent-secondary animate-spin" />
      </div>

      <!-- Preset Cards -->
      <div
        v-for="preset in presets"
        v-else
        :key="preset.id"
        class="group relative rounded-2xl p-4 border border-border-default/15 bg-gradient-to-br from-white/5 to-white/10 hover:border-accent-secondary/30 hover:shadow-lg transition-[border-color,box-shadow] duration-300 cursor-pointer"
        @click="handlePresetClick(preset)"
      >
        <!-- Tags Badge -->
        <div class="flex flex-wrap gap-1.5 mb-3">
          <span
            v-for="tag in preset.tags.slice(0, 2)"
            :key="tag"
            class="px-2 py-0.5 rounded-full text-[10px] font-medium bg-accent-secondary/10 text-accent-secondary"
          >
            {{ tag }}
          </span>
          <span
            v-if="preset.requires_api_key"
            class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-accent-warning/10 text-accent-warning"
          >
            <SIcon
              name="KeyRound"
              size="w-3 h-3"
            />
            API Key
          </span>
        </div>

        <!-- Name -->
        <h3 class="font-bold text-sm text-text-primary mb-1 truncate group-hover:text-accent-secondary transition-colors">
          {{ preset.name }}
        </h3>

        <!-- Description -->
        <p class="text-xs text-text-muted line-clamp-2 mb-3">
          {{ preset.description }}
        </p>

        <!-- Command Preview -->
        <div class="flex items-center gap-1.5 text-[10px] font-mono text-text-muted bg-bg-surface/50 rounded-lg px-2 py-1.5 overflow-hidden">
          <SIcon
            name="Terminal"
            size="w-3 h-3"
            class="flex-shrink-0"
          />
          <span class="truncate">{{ preset.command }} {{ (preset.args || []).join(' ') }}</span>
        </div>

        <!-- Hover Install Button -->
        <div class="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity rounded-2xl flex items-end justify-center pb-4">
          <button
            class="px-4 py-2 rounded-lg bg-accent-secondary text-white text-xs font-bold flex items-center gap-2 hover:bg-accent-secondary/90 transition-colors shadow-lg"
            @click.stop="handleInstall(preset)"
          >
            <SIcon
              name="Download"
              size="w-3.5 h-3.5"
            />
            {{ $t('mcp.presets.install') }}
          </button>
        </div>
      </div>
    </div>

    <!-- Install Modal -->
    <div
      v-if="showInstallModal && selectedPreset"
      class="fixed inset-0 bg-black/40 backdrop-blur-md flex items-center justify-center p-4 z-50"
      @click="closeInstallModal"
    >
      <div
        class="glass-effect rounded-3xl p-8 max-w-lg w-full shadow-2xl border border-border-default/30"
        @click.stop
      >
        <!-- Header -->
        <div class="flex items-center gap-4 mb-6">
          <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-accent-secondary to-accent-primary flex items-center justify-center text-white">
            <SIcon
              name="Sparkles"
              size="w-6 h-6"
            />
          </div>
          <div>
            <h3 class="text-xl font-bold text-text-primary">
              {{ selectedPreset.name }}
            </h3>
            <p class="text-sm text-text-muted">
              {{ selectedPreset.description }}
            </p>
          </div>
        </div>

        <!-- Platform Selection -->
        <div class="mb-6">
          <label class="block text-xs font-bold text-text-secondary uppercase tracking-wider mb-3">
            {{ $t('mcp.presets.selectPlatforms') }}
          </label>
          <div class="grid grid-cols-2 sm:grid-cols-5 gap-2">
            <button
              v-for="platform in platforms"
              :key="platform.id"
              class="px-3 py-2 rounded-xl text-xs font-medium flex items-center justify-center gap-2 transition-colors border"
              :class="selectedPlatforms.includes(platform.id)
                ? 'bg-accent-secondary/20 text-accent-secondary border-accent-secondary/30'
                : 'bg-bg-surface text-text-muted border-transparent hover:border-border-default'"
              @click="togglePlatform(platform.id)"
            >
              <SIcon
                :name="platform.icon"
                size="w-3.5 h-3.5"
              />
              <span>{{ platform.name }}</span>
            </button>
          </div>
        </div>

        <!-- API Key Input (if required) -->
        <div
          v-if="selectedPreset.requires_api_key && selectedPreset.api_key_env"
          class="mb-6"
        >
          <label class="block text-xs font-bold text-text-secondary uppercase tracking-wider mb-2">
            {{ selectedPreset.api_key_env }}
            <span class="text-accent-danger">*</span>
          </label>
          <input
            v-model="apiKeyValue"
            type="password"
            class="w-full px-4 py-3 rounded-xl bg-bg-surface/700 border border-border-default focus:border-accent-secondary focus:ring-4 focus:ring-accent-secondary/10 outline-none transition-[border-color,box-shadow] font-mono text-sm"
            :placeholder="`${$t('mcp.presets.enterApiKey')} ${selectedPreset.api_key_env}`"
          >
          <p class="text-xs text-text-muted mt-2">
            {{ $t('mcp.presets.apiKeyHint') }}
          </p>
        </div>

        <!-- Command Preview -->
        <div class="mb-6 p-4 rounded-xl bg-bg-surface/50 border border-border-default/50">
          <div class="text-xs font-medium text-text-muted mb-2">
            {{ $t('mcp.presets.commandPreview') }}
          </div>
          <code class="text-sm font-mono text-accent-secondary break-all">
            {{ selectedPreset.command }} {{ (selectedPreset.args || []).join(' ') }}
          </code>
        </div>

        <!-- Links -->
        <div
          v-if="selectedPreset.homepage || selectedPreset.docs"
          class="flex gap-3 mb-6"
        >
          <a
            v-if="selectedPreset.homepage"
            :href="selectedPreset.homepage"
            target="_blank"
            class="text-xs text-accent-secondary hover:underline flex items-center gap-1"
          >
            <SIcon
              name="ExternalLink"
              size="w-3 h-3"
            />
            {{ $t('mcp.presets.homepage') }}
          </a>
          <a
            v-if="selectedPreset.docs"
            :href="selectedPreset.docs"
            target="_blank"
            class="text-xs text-accent-secondary hover:underline flex items-center gap-1"
          >
            <SIcon
              name="Book"
              size="w-3 h-3"
            />
            {{ $t('mcp.presets.documentation') }}
          </a>
        </div>

        <!-- Actions -->
        <div class="flex gap-4">
          <button
            class="flex-1 px-6 py-3.5 rounded-xl font-bold transition-colors bg-white text-text-secondary hover:bg-bg-surface border border-border-default"
            @click="closeInstallModal"
          >
            {{ $t('common.cancel') }}
          </button>
          <button
            class="flex-1 px-6 py-3.5 rounded-xl font-bold transition-[box-shadow,transform] bg-accent-secondary text-white shadow-lg shadow-accent-secondary/20 hover:shadow-xl hover:shadow-accent-secondary/30 hover:-translate-y-0.5 flex items-center justify-center gap-2"
            :disabled="installing || selectedPlatforms.length === 0"
            @click="confirmInstall"
          >
            <SIcon
              v-if="installing"
              name="Loader2"
              size="w-4 h-4"
              class="animate-spin"
            />
            <SIcon
              v-else
              name="Download"
              size="w-4 h-4"
            />
            {{ installing ? $t('mcp.presets.installing') : $t('mcp.presets.confirmInstall') }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import SIcon from '@/components/ui/SIcon.vue'
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  listMcpPresets,
  installMcpPreset,
  type McpPreset,
  type SyncResult
} from '@/api'
import { logger } from '@/utils/logger'

const { t } = useI18n({ useScope: 'global' })

const emit = defineEmits<{
  (e: 'installed'): void
}>()

// State
const showPresetsPanel = ref(true)
const loading = ref(true)
const presets = ref<McpPreset[]>([])
const showInstallModal = ref(false)
const selectedPreset = ref<McpPreset | null>(null)
const selectedPlatforms = ref<string[]>(['claude'])
const apiKeyValue = ref('')
const installing = ref(false)

// Available platforms
const platforms = [
  { id: 'claude', name: 'Claude', icon: 'Bot' },
  { id: 'codex', name: 'Codex', icon: 'Terminal' },
  { id: 'gemini', name: 'Antigravity CLI', icon: 'Sparkles' },
]

// Load presets
const loadPresets = async () => {
  try {
    loading.value = true
    presets.value = await listMcpPresets()
  } catch (err) {
    logger.error('Failed to load MCP presets:', err)
  } finally {
    loading.value = false
  }
}

// Handle preset click
const handlePresetClick = (preset: McpPreset) => {
  selectedPreset.value = preset
  selectedPlatforms.value = ['claude']
  apiKeyValue.value = ''
  showInstallModal.value = true
}

// Handle install button
const handleInstall = (preset: McpPreset) => {
  handlePresetClick(preset)
}

// Toggle platform selection
const togglePlatform = (platformId: string) => {
  const index = selectedPlatforms.value.indexOf(platformId)
  if (index === -1) {
    selectedPlatforms.value.push(platformId)
  } else {
    selectedPlatforms.value.splice(index, 1)
  }
}

// Close modal
const closeInstallModal = () => {
  showInstallModal.value = false
  selectedPreset.value = null
  apiKeyValue.value = ''
}

// Confirm installation
const confirmInstall = async () => {
  if (!selectedPreset.value || selectedPlatforms.value.length === 0) return

  // Check API key requirement
  if (selectedPreset.value.requires_api_key && selectedPreset.value.api_key_env && !apiKeyValue.value) {
    alert(t('mcp.presets.apiKeyRequired'))
    return
  }

  installing.value = true

  try {
    const env: Record<string, string> = {}
    if (selectedPreset.value.api_key_env && apiKeyValue.value) {
      env[selectedPreset.value.api_key_env] = apiKeyValue.value
    }

    const result = await installMcpPreset(
      selectedPreset.value.id,
      selectedPlatforms.value,
      env
    )

    // Check results
    const failed = (result.results as SyncResult[]).filter((r: SyncResult) => !r.success)
    if (failed.length > 0) {
      const failedPlatforms = failed.map((f: SyncResult) => `${f.platform}: ${f.message}`).join('\n')
      alert(`${t('mcp.presets.installPartialFailed')}\n\n${failedPlatforms}`)
    } else {
      alert(t('mcp.presets.installSuccess'))
    }

    closeInstallModal()
    emit('installed')
  } catch (err) {
    logger.error('Failed to install preset:', err)
    alert(`${t('mcp.presets.installFailed')}: ${err instanceof Error ? err.message : 'Unknown error'}`)
  } finally {
    installing.value = false
  }
}

onMounted(() => {
  loadPresets()
})
</script>
