// ccr-ui/src/components/sync/SyncPassphraseModal.vue
<template>
  <BaseModal
    :model-value="modelValue"
    size="sm"
    surface="solid"
    :title="$t('sync.passphrase.title')"
    :description="$t('sync.passphrase.description')"
    @update:model-value="handleModelValue"
    @close="close"
  >
    <form
      class="sync-passphrase-form"
      @submit.prevent="submit"
    >
      <p class="sync-passphrase-target">
        <SIcon
          name="ShieldCheck"
          size="w-4 h-4"
        />
        <span>{{ assetName || $t('sync.passphrase.allAssets') }}</span>
      </p>

      <Input
        v-model="passphrase"
        type="password"
        :label="$t('sync.passphrase.label')"
        :placeholder="$t('sync.passphrase.placeholder')"
      />

      <label class="sync-passphrase-migration">
        <input
          v-model="migratePlaintextV1"
          type="checkbox"
        >
        <span>
          <strong>{{ $t('sync.passphrase.migrateTitle') }}</strong>
          <small>{{ $t('sync.passphrase.migrateDescription') }}</small>
        </span>
      </label>
    </form>

    <template #footer>
      <button
        type="button"
        class="sync-passphrase-button sync-passphrase-button--secondary"
        @click="close"
      >
        {{ $t('common.cancel') }}
      </button>
      <button
        type="button"
        class="sync-passphrase-button sync-passphrase-button--primary"
        :disabled="passphrase.length === 0"
        @click="submit"
      >
        <SIcon
          name="KeyRound"
          size="w-4 h-4"
        />
        {{ $t('sync.passphrase.continue') }}
      </button>
    </template>
  </BaseModal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import BaseModal from '@/components/common/BaseModal.vue'
import Input from '@/components/ui/Input.vue'
import SIcon from '@/components/ui/SIcon.vue'

const props = withDefaults(defineProps<{
  modelValue: boolean
  assetName?: string
}>(), {
  assetName: '',
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  'submit': [payload: { passphrase: string; migratePlaintextV1: boolean }]
}>()

const passphrase = ref('')
const migratePlaintextV1 = ref(false)

const clear = () => {
  passphrase.value = ''
  migratePlaintextV1.value = false
}

const close = () => {
  clear()
  emit('update:modelValue', false)
}

const handleModelValue = (value: boolean) => {
  if (!value) close()
}

const submit = () => {
  if (!passphrase.value) return
  const payload = {
    passphrase: passphrase.value,
    migratePlaintextV1: migratePlaintextV1.value,
  }
  clear()
  emit('update:modelValue', false)
  emit('submit', payload)
}

watch(() => props.modelValue, (isOpen) => {
  if (!isOpen) clear()
})
</script>

<style scoped>
.sync-passphrase-form {
  display: grid;
  gap: 16px;
}

.sync-passphrase-target {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--color-text-secondary);
  font-size: 13px;
}

.sync-passphrase-migration {
  display: grid;
  grid-template-columns: 18px minmax(0, 1fr);
  align-items: start;
  gap: 10px;
  cursor: pointer;
}

.sync-passphrase-migration input {
  width: 16px;
  height: 16px;
  margin-top: 2px;
  accent-color: var(--color-accent-primary);
}

.sync-passphrase-migration span {
  display: grid;
  gap: 3px;
}

.sync-passphrase-migration strong {
  color: var(--color-text-primary);
  font-size: 13px;
  font-weight: 600;
}

.sync-passphrase-migration small {
  color: var(--color-text-secondary);
  font-size: 12px;
  line-height: 1.5;
}

.sync-passphrase-button {
  display: inline-flex;
  min-height: 36px;
  align-items: center;
  justify-content: center;
  gap: 7px;
  border-radius: 6px;
  padding: 0 14px;
  font-size: 13px;
  font-weight: 600;
}

.sync-passphrase-button--secondary {
  border: 1px solid var(--color-border-default);
  color: var(--color-text-secondary);
}

.sync-passphrase-button--primary {
  background: var(--color-accent-primary);
  color: white;
}

.sync-passphrase-button--primary:disabled {
  cursor: not-allowed;
  opacity: 0.45;
}
</style>

// ccr-ui/src/features/sync/SyncPassphraseModal.tsx
import { useCallback, useEffect, type FormEvent } from 'react'
import { useForm } from 'react-hook-form'
import { BaseModal, Checkbox, SIcon } from '@/ui'
import { useSyncT } from './locale'
import './styles/sync-passphrase.css'

interface PassphraseForm {
  passphrase: string
  migratePlaintextV1: boolean
}

interface SyncPassphraseModalProps {
  open: boolean
  assetName?: string
  onOpenChange: (open: boolean) => void
  onSubmit: (payload: { passphrase: string; migratePlaintextV1: boolean }) => void
}

export function SyncPassphraseModal({ open, assetName, onOpenChange, onSubmit }: SyncPassphraseModalProps) {
  const t = useSyncT()
  const form = useForm<PassphraseForm>({ defaultValues: { passphrase: '', migratePlaintextV1: false } })
  const passphrase = form.watch('passphrase')
  const migrate = form.watch('migratePlaintextV1')

  const clear = useCallback(() => {
    form.reset({ passphrase: '', migratePlaintextV1: false })
  }, [form])

  const close = useCallback(() => {
    clear()
    onOpenChange(false)
  }, [clear, onOpenChange])

  const handleOpenChange = useCallback((next: boolean) => {
    if (!next) close()
  }, [close])

  const submit = useCallback(() => {
    const values = form.getValues()
    if (!values.passphrase) return
    const payload = { passphrase: values.passphrase, migratePlaintextV1: values.migratePlaintextV1 }
    clear()
    onOpenChange(false)
    onSubmit(payload)
  }, [clear, form, onOpenChange, onSubmit])

  const handleFormSubmit = useCallback((event: FormEvent) => {
    event.preventDefault()
    submit()
  }, [submit])

  const handleMigrate = useCallback((value: boolean | 'indeterminate') => {
    form.setValue('migratePlaintextV1', value === true)
  }, [form])

  useEffect(() => {
    if (!open) clear()
  }, [clear, open])

  return (
    <BaseModal
      modelValue={open}
      size="sm"
      surface="solid"
      title={t('sync.passphrase.title')}
      description={t('sync.passphrase.description')}
      onUpdateModelValue={handleOpenChange}
      onClose={close}
      footer={
        <div className="flex w-full gap-3">
          <button type="button" className="sync-passphrase-button sync-passphrase-button--secondary" onClick={close}>
            {t('common.cancel')}
          </button>
          <button type="button" className="sync-passphrase-button sync-passphrase-button--primary" disabled={passphrase.length === 0} onClick={submit}>
            <SIcon name="KeyRound" size="w-4 h-4" />
            {t('sync.passphrase.continue')}
          </button>
        </div>
      }
    >
      <form className="sync-passphrase-form" onSubmit={handleFormSubmit}>
        <p className="sync-passphrase-target">
          <SIcon name="ShieldCheck" size="w-4 h-4" />
          <span>{assetName || t('sync.passphrase.allAssets')}</span>
        </p>
        <label className="grid gap-1 text-sm text-text-secondary">
          {t('sync.passphrase.label')}
          <input type="password" className="rounded-lg border border-border-default bg-bg-surface px-3 py-2" placeholder={t('sync.passphrase.placeholder')} {...form.register('passphrase')} />
        </label>
        <label className="sync-passphrase-migration">
          <Checkbox checked={migrate} onCheckedChange={handleMigrate} />
          <span>
            <strong>{t('sync.passphrase.migrateTitle')}</strong>
            <small>{t('sync.passphrase.migrateDescription')}</small>
          </span>
        </label>
      </form>
    </BaseModal>
  )
}
