// ccr-ui/src/views/codex/tabs/CodexAuthAccountsTab.vue
<template>
  <div class="codex-auth-accounts-tab">
    <Card
      v-if="currentInfo"
      surface="workspace"
      :elevation="2"
      motion="subtle"
      padding="lg"
    >
      <div class="codex-auth-view__section-header">
        <SIcon
          name="Info"
          size="w-5 h-5"
          class="codex-auth-view__section-icon"
        />
        <h3 class="codex-auth-view__section-title">
          {{ $t('codex.auth.currentSession') }}
        </h3>
      </div>
      <div class="codex-auth-view__session-grid">
        <div class="codex-auth-view__session-field">
          <span class="codex-auth-view__field-label">
            {{ $t('codex.auth.fields.accountId') }}
          </span>
          <code class="codex-auth-view__field-code">
            {{ currentInfo.account_id }}
          </code>
        </div>
        <div class="codex-auth-view__session-field">
          <span class="codex-auth-view__field-label">
            {{ $t('codex.auth.fields.email') }}
          </span>
          <span class="codex-auth-view__field-value codex-auth-view__field-value--truncate">
            {{ currentInfo.email || $t('codex.auth.status.notAvailable') }}
          </span>
        </div>
        <div class="codex-auth-view__session-field">
          <span class="codex-auth-view__field-label">
            {{ tf('codex.auth.fields.authMethod', 'Auth method') }}
          </span>
          <span class="codex-auth-view__field-value codex-auth-view__field-value--muted">
            {{ formatAuthMethod(currentInfo.auth_method || '') }}
          </span>
        </div>
        <div class="codex-auth-view__session-field">
          <span class="codex-auth-view__field-label">
            {{ tf('codex.auth.fields.planType', 'Plan') }}
          </span>
          <span class="codex-auth-view__field-value codex-auth-view__field-value--muted">
            {{ currentInfo.plan_type || $t('codex.auth.status.notAvailable') }}
          </span>
        </div>
        <div class="codex-auth-view__session-field">
          <span class="codex-auth-view__field-label">
            {{ $t('codex.auth.fields.lastRefresh') }}
          </span>
          <span class="codex-auth-view__field-value codex-auth-view__field-value--muted">
            {{ currentInfo.last_refresh || $t('codex.auth.status.notAvailable') }}
          </span>
        </div>
      </div>
    </Card>

    <Card
      surface="workspace"
      :elevation="2"
      motion="subtle"
      padding="lg"
      :glow-color="canManageAuthAccounts ? 'success' : 'warning'"
    >
      <div class="codex-auth-view__guard">
        <div
          class="codex-auth-view__guard-icon-shell"
          :class="
            canManageAuthAccounts
              ? 'bg-emerald-500/10 text-emerald-400'
              : 'bg-yellow-500/10 text-yellow-400'
          "
        >
          <SIcon
            name="AlertTriangle"
            size="w-5 h-5"
          />
        </div>
        <div class="codex-auth-view__guard-body">
          <p class="codex-auth-view__guard-title">
            {{ $t('codex.auth.profileGuard.title') }}
          </p>
          <p class="codex-auth-view__guard-message">
            {{ profileGuardMessage }}
          </p>
          <p
            v-if="authActionError"
            class="codex-auth-view__guard-error"
          >
            {{ authActionError }}
          </p>
        </div>
      </div>
    </Card>

    <Card
      v-if="!loading && accounts.length > 0"
      surface="workspace"
      :elevation="2"
      motion="subtle"
      padding="lg"
      class="codex-auth-view__filters-card"
    >
      <div class="codex-auth-view__filters-grid">
        <label class="codex-auth-view__search-box">
          <SIcon
            name="Search"
            size="w-4 h-4"
          />
          <input
            :value="searchQuery"
            type="text"
            :placeholder="$t('codex.auth.filters.searchPlaceholder')"
            @input="$emit('update:searchQuery', ($event.target as HTMLInputElement).value)"
          >
        </label>

        <div class="codex-auth-view__filter-group">
          <p class="codex-auth-view__filter-label">
            {{ $t('codex.auth.filters.statusLabel') }}
          </p>
          <div class="codex-auth-view__filter-row">
            <button
              v-for="option in statusOptions"
              :key="option.value"
              type="button"
              class="codex-auth-view__filter-pill"
              :class="{
                'codex-auth-view__filter-pill--active': statusFilter === option.value,
              }"
              @click="$emit('update:statusFilter', option.value)"
            >
              {{ option.label }}
            </button>
          </div>
        </div>

        <div class="codex-auth-view__filter-group">
          <label
            class="codex-auth-view__filter-label"
            for="codex-auth-plan-filter"
          >
            {{ $t('codex.auth.filters.planLabel') }}
          </label>
          <select
            id="codex-auth-plan-filter"
            :value="planFilter"
            class="codex-auth-view__filter-select"
            @change="$emit('update:planFilter', ($event.target as HTMLSelectElement).value as AccountPlanFilter)"
          >
            <option
              v-for="option in planOptions"
              :key="option.value"
              :value="option.value"
            >
              {{ option.label }}
            </option>
          </select>
        </div>

        <div class="codex-auth-view__filter-group">
          <label
            class="codex-auth-view__filter-label"
            for="codex-auth-sort"
          >
            {{ $t('codex.auth.filters.sortLabel') }}
          </label>
          <select
            id="codex-auth-sort"
            :value="sortBy"
            class="codex-auth-view__filter-select"
            @change="$emit('update:sortBy', ($event.target as HTMLSelectElement).value as AccountSort)"
          >
            <option
              v-for="option in sortOptions"
              :key="option.value"
              :value="option.value"
            >
              {{ option.label }}
            </option>
          </select>
        </div>
      </div>

      <div class="codex-auth-view__filters-footer">
        <p class="codex-auth-view__filters-summary">
          {{ filtersResultsCount }}
        </p>
        <Button
          v-if="hasActiveFilters"
          variant="secondary"
          surface="status"
          density="compact"
          motion="subtle"
          @click="$emit('clearFilters')"
        >
          {{ $t('common.clearFilters') }}
        </Button>
      </div>
    </Card>

    <div
      v-if="loading"
      class="flex justify-center py-20"
    >
      <div
        class="w-12 h-12 rounded-full border-4 border-transparent border-t-accent-primary border-r-accent-secondary animate-spin"
      />
    </div>

    <div
      v-else-if="accounts.length === 0"
      class="empty-state glass-effect rounded-2xl border border-border-default/10"
    >
      <div class="p-4 rounded-full glass-surface mb-4">
        <SIcon
          name="KeyRound"
          size="w-8 h-8"
          class="text-text-muted"
        />
      </div>
      <p class="text-text-primary">
        {{ $t('codex.auth.emptyState') }}
      </p>
      <p class="text-sm text-text-muted mt-2">
        {{
          tf(
            'codex.auth.emptyStateHintV2',
            'Add a new account through OAuth, API key, token JSON, or import the local runtime snapshot.'
          )
        }}
      </p>
      <Button
        variant="primary"
        surface="card"
        density="compact"
        motion="standard"
        class="mt-4"
        @click="$emit('openAddAccount')"
      >
        <template #leading>
          <SIcon
            name="Plus"
            size="w-4 h-4"
          />
        </template>
        {{ tf('codex.auth.actions.addAccount', 'Add account') }}
      </Button>
    </div>

    <div
      v-else-if="filteredAccounts.length === 0"
      class="empty-state glass-effect rounded-2xl border border-border-default/10"
    >
      <div class="p-4 rounded-full glass-surface mb-4">
        <SIcon
          name="Search"
          size="w-8 h-8"
          class="text-text-muted"
        />
      </div>
      <p class="text-text-primary">
        {{ $t('codex.auth.filters.noResultsTitle') }}
      </p>
      <p class="text-sm text-text-muted mt-2">
        {{ $t('codex.auth.filters.noResultsHint') }}
      </p>
      <Button
        variant="secondary"
        surface="status"
        density="compact"
        motion="subtle"
        class="mt-4"
        @click="$emit('clearFilters')"
      >
        {{ $t('common.clearFilters') }}
      </Button>
    </div>

    <div
      v-else
      class="grid grid-cols-1 xl:grid-cols-2 gap-4"
    >
      <CodexAccountCard
        v-for="account in filteredAccounts"
        :key="account.name"
        :account="account"
        :quota="quotaMap.get(account.name) ?? null"
        :quota-loading="quotaLoading"
        :is-current="account.is_current"
        :busy-action="busyName === account.name ? busyAction : null"
        :disabled="actionLoading"
        @switch="$emit('switch', $event)"
        @delete="$emit('delete', $event)"
        @refresh="$emit('refresh', $event)"
        @tag="$emit('tag', $event)"
        @export="$emit('export', $event)"
        @rename="$emit('rename', $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { CodexAuthAccountItem, CodexAuthCurrentInfo, CodexAccountQuota } from '@/types'
import type { AccountStatusFilter, AccountPlanFilter, AccountSort } from '@/views/codex/codexAuthAccounts'
import SIcon from '@/components/ui/SIcon.vue'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
import CodexAccountCard from '@/components/codex/CodexAccountCard.vue'
import { useTf } from '@/composables/useTf'

defineOptions({ name: 'CodexAuthAccountsTab' })

interface Props {
  loading: boolean
  accounts: CodexAuthAccountItem[]
  currentInfo: CodexAuthCurrentInfo | null
  canManageAuthAccounts: boolean
  profileGuardMessage: string
  authActionError: string | null
  searchQuery: string
  statusFilter: AccountStatusFilter
  planFilter: AccountPlanFilter
  sortBy: AccountSort
  statusOptions: Array<{ value: AccountStatusFilter; label: string }>
  planOptions: Array<{ value: AccountPlanFilter; label: string }>
  sortOptions: Array<{ value: AccountSort; label: string }>
  filteredAccounts: CodexAuthAccountItem[]
  filtersResultsCount: string
  hasActiveFilters: boolean
  quotaMap: Map<string, CodexAccountQuota>
  quotaLoading: boolean
  busyName: string | null
  busyAction: 'switch' | 'delete' | null
  actionLoading: boolean
  formatAuthMethod: (method: string) => string
}

defineProps<Props>()

defineEmits<{
  'update:searchQuery': [value: string]
  'update:statusFilter': [value: AccountStatusFilter]
  'update:planFilter': [value: AccountPlanFilter]
  'update:sortBy': [value: AccountSort]
  clearFilters: []
  openAddAccount: []
  switch: [name: string]
  delete: [name: string]
  refresh: [name: string]
  tag: [name: string]
  export: [name: string]
  rename: [name: string]
}>()

const tf = useTf()
</script>

<style scoped>
/* 样式继承自 CodexAuthView.vue，无需重复定义 */
</style>

// ccr-ui/src/features/codex/auth/CodexAuthAccountsTab.tsx
import { memo, useCallback, type ChangeEvent } from 'react'
import { useForm } from 'react-hook-form'
import type { CodexAccountQuota, CodexAuthAccountItem, CodexAuthCurrentInfo } from '@/types'
import { EmptyState, SIcon, buttonClass } from '@/ui'
import type { AccountPlanFilter, AccountSort, AccountStatusFilter } from '../codexAuthAccounts'
import { panelCardClass } from '../ui-classes'
import { CodexAccountCard } from './CodexAccountCard'
import { useAppT } from '@/i18n'
import type { CodexTf } from '../useCodexLocale'

interface FilterOption<T extends string> {
  value: T
  label: string
}

interface CodexAuthAccountsTabProps {
  loading: boolean
  accounts: CodexAuthAccountItem[]
  currentInfo: CodexAuthCurrentInfo | null
  canManageAuthAccounts: boolean
  profileGuardMessage: string
  authActionError: string | null
  searchQuery: string
  statusFilter: AccountStatusFilter
  planFilter: AccountPlanFilter
  sortBy: AccountSort
  statusOptions: FilterOption<AccountStatusFilter>[]
  planOptions: FilterOption<AccountPlanFilter>[]
  sortOptions: FilterOption<AccountSort>[]
  filteredAccounts: CodexAuthAccountItem[]
  filtersResultsCount: string
  hasActiveFilters: boolean
  quotaMap: Map<string, CodexAccountQuota>
  quotaLoading: boolean
  busyName: string | null
  busyAction: 'switch' | 'delete' | null
  actionLoading: boolean
  formatAuthMethod: (method: string) => string
  tf: CodexTf
  onSearchQueryChange: (value: string) => void
  onStatusFilterChange: (value: AccountStatusFilter) => void
  onPlanFilterChange: (value: AccountPlanFilter) => void
  onSortByChange: (value: AccountSort) => void
  onClearFilters: () => void
  onOpenAddAccount: () => void
  onSwitch: (name: string) => void
  onDelete: (name: string) => void
  onRefresh: (name: string) => void
  onTag: (name: string) => void
  onExport: (name: string) => void
  onRename: (name: string) => void
}

const StatusPill = memo(function StatusPill({
  option,
  active,
  onSelect,
}: {
  option: FilterOption<AccountStatusFilter>
  active: boolean
  onSelect: (value: AccountStatusFilter) => void
}) {
  const handleClick = useCallback(() => onSelect(option.value), [onSelect, option.value])
  return (
    <button
      type="button"
      className={active ? 'codex-auth-view__filter-pill codex-auth-view__filter-pill--active' : 'codex-auth-view__filter-pill'}
      onClick={handleClick}
    >
      {option.label}
    </button>
  )
})

export function CodexAuthAccountsTab({
  loading,
  accounts,
  currentInfo,
  canManageAuthAccounts,
  profileGuardMessage,
  authActionError,
  searchQuery,
  statusFilter,
  planFilter,
  sortBy,
  statusOptions,
  planOptions,
  sortOptions,
  filteredAccounts,
  filtersResultsCount,
  hasActiveFilters,
  quotaMap,
  quotaLoading,
  busyName,
  busyAction,
  actionLoading,
  formatAuthMethod,
  tf,
  onSearchQueryChange,
  onStatusFilterChange,
  onPlanFilterChange,
  onSortByChange,
  onClearFilters,
  onOpenAddAccount,
  onSwitch,
  onDelete,
  onRefresh,
  onTag,
  onExport,
  onRename,
}: CodexAuthAccountsTabProps) {
  const t = useAppT()
  const searchForm = useForm({ defaultValues: { q: searchQuery } })
  const handleSearch = searchForm.register('q', {
    onChange: (event: ChangeEvent<HTMLInputElement>) => onSearchQueryChange(event.target.value),
  })
  const handlePlan = useCallback(
    (event: ChangeEvent<HTMLSelectElement>) => onPlanFilterChange(event.target.value as AccountPlanFilter),
    [onPlanFilterChange],
  )
  const handleSort = useCallback(
    (event: ChangeEvent<HTMLSelectElement>) => onSortByChange(event.target.value as AccountSort),
    [onSortByChange],
  )

  return (
    <div className="codex-auth-accounts-tab space-y-4">
      {currentInfo ? (
        <section className={panelCardClass}>
          <div className="codex-auth-view__section-header">
            <SIcon name="Info" size="w-5 h-5" className="codex-auth-view__section-icon" />
            <h3 className="codex-auth-view__section-title">{t('codex.auth.currentSession')}</h3>
          </div>
          <div className="codex-auth-view__session-grid">
            <div className="codex-auth-view__session-field">
              <span className="codex-auth-view__field-label">{t('codex.auth.fields.accountId')}</span>
              <code className="codex-auth-view__field-code">{currentInfo.account_id}</code>
            </div>
            <div className="codex-auth-view__session-field">
              <span className="codex-auth-view__field-label">{t('codex.auth.fields.email')}</span>
              <span className="codex-auth-view__field-value">{currentInfo.email || t('codex.auth.status.notAvailable')}</span>
            </div>
            <div className="codex-auth-view__session-field">
              <span className="codex-auth-view__field-label">{tf('codex.auth.fields.authMethod', 'Auth method')}</span>
              <span className="codex-auth-view__field-value">{formatAuthMethod(currentInfo.auth_method || '')}</span>
            </div>
          </div>
        </section>
      ) : null}

      <section className={panelCardClass}>
        <div className="codex-auth-view__guard">
          <div className={canManageAuthAccounts ? 'codex-auth-view__guard-icon-shell bg-accent-success/10 text-accent-success' : 'codex-auth-view__guard-icon-shell bg-accent-warning/10 text-accent-warning'}>
            <SIcon name="AlertTriangle" size="w-5 h-5" />
          </div>
          <div className="codex-auth-view__guard-body">
            <p className="codex-auth-view__guard-title">{t('codex.auth.profileGuard.title')}</p>
            <p className="codex-auth-view__guard-message">{profileGuardMessage}</p>
            {authActionError ? <p className="codex-auth-view__guard-error">{authActionError}</p> : null}
          </div>
        </div>
      </section>

      {!loading && accounts.length > 0 ? (
        <section className={`${panelCardClass} codex-auth-view__filters-card`}>
          <div className="codex-auth-view__filters-grid">
            <label className="codex-auth-view__search-box">
              <SIcon name="Search" size="w-4 h-4" />
              <input type="text" placeholder={t('codex.auth.filters.searchPlaceholder')} {...handleSearch} />
            </label>
            <div className="codex-auth-view__filter-group">
              <p className="codex-auth-view__filter-label">{t('codex.auth.filters.statusLabel')}</p>
              <div className="codex-auth-view__filter-row">
                {statusOptions.map((option) => (
                  <StatusPill key={option.value} option={option} active={statusFilter === option.value} onSelect={onStatusFilterChange} />
                ))}
              </div>
            </div>
            <label className="codex-auth-view__filter-group">
              <span className="codex-auth-view__filter-label">{t('codex.auth.filters.planLabel')}</span>
              <select className="codex-auth-view__filter-select" value={planFilter} onChange={handlePlan}>
                {planOptions.map((option) => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>
            </label>
            <label className="codex-auth-view__filter-group">
              <span className="codex-auth-view__filter-label">{t('codex.auth.filters.sortLabel')}</span>
              <select className="codex-auth-view__filter-select" value={sortBy} onChange={handleSort}>
                {sortOptions.map((option) => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>
            </label>
          </div>
          <div className="codex-auth-view__filters-footer">
            <p className="codex-auth-view__filters-summary">{filtersResultsCount}</p>
            {hasActiveFilters ? (
              <button type="button" className={buttonClass({ variant: 'ghost' })} onClick={onClearFilters}>{t('common.clearFilters')}</button>
            ) : null}
          </div>
        </section>
      ) : null}

      {loading ? (
        <div className="flex justify-center py-20">
          <div className="h-12 w-12 animate-spin rounded-full border-4 border-transparent border-t-accent-primary" />
        </div>
      ) : accounts.length === 0 ? (
        <EmptyState
          icon="KeyRound"
          title={t('codex.auth.emptyState')}
          description={tf('codex.auth.emptyStateHintV2', 'Add a new account through OAuth, API key, token JSON, or import the local runtime snapshot.')}
          actionText={tf('codex.auth.actions.addAccount', 'Add account')}
          actionIcon="Plus"
          onAction={onOpenAddAccount}
        />
      ) : filteredAccounts.length === 0 ? (
        <EmptyState
          icon="Search"
          title={t('codex.auth.filters.noResultsTitle')}
          description={t('codex.auth.filters.noResultsHint')}
          actionText={t('common.clearFilters')}
          onAction={onClearFilters}
        />
      ) : (
        <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
          {filteredAccounts.map((account) => (
            <CodexAccountCard
              key={account.name}
              account={account}
              quota={quotaMap.get(account.name) ?? null}
              quotaLoading={quotaLoading}
              isCurrent={account.is_current}
              busyAction={busyName === account.name ? busyAction : null}
              disabled={actionLoading}
              onSwitch={onSwitch}
              onDelete={onDelete}
              onRefresh={onRefresh}
              onTag={onTag}
              onExport={onExport}
              onRename={onRename}
            />
          ))}
        </div>
      )}
    </div>
  )
}
