// ccr-ui/src/components/dashboard/DashboardReadinessLedger.vue
<template>
  <section
    class="dashboard-ledger"
    data-dashboard-readiness
    :data-status="readiness.status"
    :aria-label="t('dashboard.readiness.label')"
  >
    <div class="dashboard-ledger__main">
      <p class="dashboard-ledger__eyebrow">
        <span
          class="dashboard-ledger__status-dot"
          aria-hidden="true"
        />
        {{ t(readiness.labelKey) }}
      </p>
      <h2 class="dashboard-ledger__title">
        {{ t(readiness.titleKey) }}
      </h2>
      <p class="dashboard-ledger__description">
        {{ t(readiness.descriptionKey) }}
      </p>

      <ul class="dashboard-ledger__reasons">
        <li
          v-for="reason in readiness.reasons"
          :key="reason.key"
          class="dashboard-ledger__reason"
          :data-ok="reason.ok"
        >
          <SIcon
            :name="reason.ok ? 'Check' : 'AlertTriangle'"
            size="w-3.5 h-3.5"
            class="dashboard-ledger__reason-icon"
          />
          {{ stripTrailingPeriod(t(reason.key)) }}
        </li>
      </ul>
    </div>

    <div class="dashboard-ledger__metrics">
      <StatTile
        v-for="metric in statusMetrics"
        :key="metric.id"
        :label="t(metric.labelKey)"
        :value="resolveValue(metric)"
        :hint="resolveHint(metric)"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import SIcon from '@/components/ui/SIcon.vue'
import StatTile from '@/components/ui/StatTile.vue'
import type {
  DashboardReadiness,
  DashboardStatusMetric,
} from '@/views/dashboard/dashboardPresentation'

defineProps<{
  readiness: DashboardReadiness
  statusMetrics: DashboardStatusMetric[]
}>()

const { t } = useI18n()

const resolveValue = (metric: DashboardStatusMetric) => {
  if (metric.valueKey) return t(metric.valueKey)
  return metric.value ?? '…'
}

const resolveHint = (metric: DashboardStatusMetric) => {
  if (metric.hint) return metric.hint
  if (metric.hintKey) return t(metric.hintKey)
  return ''
}

// 清单行结尾不需要句号，翻译文案沿用既有句子即可，这里统一裁掉中英文句号
const stripTrailingPeriod = (text: string) => text.replace(/[。.]$/, '')
</script>

<style scoped>
.dashboard-ledger {
  display: grid;
  grid-template-columns: minmax(16rem, 0.85fr) minmax(0, 1.4fr);
  gap: 1rem 1.25rem;
  align-items: start;
  height: 100%;
  padding: var(--home-card-pad);
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--home-card-radius);
  background: var(--color-bg-surface);
}

.dashboard-ledger__main {
  display: grid;
  align-content: start;
  gap: 0.45rem;
  min-width: 0;
}

.dashboard-ledger__eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 0.45rem;
  margin: 0;
  color: var(--color-text-muted);
  font-size: 0.8125rem;
  font-weight: 500;
  line-height: 1.24;
  letter-spacing: 0;
}

.dashboard-ledger__status-dot {
  width: 0.45rem;
  height: 0.45rem;
  border-radius: 999px;
  background: var(--color-text-muted);
}

.dashboard-ledger[data-status='ready'] .dashboard-ledger__status-dot {
  background: var(--color-success);
}

.dashboard-ledger[data-status='attention'] .dashboard-ledger__status-dot {
  background: var(--color-warning);
}

.dashboard-ledger[data-status='web-preview'] .dashboard-ledger__status-dot {
  background: var(--color-info);
}

.dashboard-ledger__title {
  margin: 0;
  color: var(--color-text-primary);
  font-size: 1.0625rem;
  font-weight: 600;
  line-height: 1.3;
  letter-spacing: 0;
}

.dashboard-ledger__description {
  margin: 0;
  color: var(--color-text-secondary);
  font-size: 0.8125rem;
  letter-spacing: 0;
  line-height: 1.5;
}

.dashboard-ledger__reasons {
  display: grid;
  align-content: start;
  gap: 0.28rem;
  margin: 0.15rem 0 0;
  padding: 0;
  list-style: none;
}

.dashboard-ledger__reason {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  color: var(--color-text-secondary);
  font-size: 0.8125rem;
  line-height: 1.45;
}

.dashboard-ledger__reason-icon {
  flex-shrink: 0;
  color: var(--color-text-disabled);
}

.dashboard-ledger__reason[data-ok='true'] .dashboard-ledger__reason-icon {
  color: var(--color-success);
}

.dashboard-ledger__reason[data-ok='false'] .dashboard-ledger__reason-icon {
  color: var(--color-warning);
}

.dashboard-ledger__metrics {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(7.5rem, 1fr));
  gap: 0.85rem 1rem;
  align-content: start;
  min-width: 0;
}

@media (width <= 960px) {
  .dashboard-ledger {
    grid-template-columns: 1fr;
  }
}
</style>

// ccr-ui/src/features/usage/dashboard/DashboardReadinessLedger.tsx
import { StatTile, SIcon } from '@/ui'
import type {
  DashboardReadiness,
  DashboardStatusMetric,
} from '@/views/dashboard/dashboardPresentation'
import { useUsageT } from '../translate'
import '../styles/dashboard-readiness-ledger.css'

interface DashboardReadinessLedgerProps {
  readiness: DashboardReadiness
  statusMetrics: DashboardStatusMetric[]
  className?: string
}

const stripTrailingPeriod = (text: string) => text.replace(/[。.]$/, '')

export function DashboardReadinessLedger({
  readiness,
  statusMetrics,
  className,
}: DashboardReadinessLedgerProps) {
  const t = useUsageT()

  return (
    <section
      className={['dashboard-ledger', className].filter(Boolean).join(' ')}
      data-dashboard-readiness
      data-status={readiness.status}
      aria-label={t('dashboard.readiness.label')}
    >
      <div className="dashboard-ledger__main">
        <p className="dashboard-ledger__eyebrow">
          <span className="dashboard-ledger__status-dot" aria-hidden="true" />
          {t(readiness.labelKey)}
        </p>
        <h2 className="dashboard-ledger__title">{t(readiness.titleKey)}</h2>
        <p className="dashboard-ledger__description">{t(readiness.descriptionKey)}</p>
        <ul className="dashboard-ledger__reasons">
          {readiness.reasons.map((reason) => (
            <li
              key={reason.key}
              className="dashboard-ledger__reason"
              data-ok={reason.ok}
            >
              <SIcon
                name={reason.ok ? 'Check' : 'AlertTriangle'}
                size="w-3.5 h-3.5"
                className="dashboard-ledger__reason-icon"
              />
              {stripTrailingPeriod(t(reason.key))}
            </li>
          ))}
        </ul>
      </div>
      <div className="dashboard-ledger__metrics">
        {statusMetrics.map((metric) => (
          <StatTile
            key={metric.id}
            label={t(metric.labelKey)}
            value={metric.valueKey ? t(metric.valueKey) : metric.value ?? '…'}
            hint={metric.hint ?? (metric.hintKey ? t(metric.hintKey) : '')}
            tone={metric.tone}
          />
        ))}
      </div>
    </section>
  )
}
