// ccr-ui/src/shell/GlobalConfirmDialog.tsx
import { useUIStore } from '@/shell/stores/ui'
import { ConfirmModal } from '@/ui/confirm-modal'

export function GlobalConfirmDialog() {
  const confirmDialog = useUIStore((state) => state.confirmDialog)
  const resolveConfirmDialog = useUIStore((state) => state.resolveConfirmDialog)

  if (!confirmDialog) return null

  return (
    <ConfirmModal
      isOpen
      title={confirmDialog.title}
      message={confirmDialog.message}
      confirmText={confirmDialog.confirmText}
      cancelText={confirmDialog.cancelText}
      type={confirmDialog.type}
      surface={confirmDialog.surface}
      onConfirm={() => resolveConfirmDialog(true)}
      onCancel={() => resolveConfirmDialog(false)}
      onOpenChange={(open) => {
        if (!open) resolveConfirmDialog(false)
      }}
    />
  )
}

// ccr-ui/src/components/common/GlobalConfirmDialog.vue
<template>
  <ConfirmModal
    v-if="confirmDialog"
    :is-open="true"
    :title="confirmDialog.title"
    :message="confirmDialog.message"
    :confirm-text="confirmDialog.confirmText"
    :cancel-text="confirmDialog.cancelText"
    :type="confirmDialog.type"
    :surface="confirmDialog.surface"
    @confirm="handleConfirm"
    @cancel="handleCancel"
    @update:is-open="handleOpenChange"
  />
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useUIStore } from '@/stores/ui'
import ConfirmModal from '@/components/ConfirmModal.vue'

const uiStore = useUIStore()
const { confirmDialog } = storeToRefs(uiStore)

const handleConfirm = () => {
  uiStore.resolveConfirmDialog(true)
}

const handleCancel = () => {
  uiStore.resolveConfirmDialog(false)
}

const handleOpenChange = (isOpen: boolean) => {
  if (!isOpen) {
    handleCancel()
  }
}
</script>
