// ccr-ui/src/components/grok/GrokProfileCard.vue
<template>
  <article
    class="cp-card surface-status"
    :class="{ 'cp-card--active': isCurrent, 'cp-card--off': !profile.enabled }"
    :data-profile-name="profile.name"
  >
    <div class="cp-card__head">
      <span
        class="cp-card__dot"
        :class="{ 'cp-card__dot--good': isCurrent }"
      />
      <h3
        class="cp-card__name"
        :title="profile.name"
      >
        {{ profile.name }}
      </h3>
      <span class="cp-card__kind">{{ t(`grok.profiles.profileKinds.${profile.profile_kind}`) }}</span>
      <div class="cp-card__actions">
        <button
          v-if="!isCurrent"
          type="button"
          class="cp-card__apply"
          :disabled="disabled || !profile.enabled"
          @click="emit('apply', profile.name)"
        >
          <SIcon
            :name="busyAction === 'apply' ? 'RefreshCw' : 'Play'"
            size="w-3 h-3"
            :class="{ 'cp-card__spin': busyAction === 'apply' }"
          />
          {{ t('grok.profiles.actions.apply') }}
        </button>
        <span
          v-else
          class="cp-card__current"
        >{{ t('grok.profiles.currentActive') }}</span>
        <div class="cp-card__menu">
          <button
            ref="menuButton"
            type="button"
            class="cp-card__icon-btn"
            :disabled="disabled"
            :aria-expanded="menuOpen"
            :aria-label="t('grok.profiles.overflowMenu')"
            @click="toggleMenu"
          >
            <SIcon
              name="MenuDots"
              size="w-4 h-4"
            />
          </button>
          <div
            v-if="menuOpen"
            ref="menuPanel"
            class="cp-card__menu-pop"
            role="menu"
            @keydown="onMenuKeydown"
          >
            <button
              role="menuitem"
              type="button"
              class="cp-card__menu-item"
              @click="selectAction('edit')"
            >
              <SIcon
                name="Edit2"
                size="w-4 h-4"
              />{{ t('grok.profiles.actions.edit') }}
            </button>
            <button
              role="menuitem"
              type="button"
              class="cp-card__menu-item"
              @click="selectAction('toggle')"
            >
              <SIcon
                :name="profile.enabled ? 'Pause' : 'Play'"
                size="w-4 h-4"
              />
              {{ profile.enabled ? t('grok.profiles.actions.disable') : t('grok.profiles.actions.enable') }}
            </button>
            <button
              role="menuitem"
              type="button"
              class="cp-card__menu-item cp-card__menu-item--danger"
              @click="selectAction('delete')"
            >
              <SIcon
                :name="busyAction === 'delete' ? 'RefreshCw' : 'Trash2'"
                size="w-4 h-4"
              />
              {{ t('grok.profiles.actions.delete') }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <p
      v-if="profile.description"
      class="cp-card__desc"
    >
      {{ profile.description }}
    </p>

    <dl class="cp-card__fields">
      <div
        v-for="field in fields"
        :key="field.label"
        class="cp-card__field"
      >
        <dt>{{ field.label }}</dt>
        <dd :title="field.title ?? field.value">
          {{ field.value }}
        </dd>
      </div>
    </dl>

    <div
      v-if="profile.tags.length > 0"
      class="cp-card__tags"
    >
      <span
        v-for="tag in profile.tags"
        :key="tag"
      >#{{ tag }}</span>
    </div>
  </article>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import SIcon from '@/components/ui/SIcon.vue'
import type { GrokProfileDto } from '@/types'
import { GROK_FIELD_PLACEHOLDER, grokAuthModeLabel, resolveGrokBaseUrl } from '@/utils/grokProfiles'
import { formatBaseUrlDisplay } from '@/utils/text'

const props = withDefaults(defineProps<{
  profile: GrokProfileDto
  isCurrent: boolean
  disabled?: boolean
  busyAction?: 'apply' | 'delete' | null
}>(), {
  disabled: false,
  busyAction: null,
})

const emit = defineEmits<{
  apply: [name: string]
  edit: [name: string]
  delete: [name: string]
  toggle: [name: string, enabled: boolean]
}>()

const { t } = useI18n()
const fields = computed(() => [
  {
    label: t('grok.profiles.fields.baseUrl'),
    value: formatBaseUrlDisplay(resolveGrokBaseUrl(props.profile, t)),
    title: resolveGrokBaseUrl(props.profile, t),
  },
  { label: t('grok.profiles.fields.model'), value: props.profile.model || GROK_FIELD_PLACEHOLDER },
  { label: t('grok.profiles.fields.authMode'), value: grokAuthModeLabel(t, props.profile.auth_mode) },
  { label: t('grok.profiles.fields.apiBackend'), value: props.profile.api_backend || GROK_FIELD_PLACEHOLDER },
  { label: t('grok.profiles.fields.reasoningEffort'), value: props.profile.reasoning_effort || GROK_FIELD_PLACEHOLDER },
  {
    label: t('grok.profiles.fields.contextWindow'),
    value: props.profile.context_window?.toLocaleString() || GROK_FIELD_PLACEHOLDER,
  },
])

const menuOpen = ref(false)
const menuButton = ref<HTMLButtonElement | null>(null)
const menuPanel = ref<HTMLElement | null>(null)
const menuItems = () => Array.from(menuPanel.value?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]') ?? [])

const closeMenu = (restoreFocus = false) => {
  menuOpen.value = false
  if (restoreFocus) menuButton.value?.focus()
}

const toggleMenu = async () => {
  menuOpen.value = !menuOpen.value
  if (menuOpen.value) {
    await nextTick()
    menuItems()[0]?.focus()
  }
}

const onMenuKeydown = (event: KeyboardEvent) => {
  const items = menuItems()
  if (event.key === 'Escape') {
    event.preventDefault()
    closeMenu(true)
    return
  }
  if (items.length === 0) return
  const index = items.indexOf(document.activeElement as HTMLButtonElement)
  if (event.key === 'ArrowDown') {
    event.preventDefault()
    items[(index + 1) % items.length]?.focus()
  } else if (event.key === 'ArrowUp') {
    event.preventDefault()
    items[(index - 1 + items.length) % items.length]?.focus()
  }
}

const onDocumentPointerDown = (event: MouseEvent) => {
  const target = event.target as Node
  if (!menuOpen.value || menuPanel.value?.contains(target) || menuButton.value?.contains(target)) return
  closeMenu()
}

const selectAction = (action: 'edit' | 'toggle' | 'delete') => {
  if (action === 'edit') emit('edit', props.profile.name)
  else if (action === 'toggle') emit('toggle', props.profile.name, !props.profile.enabled)
  else emit('delete', props.profile.name)
  closeMenu(true)
}

watch(menuOpen, (open) => {
  if (open) document.addEventListener('mousedown', onDocumentPointerDown)
  else document.removeEventListener('mousedown', onDocumentPointerDown)
})

onBeforeUnmount(() => document.removeEventListener('mousedown', onDocumentPointerDown))
</script>

<style scoped>
.cp-card {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 0.625rem;
  padding: 0.875rem;
  color: var(--cp-ink-1);
  border-radius: var(--radius-lg);
}

.cp-card--active { border-left: 2px solid var(--cp-accent); }
.cp-card--off { opacity: 0.62; }

.cp-card__head,
.cp-card__actions {
  display: flex;
  min-width: 0;
  align-items: center;
  gap: 0.5rem;
}

.cp-card__dot {
  width: 0.5rem;
  height: 0.5rem;
  flex: 0 0 auto;
  background: var(--cp-ink-4);
  border-radius: 999px;
}

.cp-card__dot--good { background: var(--cp-good); }

.cp-card__name {
  min-width: 0;
  flex: 1;
  margin: 0;
  overflow: hidden;
  color: var(--cp-ink-0);
  font-family: var(--cp-mono);
  font-size: 0.9375rem;
  font-weight: 600;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.cp-card__kind,
.cp-card__current,
.cp-card__tags span {
  color: var(--cp-ink-2);
  font-size: 0.75rem;
}

.cp-card__actions { margin-left: auto; }

.cp-card__apply,
.cp-card__icon-btn,
.cp-card__menu-item {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.375rem;
  color: var(--cp-ink-2);
  background: transparent;
  border: 1px solid var(--cp-line-2);
  border-radius: var(--radius-sm);
  cursor: pointer;
}

.cp-card__apply {
  padding: 0.3rem 0.55rem;
  color: var(--cp-accent);
  font-size: 0.75rem;
}

.cp-card__icon-btn {
  width: 1.75rem;
  height: 1.75rem;
}

.cp-card__apply:disabled,
.cp-card__icon-btn:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.cp-card__menu {
  position: relative;
}

.cp-card__menu-pop {
  position: absolute;
  top: calc(100% + 0.25rem);
  right: 0;
  z-index: var(--layer-popover);
  display: flex;
  min-width: 10rem;
  flex-direction: column;
  gap: 0.125rem;
  padding: 0.25rem;
  background: var(--cp-bg-1);
  border: 1px solid var(--cp-line-2);
  border-radius: var(--radius-md);
  box-shadow: 0 12px 24px rgb(0 0 0 / 16%);
}

.cp-card__menu-item {
  justify-content: flex-start;
  width: 100%;
  padding: 0.45rem 0.55rem;
  border-color: transparent;
  font-size: 0.8125rem;
}

.cp-card__menu-item:hover {
  background: var(--cp-bg-3);
}

.cp-card__menu-item--danger:hover {
  color: var(--cp-danger);
}

.cp-card__desc {
  margin: 0;
  color: var(--cp-ink-2);
  font-size: 0.8125rem;
  line-height: 1.5;
}

.cp-card__fields {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.5rem 1rem;
  margin: 0;
}

.cp-card__field {
  min-width: 0;
}

.cp-card__field dt {
  color: var(--cp-ink-3);
  font-size: 0.75rem;
}

.cp-card__field dd {
  margin: 0.2rem 0 0;
  overflow: hidden;
  color: var(--cp-ink-0);
  font-family: var(--cp-mono);
  font-size: 0.8125rem;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.cp-card__tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem;
}

.cp-card__tags span {
  padding: 0.1rem 0.4rem;
  background: var(--cp-bg-3);
  border: 1px solid var(--cp-line-2);
  border-radius: var(--radius-sm);
}

.cp-card__spin {
  animation: grok-card-spin 1s linear infinite;
}

@keyframes grok-card-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  .cp-card__spin {
    animation: none;
  }
}
</style>

// ccr-ui/src/features/grok/profiles/GrokProfileCard.tsx
import { memo, useCallback, useEffect, useRef, useState, type RefObject } from 'react'
import type { GrokProfileDto } from '@/types'
import { SIcon } from '@/ui'
import { GROK_FIELD_PLACEHOLDER, grokAuthModeLabel, resolveGrokBaseUrl } from '@/utils/grokProfiles'
import { formatBaseUrlDisplay } from '@/utils/text'
import { t } from '../locale'

interface GrokProfileCardProps {
  profile: GrokProfileDto
  isCurrent: boolean
  disabled?: boolean
  busyAction?: 'apply' | 'delete' | null
  onApply: (name: string) => void
  onEdit: (name: string) => void
  onDelete: (name: string) => void
  onToggle: (name: string, enabled: boolean) => void
}

function CardMenu({
  open,
  disabled,
  enabled,
  deleting,
  menuButton,
  menuPanel,
  onToggleMenu,
  onEdit,
  onToggle,
  onDelete,
}: {
  open: boolean
  disabled: boolean
  enabled: boolean
  deleting: boolean
  menuButton: RefObject<HTMLButtonElement | null>
  menuPanel: RefObject<HTMLDivElement | null>
  onToggleMenu: () => void
  onEdit: () => void
  onToggle: () => void
  onDelete: () => void
}) {
  return (
    <>
      <button
        ref={menuButton}
        type="button"
        className="rounded-md p-1 text-text-muted disabled:opacity-50"
        disabled={disabled}
        aria-expanded={open}
        aria-label={t('grok.profiles.overflowMenu')}
        onClick={onToggleMenu}
      >
        <SIcon name="MenuDots" size="w-4 h-4" />
      </button>
      {open ? (
        <div ref={menuPanel} className="absolute z-20 mt-8 rounded-md border border-border-default bg-bg-elevated p-1 shadow-lg" role="menu">
          <button type="button" role="menuitem" className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm" onClick={onEdit}>
            <SIcon name="Edit2" size="w-4 h-4" />
            {t('grok.profiles.actions.edit')}
          </button>
          <button type="button" role="menuitem" className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm" onClick={onToggle}>
            <SIcon name={enabled ? 'Pause' : 'Play'} size="w-4 h-4" />
            {enabled ? t('grok.profiles.actions.disable') : t('grok.profiles.actions.enable')}
          </button>
          <button type="button" role="menuitem" className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-accent-danger" onClick={onDelete}>
            <SIcon name={deleting ? 'RefreshCw' : 'Trash2'} size="w-4 h-4" />
            {t('grok.profiles.actions.delete')}
          </button>
        </div>
      ) : null}
    </>
  )
}

export const GrokProfileCard = memo(function GrokProfileCard({
  profile,
  isCurrent,
  disabled = false,
  busyAction = null,
  onApply,
  onEdit,
  onDelete,
  onToggle,
}: GrokProfileCardProps) {
  const [menuOpen, setMenuOpen] = useState(false)
  const menuButton = useRef<HTMLButtonElement | null>(null)
  const menuPanel = useRef<HTMLDivElement | null>(null)
  const fields = [
    {
      label: t('grok.profiles.fields.baseUrl'),
      value: formatBaseUrlDisplay(resolveGrokBaseUrl(profile, t)),
    },
    { label: t('grok.profiles.fields.model'), value: profile.model || GROK_FIELD_PLACEHOLDER },
    { label: t('grok.profiles.fields.authMode'), value: grokAuthModeLabel(t, profile.auth_mode) },
    { label: t('grok.profiles.fields.apiBackend'), value: profile.api_backend || GROK_FIELD_PLACEHOLDER },
    { label: t('grok.profiles.fields.reasoningEffort'), value: profile.reasoning_effort || GROK_FIELD_PLACEHOLDER },
  ]

  const closeMenu = useCallback((restoreFocus = false) => {
    setMenuOpen(false)
    if (restoreFocus) menuButton.current?.focus()
  }, [])

  const toggleMenu = useCallback(() => {
    setMenuOpen((open) => !open)
  }, [])

  useEffect(() => {
    if (!menuOpen) return
    const items = Array.from(menuPanel.current?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]') ?? [])
    items[0]?.focus()
    const onPointer = (event: MouseEvent) => {
      const target = event.target as Node
      if (menuPanel.current?.contains(target) || menuButton.current?.contains(target)) return
      closeMenu()
    }
    document.addEventListener('mousedown', onPointer)
    return () => document.removeEventListener('mousedown', onPointer)
  }, [closeMenu, menuOpen])

  const handleApply = useCallback(() => {
    onApply(profile.name)
  }, [onApply, profile.name])
  const handleEdit = useCallback(() => {
    onEdit(profile.name)
    closeMenu(true)
  }, [closeMenu, onEdit, profile.name])
  const handleToggle = useCallback(() => {
    onToggle(profile.name, !profile.enabled)
    closeMenu(true)
  }, [closeMenu, onToggle, profile.enabled, profile.name])
  const handleDelete = useCallback(() => {
    onDelete(profile.name)
    closeMenu(true)
  }, [closeMenu, onDelete, profile.name])

  return (
    <article
      className={[
        'relative flex flex-col gap-2.5 rounded-lg border border-border-default bg-bg-surface p-3.5',
        isCurrent ? 'border-l-2 border-l-accent-primary' : '',
        profile.enabled ? '' : 'opacity-60',
      ].join(' ')}
      data-profile-name={profile.name}
    >
      <div className="flex min-w-0 items-center gap-2">
        <span className={isCurrent ? 'h-2 w-2 shrink-0 rounded-full bg-accent-success' : 'h-2 w-2 shrink-0 rounded-full bg-text-ghost'} />
        <h3 className="min-w-0 flex-1 truncate font-mono text-sm font-semibold text-text-primary" title={profile.name}>
          {profile.name}
        </h3>
        <span className="text-xs text-text-secondary">{t(`grok.profiles.profileKinds.${profile.profile_kind}`)}</span>
        <div className="flex items-center gap-2">
          {isCurrent ? (
            <span className="text-xs text-text-secondary">{t('grok.profiles.currentActive')}</span>
          ) : (
            <button
              type="button"
              className="inline-flex items-center gap-1 rounded-md border border-border-default px-2 py-1 text-xs disabled:opacity-50"
              disabled={disabled || !profile.enabled}
              onClick={handleApply}
            >
              <SIcon name={busyAction === 'apply' ? 'RefreshCw' : 'Play'} size="w-3 h-3" />
              {t('grok.profiles.actions.apply')}
            </button>
          )}
          <CardMenu
            open={menuOpen}
            disabled={disabled}
            enabled={profile.enabled}
            deleting={busyAction === 'delete'}
            menuButton={menuButton}
            menuPanel={menuPanel}
            onToggleMenu={toggleMenu}
            onEdit={handleEdit}
            onToggle={handleToggle}
            onDelete={handleDelete}
          />
        </div>
      </div>
      {profile.description ? <p className="text-sm text-text-secondary">{profile.description}</p> : null}
      <dl className="grid grid-cols-2 gap-2 text-xs">
        {fields.map((field) => (
          <div key={field.label}>
            <dt className="text-text-muted">{field.label}</dt>
            <dd className="truncate text-text-primary" title={field.value}>{field.value}</dd>
          </div>
        ))}
      </dl>
      {profile.tags.length > 0 ? (
        <div className="flex flex-wrap gap-1 text-xs text-text-secondary">
          {profile.tags.map((tag) => (
            <span key={tag}>#{tag}</span>
          ))}
        </div>
      ) : null}
    </article>
  )
})
