// ccr-ui/src/features/checkin/components/AccountDashboardCalendar.tsx
import { useMemo } from 'react'
import type { CheckinDashboardCalendar, CheckinDashboardDay } from '@/types/checkin'
import { useCheckinLocale } from '../hooks/useCheckinT'
import '../styles/calendar.css'

interface AccountDashboardCalendarProps {
  calendar: CheckinDashboardCalendar | null
}

const dayReward = (cell: CheckinDashboardDay): number | null => {
  const amount = cell.reward_amount ?? cell.income_increment
  if (amount === undefined || amount === null || amount <= 0) return null
  return amount
}

export function AccountDashboardCalendar({ calendar }: AccountDashboardCalendarProps) {
  const locale = useCheckinLocale()
  const isZh = locale.startsWith('zh')
  const tt = (zh: string, en: string) => (isZh ? zh : en)
  const weekLabels = isZh
    ? ['日', '一', '二', '三', '四', '五', '六']
    : ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

  const todayString = useMemo(() => {
    const now = new Date()
    const month = String(now.getMonth() + 1).padStart(2, '0')
    const day = String(now.getDate()).padStart(2, '0')
    return `${now.getFullYear()}-${month}-${day}`
  }, [])

  const cells = useMemo<(CheckinDashboardDay | null)[]>(() => {
    if (!calendar) return []
    const firstWeekday = new Date(calendar.year, calendar.month - 1, 1).getDay()
    const blanks: (CheckinDashboardDay | null)[] = Array.from({ length: firstWeekday }, () => null)
    return blanks.concat(calendar.days)
  }, [calendar])

  if (!calendar || cells.length === 0) {
    return (
      <div className="calendar-wrapper">
        <div className="calendar-empty">{tt('暂无日历数据', 'No calendar data yet')}</div>
      </div>
    )
  }

  return (
    <div className="calendar-wrapper">
      <div className="calendar-weekdays">
        {weekLabels.map((label) => (
          <div key={label} className="weekday-label">
            {label}
          </div>
        ))}
      </div>
      <div className="calendar-grid">
        {cells.map((cell, index) => (
          <CalendarCell
            key={cell ? cell.date : `pad-${calendar.year}-${calendar.month}-${index}`}
            cell={cell}
            today={todayString}
            isZh={isZh}
          />
        ))}
      </div>
      <div className="calendar-legend">
        <div className="legend-item">
          <span className="legend-dot checked" />
          {tt('已签到', 'Checked in')}
        </div>
        <div className="legend-item">
          <span className="legend-dot unchecked" />
          {tt('未签到', 'Missed')}
        </div>
        <div className="legend-item">
          <span className="legend-dot today" />
          {tt('今天', 'Today')}
        </div>
      </div>
    </div>
  )
}

function CalendarCell({
  cell,
  today,
  isZh,
}: {
  cell: CheckinDashboardDay | null
  today: string
  isZh: boolean
}) {
  if (!cell) return <div className="calendar-cell cell-empty" />
  const reward = dayReward(cell)
  const status = cell.is_checked_in
    ? isZh
      ? '已签到'
      : 'Checked in'
    : isZh
      ? '未签到'
      : 'Missed'
  const title = isZh
    ? `${cell.date} · ${status} · 奖励 ${reward !== null ? `+${reward.toFixed(2)}` : '-'}`
    : `${cell.date} · ${status} · Reward ${reward !== null ? `+${reward.toFixed(2)}` : '-'}`
  const classes = [
    'calendar-cell',
    cell.is_checked_in ? 'cell-checked' : 'cell-unchecked',
    cell.date === today ? 'cell-today' : '',
  ]
    .filter(Boolean)
    .join(' ')
  return (
    <div className={classes} title={title}>
      <span className="day-number">{Number(cell.date.slice(8, 10))}</span>
      {reward !== null ? <span className="day-increment">+{reward.toFixed(2)}</span> : null}
      {reward === null && cell.is_checked_in ? <span className="day-dot">·</span> : null}
    </div>
  )
}

// ccr-ui/src/views/checkin/components/AccountDashboardCalendar.vue
<template>
  <div class="calendar-wrapper">
    <div class="calendar-weekdays">
      <div
        v-for="label in weekLabels"
        :key="label"
        class="weekday-label"
      >
        {{ label }}
      </div>
    </div>

    <div
      v-if="cells.length === 0"
      class="calendar-empty"
    >
      {{ tt('暂无日历数据', 'No calendar data yet') }}
    </div>

    <div
      v-else
      class="calendar-grid"
    >
      <div
        v-for="(cell, index) in cells"
        :key="cell ? cell.date : `empty-${index}`"
        class="calendar-cell"
        :class="cellClass(cell)"
        :title="cell ? buildTitle(cell) : ''"
      >
        <template v-if="cell">
          <span class="day-number">{{ getDayNumber(cell.date) }}</span>
          <span
            v-if="dayReward(cell) !== null"
            class="day-increment"
          >
            +{{ dayReward(cell)!.toFixed(2) }}
          </span>
          <span
            v-else-if="cell.is_checked_in"
            class="day-dot"
            aria-hidden="true"
          >·</span>
        </template>
      </div>
    </div>

    <div class="calendar-legend">
      <div class="legend-item">
        <span class="legend-dot checked" />
        {{ tt('已签到', 'Checked in') }}
      </div>
      <div class="legend-item">
        <span class="legend-dot unchecked" />
        {{ tt('未签到', 'Missed') }}
      </div>
      <div class="legend-item">
        <span class="legend-dot today" />
        {{ tt('今天', 'Today') }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { CheckinDashboardCalendar, CheckinDashboardDay } from '@/types/checkin'

const props = defineProps<{
  calendar: CheckinDashboardCalendar | null
}>()

const { locale } = useI18n()
const isZh = computed(() => locale.value.startsWith('zh'))
const tt = (zh: string, en: string) => (isZh.value ? zh : en)
const weekLabels = computed(() => (isZh.value
  ? ['日', '一', '二', '三', '四', '五', '六']
  : ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']))

const todayString = computed(() => {
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
})

const firstWeekday = computed(() => {
  if (!props.calendar) return 0
  return new Date(props.calendar.year, props.calendar.month - 1, 1).getDay()
})

const cells = computed<(CheckinDashboardDay | null)[]>(() => {
  if (!props.calendar) return []
  const blanks: (CheckinDashboardDay | null)[] = Array.from(
    { length: firstWeekday.value },
    () => null
  )
  return blanks.concat(props.calendar.days)
})

const getDayNumber = (date: string) => Number(date.slice(8, 10))

const dayReward = (cell: CheckinDashboardDay): number | null => {
  const amount = cell.reward_amount ?? cell.income_increment
  if (amount === undefined || amount === null || amount <= 0) return null
  return amount
}

const cellClass = (cell: CheckinDashboardDay | null) => {
  if (!cell) return 'cell-empty'

  const classes = [cell.is_checked_in ? 'cell-checked' : 'cell-unchecked']

  if (cell.date === todayString.value) {
    classes.push('cell-today')
  }

  return classes.join(' ')
}

const buildTitle = (cell: CheckinDashboardDay) => {
  const status = cell.is_checked_in ? tt('已签到', 'Checked in') : tt('未签到', 'Missed')
  const reward = dayReward(cell)
  const rewardText = reward !== null ? `+${reward.toFixed(2)}` : '-'
  return tt(`${cell.date} · ${status} · 奖励 ${rewardText}`, `${cell.date} · ${status} · Reward ${rewardText}`)
}
</script>

<style scoped>
.calendar-wrapper {
  display: flex;
  flex-direction: column;
  gap: 0.85rem;
}

.calendar-weekdays,
.calendar-grid {
  display: grid;
  grid-template-columns: repeat(7, minmax(0, 1fr));
}

.calendar-weekdays {
  gap: 0.45rem;
}

.weekday-label {
  color: var(--text-muted);
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-align: center;
}

.calendar-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 11rem;
  border-radius: 1rem;
  background: rgb(var(--color-bg-elevated-rgb) / 56%);
  border: 1px dashed rgb(var(--color-border-default-rgb) / 78%);
  color: var(--text-secondary);
  font-size: 0.88rem;
}

.calendar-grid {
  gap: 0.5rem;
}

.calendar-cell {
  position: relative;
  min-height: 3.9rem;
  border-radius: 0.85rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.22rem;
  border: 1px solid transparent;
  transition:
    transform 0.18s ease,
    border-color 0.18s ease,
    background-color 0.18s ease;
}

.calendar-cell:hover:not(.cell-empty) {
  transform: translateY(-1px);
}

.cell-empty {
  background: transparent;
  border-color: transparent;
}

.cell-checked {
  background: rgb(var(--color-accent-primary-rgb) / 12%);
  border-color: rgb(var(--color-accent-primary-rgb) / 34%);
  box-shadow: var(--shadow-inner);
}

.cell-unchecked {
  background: rgb(var(--color-bg-elevated-rgb) / 62%);
  border-color: rgb(var(--color-border-default-rgb) / 56%);
}

.cell-today {
  border-color: rgb(var(--color-accent-primary-rgb) / 62%) !important;
  box-shadow:
    0 0 0 2px rgb(var(--color-accent-primary-rgb) / 14%),
    0 8px 18px rgb(var(--color-accent-primary-rgb) / 10%);
}

.day-number {
  color: var(--text-primary);
  font-size: 0.92rem;
  font-weight: 700;
  line-height: 1;
  font-family: var(--font-mono);
}

.cell-checked .day-number {
  color: var(--accent-primary);
}

.day-increment {
  color: var(--accent-primary);
  font-size: 0.6rem;
  font-weight: 700;
  line-height: 1;
  font-family: var(--font-mono);
}

.day-dot {
  color: rgb(var(--color-accent-primary-rgb) / 78%);
  font-size: 1rem;
  line-height: 0.4;
  font-weight: 900;
}

.calendar-legend {
  display: flex;
  flex-wrap: wrap;
  gap: 0.85rem;
  color: var(--text-secondary);
  font-size: 0.75rem;
  font-weight: 600;
}

.legend-item {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
}

.legend-dot {
  width: 0.6rem;
  height: 0.6rem;
  border-radius: 999px;
  flex-shrink: 0;
}

.legend-dot.checked {
  background: var(--accent-primary);
}

.legend-dot.unchecked {
  background: rgb(var(--color-border-default-rgb) / 82%);
}

.legend-dot.today {
  background: transparent;
  border: 2px solid var(--accent-primary);
  box-shadow: 0 0 0 2px rgb(var(--color-accent-primary-rgb) / 14%);
}

@media (width <= 768px) {
  .calendar-cell {
    min-height: 3.2rem;
    border-radius: 0.75rem;
  }

  .day-number {
    font-size: 0.84rem;
  }

  .day-increment {
    font-size: 0.56rem;
  }
}
</style>
